/**
 * The dashboard pictograms, as a static map.
 *
 * Metro resolves `require` at build time, so the path cannot be built from
 * a variable — every asset has to be named here for it to be bundled at all.
 * Generated by scripts/make-symbols.py; regenerate that and this together.
 *
 * They are white on transparent and tinted where they are shown, so one
 * asset serves the red, amber and green states and the colour can never
 * disagree with the entry's own severity.
 */
export const SYMBOLS: Record<string, number> = {
  "abs": require("../assets/symbols/abs.png"),
  "airbag": require("../assets/symbols/airbag.png"),
  "battery": require("../assets/symbols/battery.png"),
  "brake": require("../assets/symbols/brake.png"),
  "bulb": require("../assets/symbols/bulb.png"),
  "catalytic": require("../assets/symbols/catalytic.png"),
  "coolant": require("../assets/symbols/coolant.png"),
  "cruise": require("../assets/symbols/cruise.png"),
  "door-ajar": require("../assets/symbols/door-ajar.png"),
  "dpf": require("../assets/symbols/dpf.png"),
  "droplet": require("../assets/symbols/droplet.png"),
  "engine": require("../assets/symbols/engine.png"),
  "epb": require("../assets/symbols/epb.png"),
  "esc-off": require("../assets/symbols/esc-off.png"),
  "ev-battery": require("../assets/symbols/ev-battery.png"),
  "ev-fault": require("../assets/symbols/ev-fault.png"),
  "ev-ready": require("../assets/symbols/ev-ready.png"),
  "fuel-pump": require("../assets/symbols/fuel-pump.png"),
  "glow-plug": require("../assets/symbols/glow-plug.png"),
  "high-beam": require("../assets/symbols/high-beam.png"),
  "hybrid": require("../assets/symbols/hybrid.png"),
  "key": require("../assets/symbols/key.png"),
  "oil-can": require("../assets/symbols/oil-can.png"),
  "oil-level-min": require("../assets/symbols/oil-level-min.png"),
  "pad-wear": require("../assets/symbols/pad-wear.png"),
  "plug": require("../assets/symbols/plug.png"),
  "radar-car": require("../assets/symbols/radar-car.png"),
  "rear-fog": require("../assets/symbols/rear-fog.png"),
  "regen": require("../assets/symbols/regen.png"),
  "seatbelt": require("../assets/symbols/seatbelt.png"),
  "skid-car": require("../assets/symbols/skid-car.png"),
  "snowflake": require("../assets/symbols/snowflake.png"),
  "spanner": require("../assets/symbols/spanner.png"),
  "start-stop": require("../assets/symbols/start-stop.png"),
  "steering": require("../assets/symbols/steering.png"),
  "suspension": require("../assets/symbols/suspension.png"),
  "thermometer": require("../assets/symbols/thermometer.png"),
  "transmission-temp": require("../assets/symbols/transmission-temp.png"),
  "turtle": require("../assets/symbols/turtle.png"),
  "tyre": require("../assets/symbols/tyre.png"),
  "warning-triangle": require("../assets/symbols/warning-triangle.png"),
  "washer": require("../assets/symbols/washer.png"),
  "water-in-fuel": require("../assets/symbols/water-in-fuel.png"),
};

export const symbolFor = (glyph?: string) =>
  glyph ? SYMBOLS[glyph] : undefined;
