import type { LibraryEntry } from "./types";

/**
 * The 32 warning lights a driver actually sees. Browsable without spending a
 * scan, works offline, and gives the app something to be when the camera is
 * closed — a scanner with one screen feels like a demo.
 *
 * Ordered roughly by how urgent they are, so the dangerous ones are first.
 */
export const DASHLIGHT_LIBRARY: LibraryEntry[] = [
  {
    id: "oil-pressure",
    title: "ضغط الزيت",
    subtitle: "Oil Pressure",
    severity: "critical",
    summary: "ضغط زيت المحرك نزل عن الحد الآمن. المحرك ممكن يتلف خلال دقائق.",
    action: "اوقف على جنب فوراً وطفّي المحرك. لا تكمل سواقة أبداً.",
  },
  {
    id: "coolant-temp",
    title: "حرارة المحرك",
    subtitle: "Coolant Temperature",
    severity: "critical",
    summary: "المحرك سخن فوق الحد. الاستمرار بالسواقة ممكن يشوي رأس المحرك.",
    action: "اوقف، طفّي المكيف، وافتح الشبابيك. استنى المحرك يبرد قبل ما تفتح الراديتر.",
  },
  {
    id: "brake",
    title: "الفرامل",
    subtitle: "Brake System",
    severity: "critical",
    summary: "خلل بنظام الفرامل، أو زيت الفرامل ناقص، أو الفرامل اليدوية مرفوعة.",
    action: "تأكد إن اليدوي منزّل. إذا اللمبة ضلت، اوقف — الفرامل ممكن تفشل.",
  },
  {
    id: "charging",
    title: "الشحن / البطارية",
    subtitle: "Battery / Charging",
    severity: "critical",
    summary: "الدينمو مش عم يشحن. السيارة عم تمشي على البطارية وحدها وممكن تطفى.",
    action: "طفّي المكيف والأضواء غير الضرورية وروح على أقرب ورشة مباشرة.",
  },
  {
    id: "airbag",
    title: "الوسادة الهوائية",
    subtitle: "Airbag / SRS",
    severity: "critical",
    summary: "خلل بنظام الوسائد الهوائية. ممكن ما تنفتح عند الحادث.",
    action: "السيارة بتمشي، بس الحماية معطّلة. صلّحها بأقرب وقت.",
  },
  {
    id: "power-steering",
    title: "الدركسيون المعزّز",
    subtitle: "Power Steering",
    severity: "critical",
    summary: "فقدان تعزيز التوجيه. الدركسيون بيصير ثقيل جداً فجأة.",
    action: "امسك الدركسيون بقوة، خفّف السرعة، واوقف بمكان آمن.",
  },
  {
    id: "check-engine",
    title: "فحص المحرك",
    subtitle: "Check Engine",
    severity: "warning",
    summary: "خلل بالمحرك أو نظام العادم. الأسباب كتيرة — من غطا البنزين المفكوك لحساس معطّل.",
    action: "شدّ غطا خزان البنزين وشوف. إذا ضلت، افحص بجهاز OBD.",
  },
  {
    id: "check-engine-flashing",
    title: "فحص المحرك (وامضة)",
    subtitle: "Check Engine — Flashing",
    severity: "critical",
    summary: "اللمبة الوامضة تعني احتراق ناقص عم يدمّر الحساس الحفاز الآن.",
    action: "خفّف السرعة واوقف. الوامضة أخطر بكتير من الثابتة.",
  },
  {
    id: "transmission",
    title: "حرارة الجير",
    subtitle: "Transmission Temperature",
    severity: "critical",
    summary: "ناقل الحركة سخن. السواقة بهالحالة بتقصّر عمر الجير كتير.",
    action: "اوقف وخلّي المحرك دائر بالوضع المحايد لتبريد الجير.",
  },
  {
    id: "abs",
    title: "نظام ABS",
    subtitle: "Anti-lock Braking",
    severity: "warning",
    summary: "نظام منع انغلاق الفرامل معطّل. الفرامل العادية بتشتغل بس بدون ABS.",
    action: "سوق بحذر وباعد المسافة، خصوصاً على طريق مبلول. صلّحها قريباً.",
  },
  {
    id: "tpms",
    title: "ضغط الإطارات",
    subtitle: "Tire Pressure (TPMS)",
    severity: "warning",
    summary: "ضغط إطار أو أكثر واطي. بيزيد استهلاك البنزين وخطر الانفجار.",
    action: "افحص الإطارات الأربعة والاحتياطي واملاهم للضغط المكتوب على باب السائق.",
  },
  {
    id: "traction",
    title: "التحكم بالجر",
    subtitle: "Traction Control",
    severity: "info",
    summary: "لو بتومض: النظام شغال هلق لأن الإطارات عم تزحلق. لو ثابتة: النظام معطّل.",
    action: "الوامضة طبيعية — خفّف السرعة. الثابتة بتحتاج فحص.",
  },
  {
    id: "esp",
    title: "الثبات الإلكتروني",
    subtitle: "ESP / Stability Control",
    severity: "warning",
    summary: "نظام الثبات مطفي أو فيه خلل. السيارة بتفقد المساعدة عند الانزلاق.",
    action: "شوف إذا ضغطت زر ESP OFF بالغلط. إذا لأ، افحصها.",
  },
  {
    id: "glow-plug",
    title: "شمعات التسخين (ديزل)",
    subtitle: "Glow Plug — Diesel",
    severity: "info",
    summary: "طبيعية عند التشغيل البارد — بتنطفي لما تسخن. لو ضلت وامضة، في خلل.",
    action: "استنى تنطفي قبل ما تدير المحرك. لو ضلت وامضة، افحص الشمعات.",
  },
  {
    id: "dpf",
    title: "فلتر الجزيئات (ديزل)",
    subtitle: "DPF Filter",
    severity: "warning",
    summary: "فلتر عادم الديزل متسكّر — عادةً بسبب كثرة السواقة القصيرة.",
    action: "سوق على سرعة ثابتة ٢٠ دقيقة على طريق سريع لتنظيف الفلتر.",
  },
  {
    id: "adblue",
    title: "سائل AdBlue",
    subtitle: "AdBlue / DEF",
    severity: "warning",
    summary: "سائل معالجة العادم خلص أو قارب يخلص. السيارة ممكن ترفض تشتغل إذا فضي.",
    action: "عبّي AdBlue قبل ما يخلص تماماً.",
  },
  {
    id: "epb",
    title: "الفرامل اليدوية الإلكترونية",
    subtitle: "Electronic Parking Brake",
    severity: "warning",
    summary: "خلل بالفرامل اليدوية الإلكترونية أو إنها مرفوعة.",
    action: "جرّب تنزّلها وترفعها. إذا ضلت، صلّحها قبل ما توقف بمنحدر.",
  },
  {
    id: "water-in-fuel",
    title: "ماء بالوقود",
    subtitle: "Water in Fuel",
    severity: "warning",
    summary: "تجمّع ماء بفلتر الديزل. ممكن يتلف مضخة الوقود.",
    action: "صرّف فلتر الوقود أو روح على الورشة قريباً.",
  },
  {
    id: "catalytic",
    title: "الحساس الحفاز",
    subtitle: "Catalytic Converter",
    severity: "warning",
    summary: "الحساس الحفاز سخن أو ما عاد يشتغل صح.",
    action: "خفّف الحمل على المحرك وافحص — القطعة غالية إذا تلفت.",
  },
  {
    id: "service",
    title: "موعد الصيانة",
    subtitle: "Service Due",
    severity: "info",
    summary: "وصلت مسافة أو مدة الصيانة الدورية.",
    action: "احجز موعد تغيير زيت وصيانة.",
  },
  {
    id: "oil-level",
    title: "مستوى الزيت",
    subtitle: "Oil Level",
    severity: "warning",
    summary: "منسوب الزيت واطي — غير عن لمبة ضغط الزيت الحمرا.",
    action: "افحص بالمقياس وضيف زيت من النوع المناسب.",
  },
  {
    id: "fuel-low",
    title: "الوقود شارف يخلص",
    subtitle: "Low Fuel",
    severity: "info",
    summary: "باقي عادةً ٥٠–٨٠ كم حسب السيارة.",
    action: "عبّي قريباً — السواقة على خزان فاضي بتضر مضخة البنزين.",
  },
  {
    id: "washer",
    title: "ماء المساحات",
    subtitle: "Washer Fluid",
    severity: "info",
    summary: "خزان ماء غسيل الزجاج فاضي.",
    action: "عبّي الخزان.",
  },
  {
    id: "door-ajar",
    title: "باب مفتوح",
    subtitle: "Door Ajar",
    severity: "warning",
    summary: "باب أو صندوق أو غطا محرك مش مسكّر صح.",
    action: "اوقف وسكّر الباب — خطير على السرعات العالية.",
  },
  {
    id: "seatbelt",
    title: "حزام الأمان",
    subtitle: "Seat Belt",
    severity: "warning",
    summary: "حزام السائق أو أحد الركاب مش مربوط.",
    action: "اربط الحزام.",
  },
  {
    id: "immobilizer",
    title: "نظام الحماية",
    subtitle: "Immobilizer / Security",
    severity: "warning",
    summary: "السيارة ما تعرّفت على المفتاح. ممكن بطارية المفتاح فاضية.",
    action: "قرّب المفتاح من زر التشغيل أو بدّل بطاريته.",
  },
  {
    id: "key-battery",
    title: "بطارية المفتاح",
    subtitle: "Key Fob Battery",
    severity: "info",
    summary: "بطارية الريموت شارفت تخلص.",
    action: "بدّل البطارية قبل ما تعلق برّا.",
  },
  {
    id: "high-beam",
    title: "الأضواء العالية",
    subtitle: "High Beam",
    severity: "info",
    summary: "الأضواء العالية شغالة (أزرق عادةً).",
    action: "طفّيها عند مقابلة سيارات — بتعمي السائق المقابل.",
  },
  {
    id: "fog",
    title: "أضواء الضباب",
    subtitle: "Fog Lights",
    severity: "info",
    summary: "أضواء الضباب الأمامية أو الخلفية شغالة.",
    action: "طفّيها بالجو الصافي — الخلفية بتزعج اللي وراك.",
  },
  {
    id: "cruise",
    title: "مثبّت السرعة",
    subtitle: "Cruise Control",
    severity: "info",
    summary: "مثبّت السرعة مفعّل.",
    action: "معلومة فقط. الفرملة بتلغيه.",
  },
  {
    id: "lane-departure",
    title: "تحذير مغادرة المسار",
    subtitle: "Lane Departure",
    severity: "info",
    summary: "النظام لاحظ إنك خرجت عن مسارك بدون إشارة.",
    action: "معلومة فقط — بس خد بريك إذا تكررت، ممكن تكون تعبان.",
  },
  {
    id: "master-warning",
    title: "التحذير العام",
    subtitle: "Master Warning",
    severity: "warning",
    summary: "تحذير عام — التفاصيل بتطلع على شاشة العدادات.",
    action: "اقرأ الرسالة على الشاشة لتعرف السبب الحقيقي.",
  },
];
