/**
 * Affiliate monetization — the layer that turns Luka's product links into income.
 *
 * Every product URL the agent surfaces passes through `monetizeUrl` before it
 * reaches a shopper, so a purchase made through that link is credited to the
 * operator's affiliate account.
 *
 * Nothing is applied unless the operator configured their OWN affiliate IDs via
 * environment variables. With no configuration every function here is a no-op
 * and links are returned untouched — Luka keeps working exactly as before.
 *
 * Two kinds of rule cover essentially every affiliate program in existence:
 *
 *   "params"   — append tracking parameters to the store URL itself.
 *                (Amazon Associates, eBay Partner Network, most direct programs)
 *   "deeplink" — wrap the store URL inside a network's redirect URL.
 *                (Admitad, Awin, CJ, Impact, ArabClicks, Rakuten — the networks
 *                 that most regional Gulf/MENA stores run their programs through)
 */

export type AffiliateRule =
  | {
      network: string;
      /** Domain suffixes this rule applies to, e.g. ["amazon.ae"]. */
      match: string[];
      type: "params";
      /** Query parameters to set on the target URL (existing ones are overwritten). */
      params: Record<string, string>;
    }
  | {
      network: string;
      match: string[];
      type: "deeplink";
      /** Network URL with `{url}` (percent-encoded target) or `{url_raw}`. */
      template: string;
    };

export type MonetizedLink = {
  /** The link to hand to the shopper — affiliate-tagged when a rule matched. */
  url: string;
  /** The link exactly as the agent found it on the web. */
  original: string;
  /** Which program earns this click, or null when no rule matched. */
  network: string | null;
};

/** Analytics parameters from wherever the agent found the link. Ours replace them. */
const TRACKING_JUNK = [
  /^utm_/i,
  /^gclid$/i,
  /^fbclid$/i,
  /^msclkid$/i,
  /^igshid$/i,
  /^_branch_match_id$/i,
];

/** Amazon marketplaces, so one `AFF_AMAZON_TAG` can cover the common ones. */
const AMAZON_DOMAINS = [
  "amazon.com",
  "amazon.ae",
  "amazon.sa",
  "amazon.eg",
  "amazon.co.uk",
  "amazon.de",
  "amazon.fr",
  "amazon.it",
  "amazon.es",
  "amazon.nl",
  "amazon.se",
  "amazon.pl",
  "amazon.com.tr",
  "amazon.ca",
  "amazon.com.mx",
  "amazon.com.br",
  "amazon.co.jp",
  "amazon.in",
  "amazon.sg",
  "amazon.com.au",
];

function env(name: string): string | undefined {
  const v = process.env[name];
  return typeof v === "string" && v.trim() !== "" ? v.trim() : undefined;
}

function parseJsonEnv<T>(name: string): T | undefined {
  const raw = env(name);
  if (!raw) return undefined;
  try {
    return JSON.parse(raw) as T;
  } catch {
    console.warn(`[affiliate] ${name} is not valid JSON — ignoring it.`);
    return undefined;
  }
}

/**
 * Build the active rule set from environment configuration.
 *
 * Convenience variables cover the two programs with a stable, documented link
 * format; `AFF_RULES` covers everything else without touching code.
 */
export function getAffiliateRules(): AffiliateRule[] {
  const rules: AffiliateRule[] = [];

  // --- Amazon Associates -----------------------------------------------
  // Per-marketplace tags, since Associates issues a separate tag per region.
  // AFF_AMAZON_TAGS='{"amazon.ae":"luka-21","amazon.com":"luka-20"}'
  const amazonTags = parseJsonEnv<Record<string, string>>("AFF_AMAZON_TAGS") ?? {};
  const amazonDefault = env("AFF_AMAZON_TAG");

  for (const domain of AMAZON_DOMAINS) {
    const tag = amazonTags[domain] ?? amazonDefault;
    if (!tag) continue;
    rules.push({
      network: "amazon",
      match: [domain],
      type: "params",
      params: { tag, linkCode: "ll1", language: "en_US" },
    });
  }

  // --- eBay Partner Network ---------------------------------------------
  const ebayCampid = env("AFF_EBAY_CAMPID");
  if (ebayCampid) {
    rules.push({
      network: "ebay",
      match: ["ebay.com", "ebay.co.uk", "ebay.de", "ebay.com.au"],
      type: "params",
      params: {
        mkcid: "1",
        mkrid: env("AFF_EBAY_MKRID") ?? "711-53200-19255-0",
        siteid: env("AFF_EBAY_SITEID") ?? "0",
        campid: ebayCampid,
        customid: env("AFF_EBAY_CUSTOMID") ?? "luka",
        toolid: "10001",
        mkevt: "1",
      },
    });
  }

  // --- AliExpress --------------------------------------------------------
  // NOTE: AliExpress tracks most reliably through links generated by their
  // portal/API. These parameters work for many storefront URLs but verify a
  // real click lands in your AliExpress dashboard before relying on it.
  const aliPid = env("AFF_ALIEXPRESS_PID");
  if (aliPid) {
    rules.push({
      network: "aliexpress",
      match: ["aliexpress.com", "aliexpress.us", "ar.aliexpress.com"],
      type: "params",
      params: { aff_platform: "link-c-api", aff_trace_key: aliPid, terminal_id: "luka" },
    });
  }

  // --- Anything else: fully operator-defined ----------------------------
  // AFF_RULES='[{"network":"admitad-noon","match":["noon.com"],
  //              "type":"deeplink","template":"https://ad.admitad.com/g/ABC123/?ulp={url}"}]'
  const custom = parseJsonEnv<AffiliateRule[]>("AFF_RULES");
  if (Array.isArray(custom)) {
    for (const rule of custom) {
      if (isValidRule(rule)) rules.push(rule);
      else console.warn("[affiliate] Skipping malformed rule in AFF_RULES:", rule);
    }
  }

  return rules;
}

function isValidRule(rule: unknown): rule is AffiliateRule {
  if (!rule || typeof rule !== "object") return false;
  const r = rule as Record<string, unknown>;
  if (typeof r.network !== "string" || !r.network.trim()) return false;
  if (!Array.isArray(r.match) || r.match.length === 0) return false;
  if (!r.match.every((m) => typeof m === "string" && m.trim())) return false;
  if (r.type === "params") {
    return !!r.params && typeof r.params === "object" && !Array.isArray(r.params);
  }
  if (r.type === "deeplink") {
    return (
      typeof r.template === "string" &&
      (r.template.includes("{url}") || r.template.includes("{url_raw}"))
    );
  }
  return false;
}

function hostMatches(hostname: string, suffix: string): boolean {
  const host = hostname.toLowerCase().replace(/^www\./, "");
  const needle = suffix.toLowerCase().replace(/^www\./, "");
  return host === needle || host.endsWith(`.${needle}`);
}

/** Parse a URL, tolerating the scheme-less forms models sometimes emit. */
function safeParse(raw: string): URL | null {
  const trimmed = raw?.trim();
  if (!trimmed) return null;
  const candidate = /^https?:\/\//i.test(trimmed) ? trimmed : `https://${trimmed}`;
  try {
    const url = new URL(candidate);
    if (url.protocol !== "http:" && url.protocol !== "https:") return null;
    if (!url.hostname.includes(".")) return null;
    return url;
  } catch {
    return null;
  }
}

/**
 * Attach the operator's affiliate credentials to a product link.
 *
 * Returns the original link unchanged when it is unparseable or when no
 * configured rule covers that store.
 */
export function monetizeUrl(raw: string): MonetizedLink {
  const original = (raw ?? "").trim();
  const url = safeParse(original);
  if (!url) return { url: original, original, network: null };

  const rule = getAffiliateRules().find((r) =>
    r.match.some((m) => hostMatches(url.hostname, m)),
  );
  if (!rule) return { url: original, original, network: null };

  // Drop upstream analytics params so our attribution isn't competing with
  // whatever tracking was on the page the agent found the link on.
  for (const key of Array.from(url.searchParams.keys())) {
    if (TRACKING_JUNK.some((re) => re.test(key))) url.searchParams.delete(key);
  }

  if (rule.type === "params") {
    for (const [key, value] of Object.entries(rule.params)) {
      if (typeof value === "string" && value.trim()) url.searchParams.set(key, value);
    }
    return { url: url.toString(), original, network: rule.network };
  }

  const target = url.toString();
  const deeplink = rule.template
    .replace(/\{url\}/g, encodeURIComponent(target))
    .replace(/\{url_raw\}/g, target);
  return { url: deeplink, original, network: rule.network };
}

/** True when a configured program covers this link. */
export function isMonetizable(raw: string): boolean {
  return monetizeUrl(raw).network !== null;
}

/** Which programs are live — used by the setup check so misconfiguration is visible. */
export function affiliateStatus(): {
  configured: boolean;
  networks: string[];
  ruleCount: number;
} {
  const rules = getAffiliateRules();
  const networks = Array.from(new Set(rules.map((r) => r.network))).sort();
  return { configured: rules.length > 0, networks, ruleCount: rules.length };
}
