import { L } from "../i18n";
import type { LibraryEntry } from "./types";

/**
 * 40 insects, arachnids and bites found worldwide. Identification and first
 * aid only — never diagnosis. Anaphylaxis signs appear wherever relevant,
 * because that is an emergency regardless of species.
 */
export const BUGSCAN_LIBRARY: LibraryEntry[] = [
  {
    id: "sting-anaphylaxis",
    title: L("Severe Allergic Reaction to a Sting", "حساسية شديدة من لسعة"),
    subtitle: "Sting Anaphylaxis (systemic allergic reaction)",
    severity: "critical",
    summary: L("Not an insect — the body's whole-system reaction to one. Warning signs start within minutes: swelling of the lips, tongue or throat, wheezing or tight chest, trouble swallowing, hives spreading far from the sting, dizziness, vomiting, or a sudden sense that something is badly wrong. It can happen on a sting the person tolerated fine last year.", "هذي مو حشرة — هذا رد فعل الجسم كله على لسعة. العلامات تبدأ خلال دقايق: انتفاخ بالشفايف أو اللسان أو الحلق، ضيق نفس أو صفير بالصدر، صعوبة بالبلع، طفح ينتشر بعيد عن مكان اللسعة، دوخة، استفراغ، أو إحساس مفاجئ إن في شي غلط تماماً. وممكن تصير من لسعة نفس الشخص تحمّلها عادي قبل سنة."),
    action: L("Use an adrenaline auto-injector into the outer thigh immediately if one is available, call emergency services even if the person improves, and keep them lying flat with legs raised.", "اضرب حقنة الأدرينالين بجنب الفخذ من برّه على طول إذا متوفرة، واتصل بالإسعاف حتى لو تحسّن، وخلّه نايم على ظهره ورجوله مرفوعة."),
  },
  {
    id: "infected-bite",
    title: L("Bite That Reddens and Spreads", "قرصة تحمرّ وتنتشر"),
    subtitle: "Cellulitis / Secondary Wound Infection",
    severity: "warning",
    summary: L("Any bite can get infected, and scratched bites on the legs and hands are the usual culprits. The tell is timing: normal bites peak at 24 hours and fade, an infection gets worse after day two — redness widening hour by hour, heat, throbbing pain, pus, red streaks running up the limb, fever or chills.", "أي قرصة ممكن تلتهب، وخصوصاً القرصات اللي تنحك على الرجول والإيدين. الفرق بالتوقيت: القرصة العادية توصل ذروتها بأول 24 ساعة وبعدين تخف، أما الالتهاب يزيد بعد اليوم الثاني — الاحمرار يتوسع ساعة بعد ساعة، سخونة بالمكان، ألم نبضي، صديد، خطوط حمر طالعة على الذراع أو الرجل، وحرارة أو قشعريرة."),
    action: L("Draw a pen line around the edge of the redness; if it spreads past that line, or you develop fever or red streaks, get medical care the same day.", "سوّ خط بالقلم حول حدود الاحمرار، وإذا طلع برّا الخط أو جتك حرارة أو خطوط حمر، روح للطبيب بنفس اليوم."),
  },
  {
    id: "black-widow",
    title: L("Black Widow", "الأرملة السوداء"),
    subtitle: "Black Widow (Latrodectus mactans and relatives)",
    severity: "critical",
    summary: L("Glossy black, pea-shaped abdomen, red hourglass on the underside; hides in woodpiles, sheds, garden furniture and outdoor toilets across the Americas, southern Europe, the Middle East and parts of Asia. The bite itself is often just a pinprick, then 30 to 60 minutes later comes cramping pain in the belly, back and thighs with heavy sweating. Medically significant, and worst in children and older adults.", "سودا لامعة، بطنها مدوّر مثل الحمصة وتحتها علامة حمرا شكل ساعة رملية؛ تختبي بين الحطب وبالمخازن وتحت أثاث الحديقة وبالحمامات الخارجية، وموجودة بالأمريكتين وجنوب أوروبا والشرق الأوسط وأجزاء من آسيا. العضة نفسها غالباً بس وخزة، وبعدها بنص ساعة لساعة يجي مغص وتشنج قوي بالبطن والظهر والفخاذ مع تعرّق شديد. خطيرة طبياً وأسوأ شي عند الأطفال وكبار السن."),
    action: L("Wash the site, apply a cold pack, never tie a tourniquet, and go to an emergency department now — antivenom and proper pain control exist.", "اغسل المكان، حط كمادة باردة، لا تربط الطرف أبداً، وروح الطوارئ على طول — في مصل مضاد وعلاج قوي للألم."),
  },
  {
    id: "redback-spider",
    title: L("Redback Spider", "عنكبوت الظهر الأحمر"),
    subtitle: "Redback Spider (Latrodectus hasselti)",
    severity: "critical",
    summary: L("Australia's black widow relative, now also established in Japan, New Zealand and parts of the Gulf. Small black spider with a red or orange stripe down the back, webbing under garden chairs, letterboxes and bin lids. Pain builds over an hour rather than starting severe, with sweating that is often patchy or one-sided, nausea and restlessness.", "قريبة الأرملة السوداء وموطنها أستراليا، وصارت موجودة كمان باليابان ونيوزيلندا وبعض دول الخليج. عنكبوت أسود صغير وعلى ظهره خط أحمر أو برتقالي، ويعشش تحت كراسي الحديقة وبصناديق البريد وتحت أغطية الزبالة. الألم يزيد تدريجياً خلال ساعة مو من أول لحظة، ويجي معه تعرّق غريب غالباً بمنطقة وحدة أو بجهة وحدة، وغثيان وعدم ارتياح."),
    action: L("Cold pack only — do not use a pressure bandage for this one — and get to a hospital; photograph the spider from a safe distance if you can.", "كمادة باردة بس — لا تلف ضماد ضاغط بهذي الحالة — وروح المستشفى، وإذا تقدر صوّر العنكبوت من مسافة آمنة."),
  },
  {
    id: "brown-recluse",
    title: L("Recluse Spider", "العنكبوت الناسك"),
    subtitle: "Brown / Mediterranean Recluse (Loxosceles reclusa, L. rufescens)",
    severity: "critical",
    summary: L("Small, uniformly tan, long-legged, with a dark violin shape behind the head and six eyes instead of eight. Lives behind stored boxes, in wardrobes and inside shoes — central and southern USA, the Mediterranean, the Middle East and parts of Asia. The bite is often painless at first, then over two to four days the centre turns blue-grey and sinks into a slow ulcer.", "عنكبوت صغير لونه بني فاتح موحّد، رجوله طويلة، وعلى ظهره علامة غامقة شكل كمان، وعنده ست عيون مو ثمانية. يعيش ورا الكراتين المخزّنة وبالدواليب وداخل الجزم — بوسط وجنوب الولايات المتحدة والبحر المتوسط والشرق الأوسط وأجزاء من آسيا. غالباً العضة ما توجع بالبداية، وبعدين خلال يومين لأربعة يصير وسطها رمادي مزرق وبعدين يتحول لقرحة تتوسع ببطء."),
    action: L("Clean it, apply a cold pack, keep the limb raised, never cut or suck the wound, and see a doctor if the centre darkens or you get fever.", "نظّف المكان، حط كمادة باردة، ارفع الطرف، ولا تفتح الجرح أو تمصّه أبداً، وراجع الطبيب إذا وسط الجرح غمّق أو جتك حرارة."),
  },
  {
    id: "sydney-funnel-web",
    title: L("Funnel-Web Spider", "عنكبوت الشبكة القمعية"),
    subtitle: "Sydney Funnel-Web (Atrax robustus, Hadronyche spp.)",
    severity: "critical",
    summary: L("Eastern Australia only, but one of the most dangerous spiders alive. Large, glossy black, thick-legged; rears up with fangs raised when threatened and often ends up in swimming pools, garages and shoes left outside. The bite hurts instantly and hard, followed within minutes by tingling around the mouth, drooling, muscle twitching, sweating and vomiting.", "موجود بس بشرق أستراليا، بس يعتبر من أخطر العناكب بالعالم. كبير، أسود لامع، رجوله غليظة، ولما يحس بخطر يرفع نفسه وينصب أنيابه، وكثير يلاقونه بالمسابح والكراجات وبالجزم اللي تنترك برّا. العضة توجع فوراً وبقوة، وخلال دقايق يجي تنميل حول الفم وسيلان لعاب ورجفة بالعضلات وتعرّق واستفراغ."),
    action: L("Apply a firm pressure-immobilisation bandage over the bite and up the entire limb, splint it, keep the person absolutely still, and call emergency services immediately.", "لف ضماد ضاغط بقوة على العضة وعلى الطرف كله لفوق، ثبّته بجبيرة، خلّي الشخص ما يتحرك أبداً، واتصل بالإسعاف فوراً."),
  },
  {
    id: "mouse-spider",
    title: L("Mouse Spider", "عنكبوت الفأر"),
    subtitle: "Mouse Spider (Missulena spp.)",
    severity: "critical",
    summary: L("Australian ground spider, stocky and black with an oversized glossy head and huge fangs; males wander in daylight after rain and are often mistaken for funnel-webs. Most bites are dry, but the venom of some species is comparable to funnel-web venom and the same antivenom is used, so it is always treated as a serious bite.", "عنكبوت أرضي أسترالي، جسمه ممتلئ وأسود وراسه كبير ولامع وأنيابه ضخمة؛ الذكور يتمشون بالنهار بعد المطر وكثير الناس تخلط بينه وبين عنكبوت الشبكة القمعية. أغلب العضات تكون بدون سم، بس سم بعض الأنواع يشبه سم القمعية ونفس المصل يُستخدم، فعشان كذا دايماً يتعاملون معها كعضة خطيرة."),
    action: L("Treat exactly like a funnel-web: pressure-immobilisation bandage over the bite and up the limb, splint, keep still, and call emergency services.", "تعامل معها بالضبط مثل القمعية: ضماد ضاغط على العضة وعلى الطرف كله، جبيرة، خلّه بلا حركة، واتصل بالإسعاف."),
  },
  {
    id: "deathstalker-scorpion",
    title: L("Deathstalker Scorpion", "عقرب الموت الأصفر"),
    subtitle: "Deathstalker (Leiurus quinquestriatus)",
    severity: "critical",
    summary: L("Pale straw-yellow, slender pincers, thin whip-like tail — the classic desert scorpion of North Africa, the Levant and the Arabian Peninsula. Shelters under stones, in wall cracks and inside shoes and bedding. The sting burns instantly and intensely with almost no swelling to show for it, and the danger is neurological: sweating, agitation, fast heartbeat and breathing trouble, especially in children.", "لونه أصفر باهت مثل القش، كلاّباته رفيعة وذيله دقيق مثل السوط — هذا عقرب الصحرا المعروف بشمال أفريقيا وبلاد الشام والجزيرة العربية. يختبي تحت الحجار وبشقوق الجدران وداخل الجزم والفرش. اللسعة تحرق فوراً وبشدة وبالكاد يبين ورم، والخطر مو بالمكان نفسه بل عصبي: تعرّق، هياج، دقات قلب سريعة، وضيق نفس، وبالأخص عند الأطفال."),
    action: L("Keep the person still and calm, apply a cold pack over cloth, never cut or suck the site, and get to a hospital now — antivenom works best early.", "خلّي الشخص هادي وما يتحرك، حط كمادة باردة فوق قماش، لا تفتح المكان ولا تمصّه أبداً، وروح المستشفى فوراً — المصل يفيد أكثر إذا كان بدري."),
  },
  {
    id: "fat-tailed-scorpion",
    title: L("Fat-Tailed Scorpion", "العقرب أبو ذيل عريض"),
    subtitle: "Fat-Tailed Scorpion (Androctonus spp.)",
    severity: "critical",
    summary: L("Dark brown to black, with a noticeably thick, heavy tail and small pincers — a rule of thumb across scorpions is that thick tail plus small pincers means potent venom. Common across the Gulf, the Middle East and North Africa in old walls, rubble and around houses. Severe burning pain, sweating, vomiting and cardiac effects; children are at real risk.", "لونه بني غامق لأسود، وذيله ملفت واضح وسميك وكلاّباته صغيرة — والقاعدة بالعقارب: ذيل عريض وكلاّبات صغيرة يعني سمّه قوي. منتشر بالخليج والشرق الأوسط وشمال أفريقيا بالجدران القديمة والأنقاض وحول البيوت. اللسعة تسبب حرقان شديد وتعرّق واستفراغ وتأثير على القلب، والأطفال معرّضين لخطر حقيقي."),
    action: L("Immobilise the limb at heart level, cold pack over cloth, no tourniquet and no cutting, and go straight to the nearest emergency department.", "ثبّت الطرف بمستوى القلب، كمادة باردة فوق قماش، بدون ربط وبدون تجريح، وروح على أقرب طوارئ مباشرة."),
  },
  {
    id: "bark-scorpion",
    title: L("Bark Scorpion", "عقرب اللحاء"),
    subtitle: "Arizona Bark Scorpion (Centruroides sculpturatus)",
    severity: "critical",
    summary: L("Small, slim and translucent straw-coloured — barely 7 cm — and unusual in that it climbs, so it stings people on walls, ceilings and in bedsheets rather than on the ground. Southwestern USA and northern Mexico. Intense pain and numbness with little to see, and in young children jerky eye movements, flailing limbs and breathing difficulty.", "عقرب صغير ونحيل ولونه شفاف مايل للقشي — بالكاد 7 سم — وميّزته إنه يتسلّق، فيلسع الناس على الجدران والسقوف وبين شراشف السرير مو بس على الأرض. موجود بجنوب غرب أمريكا وشمال المكسيك. اللسعة توجع بشدة وتخدّر بدون ما يبين شي تقريباً، وعند الأطفال الصغار تسبب حركات عين غير طبيعية ورفس بالأطراف وضيق نفس."),
    action: L("Wash, apply a cold pack, and take any child, older adult, or anyone with numbness spreading beyond the sting site to an emergency department now.", "اغسل المكان وحط كمادة باردة، وأي طفل أو كبير بالسن أو أي شخص التنميل عنده يتوسع برّا مكان اللسعة لازم يروح الطوارئ فوراً."),
  },
  {
    id: "indian-red-scorpion",
    title: L("Indian Red Scorpion", "العقرب الهندي الأحمر"),
    subtitle: "Indian Red Scorpion (Hottentotta tamulus)",
    severity: "critical",
    summary: L("Small, orange-red to brown with dark ridges, found across India, Pakistan, Nepal and Sri Lanka, often in rural houses and stored grain. Considered one of the deadliest scorpions in the world: severe local pain, then vomiting, cold clammy hands and feet, and in children fluid on the lungs causing rapid breathing and frothy cough within hours.", "عقرب صغير لونه برتقالي مايل للأحمر أو بني وعليه خطوط غامقة، وموجود بالهند وباكستان ونيبال وسريلانكا، وغالباً بالبيوت الريفية وبمخازن الحبوب. يعتبر من أخطر العقارب بالعالم: ألم موضعي شديد، وبعدها استفراغ وبرودة ورطوبة بالإيدين والرجول، وعند الأطفال ماي على الرئة يسبب تنفّس سريع وكحة برغوة خلال ساعات."),
    action: L("Get to a hospital immediately without waiting for symptoms — specific treatment exists and rapid breathing in a child is a late sign.", "روح المستشفى فوراً وبدون ما تنتظر تطلع الأعراض — في علاج مخصص، وسرعة التنفس عند الطفل تعتبر علامة متأخرة."),
  },
  {
    id: "paralysis-tick",
    title: L("Paralysis Tick", "قرادة الشلل"),
    subtitle: "Australian Paralysis Tick (Ixodes holocyclus)",
    severity: "critical",
    summary: L("East-coast Australian tick found in bush, gardens and on pets. While attached it releases a toxin, so trouble builds over three to five days: unsteady walking, drooping eyelids, double vision, slurred speech or weakness climbing stairs. It is also the main cause of the mammalian-meat (alpha-gal) allergy in Australia, and bites can trigger severe allergic reactions.", "قرادة موجودة بالساحل الشرقي لأستراليا بالأدغال والحدايق وعلى الحيوانات الأليفة. وهي عالقة بالجلد تفرز سم، فالمشكلة تكبر خلال ثلاثة لخمسة أيام: مشي غير متزن، تدلّي بالجفون، ازدواج بالرؤية، تلعثم بالكلام، أو ضعف عند طلوع الدرج. وهي كمان السبب الرئيسي لحساسية لحوم الثدييات بأستراليا، وعضتها ممكن تسبب حساسية شديدة."),
    action: L("Kill it in place with an ether-containing freeze spray and let it drop off rather than squeezing or pulling it, and get medical care immediately for any weakness, unsteadiness or drooping eyelids.", "اقتلها بمكانها ببخاخ التجميد اللي فيه إيثر وخلّها تطيح لحالها بدل ما تعصرها أو تشدّها، وروح للطبيب فوراً إذا صار أي ضعف أو عدم اتزان أو تدلّي بالجفون."),
  },
  {
    id: "giant-hornet",
    title: L("Giant Hornet", "الدبور العملاق"),
    subtitle: "Asian Giant Hornet / Yellow-Legged Hornet (Vespa mandarinia, V. velutina)",
    severity: "critical",
    summary: L("Very large hornets, up to 4–5 cm, orange-and-brown headed, nesting in the ground or in trees across East and South Asia, with the yellow-legged species now widespread in Europe. They sting repeatedly and swarm when a nest is disturbed — vibration from strimmers and mowers is the usual trigger. A handful of stings is painful; many stings deliver enough venom to damage muscle and kidneys.", "دبابير كبيرة جداً، يوصل طولها 4–5 سم، راسها برتقالي وبني، وتعشعش بالأرض أو بالشجر بشرق وجنوب آسيا، والنوع أصفر الأرجل صار منتشر بأوروبا. تلسع أكثر من مرة وتهجم بجماعة إذا انزعج عشها — وغالباً السبب اهتزاز ماكينة قص العشب أو الحشيش. كم لسعة توجع بشدة، لكن اللسعات الكثيرة تدخل كمية سم تضر العضلات والكلى."),
    action: L("Walk away covering your face without swatting, then wash and ice each sting; more than about ten stings, dark urine, or any breathing trouble means emergency care now.", "ابتعد وغطّ وجهك وبدون ما تحاول تضربهم، وبعدين اغسل وحط ثلج على كل لسعة؛ وإذا اللسعات أكثر من عشرة تقريباً أو صار البول غامق أو في ضيق نفس، روح الطوارئ فوراً."),
  },
  {
    id: "honeybee-sting",
    title: L("Honeybee Sting", "لسعة نحلة"),
    subtitle: "Honeybee (Apis mellifera)",
    severity: "warning",
    summary: L("The one stinger that stays behind — a black speck with a pulsing venom sac still pumping after the bee has gone. Bees sting only when trodden on, trapped in clothing or defending a hive. Expect sharp pain, a red lump and swelling that peaks around 24 to 48 hours; swelling of a whole hand or foot is common and alarming but not itself dangerous.", "النحلة النوع الوحيد اللي تترك إبرتها بالجلد — نقطة سودا صغيرة وعليها كيس سم يضخ حتى بعد ما تطير النحلة. النحل ما يلسع إلا إذا دستَ عليه أو انحبس بالملابس أو كان يدافع عن الخلية. توقّع ألم حاد وحبة حمرا وورم يوصل ذروته بعد 24 لـ 48 ساعة؛ وانتفاخ الكف كله أو القدم كلها شي شايع ومخوّف بس مو خطير بحد ذاته."),
    action: L("Scrape the sting out sideways with a card or fingernail instead of pinching it, wash, ice for ten minutes, and stay with the person for thirty minutes watching for throat or breathing symptoms.", "اكشط الإبرة من الجنب ببطاقة أو بظفرك بدل ما تمسكها وتعصرها، اغسل المكان، حط ثلج عشر دقايق، واقعد مع الشخص نص ساعة وراقب إذا صار شي بالحلق أو بالتنفس."),
  },
  {
    id: "wasp-yellowjacket",
    title: L("Wasp and Yellowjacket", "الزنبور والدبور الأصفر"),
    subtitle: "Common Wasp / Yellowjacket (Vespula, Polistes spp.)",
    severity: "warning",
    summary: L("Smooth, bright yellow and black with a narrow waist, and unlike bees they keep their stinger and can sting repeatedly. In late summer they turn aggressive around food, sweet drinks and bins. The real hazard is a wasp crawling into an open can — a sting inside the mouth or throat can swell the airway shut in someone with no allergy at all.", "جسمه أملس وأصفر فاقع مع أسود وخصره ضيق، وعكس النحل يحتفظ بإبرته ويقدر يلسع مرات ومرات. بآخر الصيف يصير عدواني حول الأكل والمشروبات الحلوة والزبالة. والخطر الحقيقي إنه يدخل بعلبة المشروب المفتوحة — واللسعة داخل الفم أو الحلق ممكن تسكّر مجرى الهوا حتى عند شخص ما عنده أي حساسية."),
    action: L("Wash and ice the sting and take an oral antihistamine for the itch; a sting inside the mouth or throat needs emergency care straight away.", "اغسل مكان اللسعة وحط ثلج وخذ حبة مضاد حساسية للحكة؛ وأي لسعة داخل الفم أو الحلق تروح فيها الطوارئ على طول."),
  },
  {
    id: "fire-ant",
    title: L("Fire Ant", "النملة النارية"),
    subtitle: "Red Imported Fire Ant (Solenopsis invicta)",
    severity: "warning",
    summary: L("Small reddish ants that build loose dome mounds with no central hole in lawns and parks — southern USA, Australia, China, and now spreading in Europe and the Gulf. They swarm up a leg silently and sting together on signal, leaving a ring of burning welts that turn into small sterile white pustules by the next day.", "نمل صغير لونه مايل للأحمر ويبني تلال ترابية مقببة بدون فتحة بالنص بالمروج والحدايق — بجنوب الولايات المتحدة وأستراليا والصين، وصار ينتشر بأوروبا والخليج. يطلع على الرجل بصمت وكلهم يلسعون بنفس اللحظة، ويخلّون دائرة حبوب تحرق تتحول ثاني يوم لبثور بيضا صغيرة معقّمة."),
    action: L("Brush them off dry — water does not make them let go — then wash with soap, ice the area, and leave the pustules intact, because popping them is how they get infected.", "انفضهم عن جلدك وهم ناشفين — الماي ما يخليهم يفكّون — وبعدها اغسل بصابون وحط ثلج، ولا تفقع البثور، لأن فقعها هو اللي يجيب الالتهاب."),
  },
  {
    id: "jack-jumper-ant",
    title: L("Jack Jumper Ant", "النملة القافزة"),
    subtitle: "Jack Jumper / Bull Ant (Myrmecia spp.)",
    severity: "warning",
    summary: L("Large black-and-orange Australian ants that hop toward you in a series of jumps and sting with the abdomen while gripping with the jaws. The sting is genuinely severe — burning pain for hours — but the reason it matters is that in parts of Australia this ant causes more sting anaphylaxis than bees and wasps combined.", "نمل أسترالي كبير لونه أسود وبرتقالي ويجي عليك نطّ نطّ، ويلسع بمؤخرته وهو ماسك بفكوكه. اللسعة موجعة جداً فعلاً — حرقان يستمر ساعات — بس أهميتها إن بمناطق من أستراليا هذي النملة تسبب حساسية شديدة أكثر من النحل والزنابير مع بعض."),
    action: L("Ice the sting and take an antihistamine, and if there is any lip or throat swelling, wheeze or dizziness, use adrenaline and call emergency services.", "حط ثلج على مكان اللسعة وخذ مضاد حساسية، وإذا صار انتفاخ بالشفايف أو الحلق أو صفير بالصدر أو دوخة، اضرب الأدرينالين واتصل بالإسعاف."),
  },
  {
    id: "lyme-tick",
    title: L("Deer Tick", "قرادة الغزلان"),
    subtitle: "Blacklegged / Castor Bean Tick (Ixodes scapularis, I. ricinus)",
    severity: "warning",
    summary: L("The tick behind Lyme disease across North America, Europe and northern Asia. The dangerous stage is the nymph — the size of a poppy seed, easy to mistake for a freckle, usually found behind the knee, in the groin, at the waistband or along the hairline. The bite is painless; a red patch that expands over days into a circle wider than 5 cm is the sign that matters.", "هذي القرادة المسؤولة عن مرض لايم بأمريكا الشمالية وأوروبا وشمال آسيا. المرحلة الخطرة هي الحوريّة — بحجم بذرة الخشخاش وسهل تحسبها شامة، وغالباً تلاقيها ورا الركبة أو بالمنطقة الحساسة أو عند حزام البنطلون أو على حدود الشعر. العضة ما توجع؛ والعلامة المهمة هي بقعة حمرا تتوسع خلال أيام وتصير دايرة أكبر من 5 سم."),
    action: L("Grip it with fine tweezers right against the skin and pull straight out without twisting or burning it, note the date, and see a doctor if a spreading rash or flu-like illness follows within six weeks.", "امسكها بملقط رفيع لصق الجلد واسحبها لفوق مستقيم بدون لف وبدون ما تحرقها، سجّل التاريخ، وراجع الطبيب إذا طلع طفح يتوسع أو أعراض تشبه الإنفلونزا خلال ستة أسابيع."),
  },
  {
    id: "lone-star-tick",
    title: L("Lone Star Tick", "قرادة النجمة"),
    subtitle: "Lone Star Tick (Amblyomma americanum)",
    severity: "warning",
    summary: L("Round, reddish-brown, with a single white dot on the female's back; aggressive and fast-moving, common in the eastern and central USA. Besides local infections, its bite can switch on alpha-gal syndrome — an allergy to red meat where hives or stomach upset arrive three to six hours after eating beef, lamb or pork, so the meal never looks like the cause.", "قرادة مدوّرة لونها بني محمر وعلى ظهر الأنثى نقطة بيضا وحدة؛ سريعة وتلاحق الناس، ومنتشرة بشرق ووسط أمريكا. غير الالتهابات الموضعية، عضتها ممكن تشغّل حساسية الألفا-غال — يعني حساسية من اللحوم الحمرا، تطلع فيها طفح أو مغص بعد ثلاث لست ساعات من أكل لحم البقر أو الغنم، فما يخطر ببالك إن الأكل هو السبب."),
    action: L("Remove it with fine tweezers straight out, wash the site, and tell a doctor if hives or stomach cramps start hours after a red-meat meal in the months afterward.", "شيلها بملقط رفيع وسحبة مستقيمة، اغسل المكان، وخبّر الطبيب إذا صار عندك طفح أو مغص بعد ساعات من وجبة لحم بالشهور اللي بعدها."),
  },
  {
    id: "hyalomma-tick",
    title: L("Hyalomma Tick", "قرادة الهيالوما"),
    subtitle: "Hyalomma Tick (Hyalomma marginatum and relatives)",
    severity: "warning",
    summary: L("Large tick with banded, striped legs and long mouthparts, found on livestock and in dry grassland across the Middle East, Central Asia, the Balkans and southern Europe. Unusually, it actively hunts and will run toward a person. It is the main carrier of Crimean-Congo haemorrhagic fever, and the highest-risk exposures are handling livestock or crushing a tick with bare fingers.", "قرادة كبيرة رجولها مخططة ومنقّطة وفمها طويل، تلاقيها على المواشي وبالمراعي الجافة بالشرق الأوسط وآسيا الوسطى والبلقان وجنوب أوروبا. وشي غريب فيها إنها تطارد وتركض باتجاه الشخص. وهي الناقل الرئيسي لحمى القرم-الكونغو النزفية، وأخطر حالات التعرض هي التعامل مع المواشي أو تفقيع القرادة بالإصبع."),
    action: L("Remove it with tweezers while wearing gloves, never crush it between your fingers, and seek medical care urgently for fever, bruising or bleeding gums within two weeks.", "شيلها بملقط وأنت لابس قفاز، ولا تفقعها بين أصابعك أبداً، وروح للطبيب بسرعة إذا جتك حرارة أو كدمات أو نزيف باللثة خلال أسبوعين."),
  },
  {
    id: "mosquito",
    title: L("Mosquito Bite", "قرصة البعوض"),
    subtitle: "Mosquito (Culex, Aedes, Anopheles spp.)",
    severity: "warning",
    summary: L("An itchy pale bump with a tiny central dot, usually on exposed skin, appearing within minutes. The bite itself is trivial almost everywhere; what makes it matter is geography — Aedes (black with white leg bands, bites in daylight) carries dengue and Zika, Anopheles bites at night and carries malaria, Culex carries West Nile.", "حبة فاتحة تحكّ وفي نصها نقطة صغيرة، وغالباً على الجلد المكشوف وتطلع خلال دقايق. القرصة نفسها بسيطة بأغلب الأماكن؛ اللي يخليها مهمة هو المنطقة — بعوض الزاعجة (أسود وعلى رجوله خطوط بيضا ويقرص بالنهار) ينقل حمى الضنك وزيكا، والأنوفيليس يقرص بالليل وينقل الملاريا، والكيولكس ينقل حمى غرب النيل."),
    action: L("Cold pack and an antihistamine cream for the itch, and see a doctor for a blood test — not wait-and-see — for any fever within three weeks of being in a malaria or dengue area.", "كمادة باردة وكريم مضاد للحساسية للحكة، وإذا جتك حرارة خلال ثلاثة أسابيع من وجودك بمنطقة ملاريا أو ضنك روح للطبيب وسوّ تحليل دم، لا تنتظر وتشوف."),
  },
  {
    id: "sandfly",
    title: L("Sandfly", "ذبابة الرمل"),
    subtitle: "Sandfly (Phlebotomus, Lutzomyia spp.)",
    severity: "warning",
    summary: L("Tiny, silent, hairy flies barely 3 mm across that bite at dusk and pass straight through ordinary mosquito netting. Common in the Middle East, the Mediterranean, Central and South Asia. Bites come in clusters and itch fiercely, and in endemic areas a single bite can leave a painless sore that refuses to heal over weeks — cutaneous leishmaniasis.", "ذبابة صغيرة جداً وصامتة وجسمها مشعر بالكاد 3 مم، تقرص وقت المغرب وتعدي من ثقوب الناموسية العادية. منتشرة بالشرق الأوسط والبحر المتوسط وآسيا الوسطى والجنوبية. القرصات تجي بمجموعات وتحكّ بشدة، وبالمناطق الموبوءة قرصة وحدة ممكن تخلّي قرحة ما توجع وترفض تطيب لأسابيع — وهذي اللشمانيا الجلدية."),
    action: L("Wash and use an antihistamine for the itch, and see a doctor for any bite that becomes a painless ulcer still open after three or four weeks.", "اغسل المكان واستخدم مضاد حساسية للحكة، وراجع الطبيب إذا صارت القرصة قرحة ما توجع وباقية مفتوحة بعد ثلاثة أو أربعة أسابيع."),
  },
  {
    id: "blackfly",
    title: L("Blackfly", "الذبابة السوداء"),
    subtitle: "Blackfly / Buffalo Gnat (Simulium spp.)",
    severity: "warning",
    summary: L("Small humpbacked flies that breed in fast-running streams and swarm around the head in late spring — northern Europe, North America, Asia. They cut the skin rather than piercing it, so the bite bleeds freely, then swells out of proportion over the next day, often closing an eyelid or fattening an ear.", "ذباب صغير ظهره محدودب، يتكاثر بالأنهار السريعة ويلتف حول الراس بآخر الربيع — بشمال أوروبا وأمريكا الشمالية وآسيا. يقص الجلد بدل ما يخزّه، فالقرصة تنزف بسهولة، وبعدين تنتفخ بشكل مبالغ فيه باليوم التالي، وكثير تسكّر العين أو تورّم الأذن."),
    action: L("Press until the bleeding stops, wash with soap, apply a cold pack, and keep nails short — most trouble from these bites comes from scratching them open.", "اضغط لين يوقف النزيف، اغسل بصابون، حط كمادة باردة، وقصّر أظافرك — أغلب مشاكل هالقرصات تجي من الحك لين تنفتح."),
  },
  {
    id: "horsefly",
    title: L("Horsefly", "ذبابة الخيل"),
    subtitle: "Horsefly / Deer Fly (Tabanus, Chrysops spp.)",
    severity: "warning",
    summary: L("Big, fast, with iridescent green or banded eyes; found near livestock, water and woodland worldwide. Only the female bites, and she slices the skin open with blade-like mouthparts, so it hurts immediately and hard. The wound is ragged rather than a neat puncture, which is exactly why these bites get infected more often than any other fly bite.", "ذبابة كبيرة وسريعة وعيونها خضرا لامعة أو مخططة؛ تلاقيها قرب المواشي والماي والغابات بكل العالم. الأنثى بس اللي تعض، وتشق الجلد بفم مثل الشفرة، فتوجع فوراً وبقوة. والجرح يطلع ممزّق مو خزّة نظيفة، وهذا بالضبط سبب إن قرصاتها تلتهب أكثر من أي ذبابة ثانية."),
    action: L("Wash thoroughly with soap and running water, apply a cold pack, cover it, and watch for spreading redness over the following two days.", "اغسل زين بصابون وماي جاري، حط كمادة باردة، غطّ الجرح، وراقب إذا الاحمرار يتوسع باليومين الجايين."),
  },
  {
    id: "flea-bite",
    title: L("Flea Bites", "قرصات البراغيث"),
    subtitle: "Cat / Dog Flea (Ctenocephalides felis, C. canis)",
    severity: "warning",
    summary: L("Small hard red bumps with a darker centre, arriving in lines or clusters of three and concentrated below the knee — ankles, shins, sock line. Usually means a pet or a recently empty flat. Harmless in themselves, but they itch relentlessly, and scratched flea bites are a very common route to skin infection in children.", "حبوب حمرا صغيرة وصلبة ونصها غامق، تجي بخط أو بمجموعات ثلاث ثلاث ومركّزة تحت الركبة — بالكواعب والسيقان وعند حد الجوارب. غالباً تعني إن في حيوان أليف بالبيت أو إن الشقة كانت فاضية فترة. بحد ذاتها مو خطيرة، بس حكّتها ما تهدّ، والحك المستمر من أشهر أسباب التهاب الجلد عند الأطفال."),
    action: L("Wash with soap, use a cold pack and an anti-itch cream, and treat the pet and the carpets on the same day or the bites simply keep coming.", "اغسل بصابون، استخدم كمادة باردة وكريم للحكة، وعالج الحيوان والسجاد بنفس اليوم وإلا القرصات بتستمر."),
  },
  {
    id: "scabies-mite",
    title: L("Scabies", "الجرب"),
    subtitle: "Scabies Mite (Sarcoptes scabiei)",
    severity: "warning",
    summary: L("Not a bite but a mite living in the skin. Look for thin wavy grey lines a few millimetres long in the finger webs, wrists, elbows, waistband and around the nipples or genitals, with an itch that becomes unbearable at night. It spreads by prolonged skin contact and shared beds, so it runs through a household and is often mistaken for bedbugs for weeks.", "مو قرصة، هذا سوس يعيش داخل الجلد. دوّر على خطوط رفيعة متعرجة رمادية طولها ملّيمترات بين الأصابع وبالمعاصم والمرافق وعند الخصر وحول الحلمات أو المنطقة الحساسة، مع حكة تصير لا تنطاق بالليل. ينتقل بالتلامس الطويل ومشاركة الفراش، فيمشي بالبيت كله وكثير الناس تحسبه بق فراش لأسابيع."),
    action: L("See a doctor for the prescribed treatment, treat every person in the household on the same day even if they have no itch, and hot-wash all bedding and clothing.", "راجع الطبيب وخذ العلاج الموصوف، وعالج كل أهل البيت بنفس اليوم حتى لو ما عندهم حكة، واغسل كل الفرش والملابس بماي حار."),
  },
  {
    id: "chigger",
    title: L("Chigger", "سوس الحصاد"),
    subtitle: "Chigger / Harvest Mite (Trombicula, Neotrombicula spp.)",
    severity: "warning",
    summary: L("Microscopic mite larvae picked up from long grass in summer. They cannot be seen and they do not burrow — despite the folklore, they attach where clothing is tight and feed on dissolved skin, then drop off. The result is a line of intensely itchy red bumps exactly along the sock line, waistband and bra line, itching hardest 24 to 48 hours later.", "يرقات سوس مجهرية تلتصق فيك من العشب الطويل بالصيف. ما تنشاف وما تحفر داخل الجلد — عكس اللي يقولونه الناس، هي تتعلّق بالأماكن اللي الملابس ضيقة فيها وتتغذى على الجلد اللي تذوّبه وبعدين تطيح. والنتيجة صف حبوب حمرا حكتها قوية بالضبط عند حد الجوارب والخصر وخط حمالة الصدر، وأقوى حكة تكون بعد 24 لـ 48 ساعة."),
    action: L("Shower with soap as soon as you come in from grass, wash the clothes, and use a cold pack and anti-itch cream — nail polish and bleach do nothing and damage the skin.", "استحم بصابون أول ما ترجع من العشب، اغسل الملابس، واستخدم كمادة باردة وكريم للحكة — مناكير الأظافر والكلوركس ما يسوّون شي ويأذون الجلد."),
  },
  {
    id: "centipede-bite",
    title: L("Centipede Bite", "عضة أم أربعة وأربعين"),
    subtitle: "Giant Centipede (Scolopendra spp.)",
    severity: "warning",
    summary: L("Long flat many-legged arthropod, orange to dark brown, hiding under stones, pots and inside houses at night across the Mediterranean, Middle East, Asia, Australia and the Americas. It bites with modified front legs, leaving two puncture marks, and the pain is immediate and severe with swelling for a few hours. Serious complications are rare but the pain is real.", "مفصلية طويلة ومسطحة وكثيرة الأرجل، لونها برتقالي لبني غامق، تختبي تحت الحجار والأصص وداخل البيوت بالليل، وموجودة بالبحر المتوسط والشرق الأوسط وآسيا وأستراليا والأمريكتين. تعض برجليها الأماميتين المعدّلتين وتترك خزّتين، والألم يجي فوراً وقوي مع ورم لعدة ساعات. المضاعفات الخطيرة نادرة، بس الألم حقيقي."),
    action: L("Soak the area in comfortably hot water — hot enough to sting slightly, never scalding — for fifteen to twenty minutes, then wash, ice, and check tetanus cover.", "غطّس المكان بماي حار محتمل — حار يلسع شوي بس ما يحرق — من ربع لثلث ساعة، وبعدها اغسل وحط ثلج وتأكد إن تطعيم الكزاز عندك محدّث."),
  },
  {
    id: "rove-beetle",
    title: L("Rove Beetle Blisters", "بثور ذبابة نيروبي"),
    subtitle: "Paederus Rove Beetle (Nairobi Fly / Dermatitis Linearis)",
    severity: "warning",
    summary: L("Slim ant-like beetle with orange and black bands, drawn to lights at night in the Middle East, Africa, South and East Asia. It does not bite or sting — crushing it against the skin releases pederin, a chemical that burns. Twelve to thirty-six hours later you get a red streak of blisters in the exact shape of the swipe, and transferring it to an eyelid causes a painful eye reaction.", "خنفساء نحيلة تشبه النملة وعليها خطوط برتقالية وسودا، تنجذب للأضوية بالليل بالشرق الأوسط وأفريقيا وجنوب وشرق آسيا. هي ما تعض ولا تلسع — لكن إذا فقعتها على جلدك تطلع مادة اسمها بيديرين تحرق الجلد. وبعد 12 لـ 36 ساعة يطلع خط أحمر من البثور بنفس شكل مسحة يدك، وإذا وصلت للجفن تسبب التهاب مؤلم بالعين."),
    action: L("Blow or flick it off rather than crushing it, and if it was squashed on you, wash the skin with soap and plenty of water immediately and do not touch your eyes.", "انفخها أو طيّرها بإصبعك بدل ما تفقعها، وإذا انفقعت عليك اغسل الجلد فوراً بصابون وماي كثير ولا تحك عيونك."),
  },
  {
    id: "processionary-caterpillar",
    title: L("Processionary Caterpillar", "يرقة الصنوبر الزاحفة"),
    subtitle: "Pine Processionary Caterpillar (Thaumetopoea pityocampa)",
    severity: "warning",
    summary: L("Hairy brown caterpillars that march nose-to-tail in a long line under pine trees in late winter and spring — Mediterranean Europe, Turkey, North Africa and the Middle East. You do not need to touch them: their barbed hairs blow off the nest and cause an intense burning rash, swollen eyes, or throat and chest tightness. Dogs that nose the line can lose part of the tongue.", "يرقات بنية مشعرة تمشي بصف طويل ورا بعض تحت أشجار الصنوبر بآخر الشتا والربيع — بأوروبا المتوسطية وتركيا وشمال أفريقيا والشرق الأوسط. مو لازم تلمسها: شعيراتها الشوكية تطير من العش وتسبب طفح يحرق بشدة وانتفاخ بالعيون أو ضيق بالحلق والصدر. والكلاب اللي تشمّ الصف ممكن تخسر جزء من لسانها."),
    action: L("Do not rub — lift the hairs off with sticky tape, rinse the skin with plenty of water, wash clothing separately, and go to hospital for eye contact or any breathing difficulty.", "لا تفرك أبداً — شيل الشعيرات بشريط لاصق، اشطف الجلد بماي كثير، اغسل الملابس لحالها، وروح المستشفى إذا وصلت للعين أو صار ضيق نفس."),
  },
  {
    id: "yellow-sac-spider",
    title: L("Yellow Sac Spider", "عنكبوت الكيس الأصفر"),
    subtitle: "Yellow Sac Spider (Cheiracanthium spp.)",
    severity: "warning",
    summary: L("Small pale cream or yellow-green spider with dark jaw tips, common indoors worldwide; it spins a silk sleeping sac in ceiling corners and behind curtains and hunts at night, which is why bites happen in bed. The bite stings sharply and leaves a red itchy welt for a couple of days. It is widely blamed for flesh-eating wounds — that reputation is not supported by evidence.", "عنكبوت صغير لونه كريمي فاتح أو أصفر مخضر وأطراف فكوكه غامقة، منتشر داخل البيوت بكل العالم؛ يسوّي كيس حرير ينام فيه بزوايا السقف وورا الستاير ويصيد بالليل، وعشان كذا العضات تصير بالسرير. العضة تلسع بحدة وتخلي حبة حمرا تحكّ ليومين. وكثير ينلام إنه يسبب جروح تأكل اللحم — وهذي السمعة ما عليها دليل علمي."),
    action: L("Wash with soap, apply a cold pack and take an antihistamine; see a doctor only if it stays painful past two days or the redness spreads.", "اغسل بصابون، حط كمادة باردة وخذ مضاد حساسية؛ وراجع الطبيب بس إذا الألم استمر بعد يومين أو الاحمرار توسّع."),
  },
  {
    id: "white-tailed-spider",
    title: L("White-Tailed Spider", "العنكبوت أبو ذيل أبيض"),
    subtitle: "White-Tailed Spider (Lampona cylindrata, L. murina)",
    severity: "warning",
    summary: L("Slim dark grey Australian spider with a distinct white spot at the tip of the abdomen; it hunts other spiders indoors at night and is often found in towels and clothes left on the floor. The bite gives sharp pain and a red itchy mark for a day or two. Its reputation for causing rotting ulcers was studied in over a hundred confirmed bites and did not hold up.", "عنكبوت أسترالي نحيل لونه رمادي غامق وعند طرف بطنه نقطة بيضا واضحة؛ يصيد عناكب ثانية داخل البيت بالليل وكثير يلاقونه بالمناشف والملابس المرمية على الأرض. العضة توجع بحدة وتخلي علامة حمرا تحكّ ليوم أو يومين. وسمعته إنه يسبب تقرحات تأكل اللحم انفحصت بمئات العضات المؤكدة وما ثبتت."),
    action: L("Wash with soap and water, apply a cold pack for the pain, and see a doctor only if the area becomes hot, swollen and increasingly painful after two days.", "اغسل بماي وصابون، حط كمادة باردة للألم، وراجع الطبيب بس إذا المكان صار حار ومنتفخ والألم يزيد بعد يومين."),
  },
  {
    id: "tarantula-hairs",
    title: L("Tarantula Hairs and Bite", "شعيرات وعضة الرتيلاء"),
    subtitle: "Tarantula (Theraphosidae)",
    severity: "warning",
    summary: L("Large hairy spiders kept as pets and found wild in the Americas, southern Europe, Africa, Asia and Australia. American species flick barbed hairs off the abdomen when disturbed — these cause a stubborn itchy rash and are genuinely dangerous in the eye. Asian and African species have no such hairs but a far more painful bite with hours of muscle cramping.", "عناكب كبيرة مشعرة تنربّى بالبيوت وموجودة ببرية الأمريكتين وجنوب أوروبا وأفريقيا وآسيا وأستراليا. الأنواع الأمريكية تنفض شعيرات شوكية من بطنها لما تنزعج — وهذي تسبب طفح عنيد يحكّ وخطيرة فعلاً إذا دخلت العين. أما الأنواع الآسيوية والأفريقية فما عندها شعيرات بس عضتها أوجع بكثير وتسبب تشنج عضلي لساعات."),
    action: L("Lift hairs off the skin with sticky tape rather than rubbing, wash your hands before touching your face, and see an eye doctor urgently for any hair in the eye.", "شيل الشعيرات بشريط لاصق بدل ما تفرك، اغسل يدينك قبل ما تلمس وجهك، وروح لطبيب عيون بسرعة إذا دخلت شعيرة بالعين."),
  },
  {
    id: "body-lice",
    title: L("Body Lice", "قمل الجسم"),
    subtitle: "Body Louse (Pediculus humanus humanus)",
    severity: "warning",
    summary: L("Unlike head lice, these live in the seams of clothing and only move onto skin to feed, so you find eggs in the seams rather than on the body. Bites cluster on the shoulders, waist and back with a rash from constant scratching. They occur where clothes cannot be washed or changed, and they are the one louse that transmits serious disease such as typhus and trench fever.", "عكس قمل الراس، هذا يعيش بخياطات الملابس وما يطلع على الجلد إلا عشان يتغذى، فتلاقي البيض بالخياطات مو على الجسم. القرصات تتجمّع على الأكتاف والخصر والظهر مع طفح من كثر الحك. ينتشر بالأماكن اللي ما فيها إمكانية غسيل أو تبديل الملابس، وهو النوع الوحيد من القمل اللي ينقل أمراض خطيرة مثل التيفوس وحمى الخنادق."),
    action: L("Change into clean clothes and hot-wash or bag the old ones, bathe thoroughly, and see a doctor promptly for fever or a widespread rash.", "بدّل ملابس نظيفة واغسل القديمة بماي حار أو حطها بكيس مسكّر، استحم زين، وراجع الطبيب بسرعة إذا جتك حرارة أو طفح منتشر."),
  },
  {
    id: "bed-bug",
    title: L("Bed Bug", "بق الفراش"),
    subtitle: "Bed Bug (Cimex lectularius)",
    severity: "info",
    summary: L("Flat, apple-seed-sized reddish-brown insect hiding in mattress seams, headboards and bed frames, leaving dark ink-like specks on the sheets. Bites appear overnight in short lines of three or four on skin exposed while sleeping — arms, shoulders, neck. Itchy and upsetting, but bed bugs transmit no disease.", "حشرة مسطحة بحجم بذرة التفاح لونها بني محمر، تختبي بخياطات المرتبة وبظهر السرير وهيكله، وتترك نقاط غامقة مثل الحبر على الشراشف. القرصات تطلع بالليل بخط قصير ثلاث أو أربع على الجلد المكشوف وقت النوم — الذراعين والأكتاف والرقبة. تحكّ وتزعج نفسياً، بس بق الفراش ما ينقل أي مرض."),
    action: L("Wash the area, use an anti-itch cream, and hot-wash and tumble-dry all bedding — the bites clear on their own, the infestation needs professional treatment.", "اغسل المكان، استخدم كريم للحكة، واغسل كل الفرش بماي حار ونشّفه بالنشافة — القرصات تروح لحالها، بس الحشرة نفسها تحتاج مكافحة متخصصة."),
  },
  {
    id: "head-lice",
    title: L("Head Lice", "قمل الراس"),
    subtitle: "Head Louse (Pediculus humanus capitis)",
    severity: "info",
    summary: L("Sesame-seed-sized grey insects on the scalp, easiest to confirm by the eggs — pale ovals glued firmly to the hair shaft near the scalp that will not slide off like dandruff does. Common in school-age children, spread by head-to-head contact rather than dirt or hygiene, and they carry no disease at all.", "حشرات رمادية بحجم بذرة السمسم بفروة الراس، وأسهل طريقة تتأكد فيها هي البيض — بيضات بيضاوية فاتحة ملزوقة بقوة بالشعرة قريب من الفروة وما تنزلق مثل القشرة. شايع عند أطفال المدارس وينتقل بملامسة الراس للراس مو من الوسخ أو قلة النظافة، وما ينقل أي مرض."),
    action: L("Treat with a pharmacy lice product or wet-combing with conditioner, repeat after seven days to catch newly hatched eggs, and check everyone in the house.", "عالج بمنتج قمل من الصيدلية أو بتمشيط الشعر وهو مبلول بالبلسم، وأعد العلاج بعد سبعة أيام عشان تمسك البيض اللي فقس، وافحص كل أهل البيت."),
  },
  {
    id: "house-spider",
    title: L("House Spider", "عنكبوت البيت"),
    subtitle: "Common House / Hobo Spider (Tegenaria, Eratigena spp.)",
    severity: "info",
    summary: L("Fast brown long-legged spiders that build funnel-shaped sheet webs in corners, cellars and garages across Europe, North America and Asia; the males are the ones sprinting across the floor in autumn looking for mates. They very rarely bite and their fangs struggle with human skin. The hobo spider, once feared for causing necrosis, has been cleared by later research.", "عناكب بنية سريعة رجولها طويلة تبني شبكة على شكل قمع بالزوايا والسراديب والكراجات بأوروبا وأمريكا الشمالية وآسيا؛ والذكور هم اللي تشوفهم يركضون على الأرض بالخريف يدوّرون إناث. نادر جداً يعضون وأنيابهم بالكاد تخترق جلد الإنسان. وعنكبوت الهوبو اللي كانوا يخافون منه ويقولون يسبب تنخّر، الأبحاث اللاحقة برّأته."),
    action: L("Nothing needed for the spider itself; if it did bite, wash with soap and water and use a cold pack for an hour.", "ما يحتاج شي بالنسبة للعنكبوت نفسه؛ وإذا عض فعلاً، اغسل بماي وصابون وحط كمادة باردة لمدة ساعة."),
  },
  {
    id: "camel-spider",
    title: L("Camel Spider", "عنكبوت الجمل"),
    subtitle: "Camel Spider / Solifuge (Solifugae)",
    severity: "info",
    summary: L("Tan, fast, ten-legged-looking desert arachnid with enormous jaws, found across the Middle East, North Africa and dry Asia. It is not venomous — it has no venom glands at all — it does not chase people, it runs toward your shadow for shade, and it does not eat camel stomachs. A bite from a big one can tear the skin because the jaws are powerful.", "عنكبوت صحراوي لونه بيج وسريع ويبين وكأن له عشر أرجل وفكوكه ضخمة، موجود بالشرق الأوسط وشمال أفريقيا وآسيا الجافة. هو مو سام أصلاً — ما عنده غدد سم — وما يطارد الناس، بس يركض ناحية ظلّك عشان يستظل، وما ياكل معدة الجمال. عضته إذا كان كبير ممكن تجرح الجلد لأن فكوكه قوية."),
    action: L("If bitten, wash the wound well with soap and water, cover it, and check your tetanus is up to date — there is no venom to treat.", "إذا عضّك، اغسل الجرح زين بماي وصابون، غطّه، وتأكد إن تطعيم الكزاز محدّث — ما في سم يحتاج علاج."),
  },
  {
    id: "huntsman-spider",
    title: L("Huntsman Spider", "العنكبوت الصياد"),
    subtitle: "Huntsman Spider (Sparassidae, Heteropoda spp.)",
    severity: "info",
    summary: L("Very large flat spider with legs held crab-like out to the sides, moving sideways at speed on walls and ceilings; common in Australia, Asia, the Middle East and southern Europe, and famous for appearing behind car sun visors. Alarming rather than dangerous — it eats cockroaches, does not build webs indoors, and bites only if pinned against skin.", "عنكبوت كبير ومسطح ورجوله ممدودة على الجنبين مثل السرطان، ويتحرك بالعرض بسرعة على الجدران والسقوف؛ شايع بأستراليا وآسيا والشرق الأوسط وجنوب أوروبا، ومشهور إنه يطلع من ورا حاجب الشمس بالسيارة. مخوّف بس مو خطير — ياكل الصراصير، وما يبني شبكة داخل البيت، وما يعض إلا إذا انضغط على الجلد."),
    action: L("Guide it out with a jar and card rather than swatting; a bite needs only soap, water and a cold pack.", "طلّعه برّا بكاسة وورقة بدل ما تضربه؛ وإذا عض، بس ماي وصابون وكمادة باردة تكفي."),
  },
  {
    id: "wolf-spider",
    title: L("Wolf Spider", "عنكبوت الذئب"),
    subtitle: "Wolf Spider (Lycosidae)",
    severity: "info",
    summary: L("Stocky brown ground spider with a striped back and two large forward eyes that shine back at a torch; the female carries a round egg sac on her spinnerets and later a crowd of babies on her back. Found worldwide in gardens and entering houses in autumn. It hunts rather than webbing, and the bite is a brief sting with mild swelling.", "عنكبوت أرضي ممتلئ لونه بني وظهره مخطط وعنده عينين كبيرتين لقدام يلمعون إذا سلّطت عليهم كشاف؛ والأنثى تشيل كيس بيض مدوّر بمؤخرتها وبعدين تشيل صغارها على ظهرها. موجود بكل العالم بالحدايق ويدخل البيوت بالخريف. يصيد وما يبني شبكة، وعضته وخزة بسيطة مع ورم خفيف."),
    action: L("Wash with soap and water and use a cold pack for twenty minutes; no further treatment is needed.", "اغسل بماي وصابون وحط كمادة باردة عشرين دقيقة؛ ما يحتاج أي علاج ثاني."),
  },
];
