import { L } from "../i18n";
import type { LibraryEntry } from "./types";

/**
 * The 48 warning lights drivers actually see, across petrol, diesel, hybrid
 * and EV cars worldwide. Browsable without spending a scan, and it works
 * offline — a scanner with one screen feels like a demo.
 */
export const DASHLIGHT_LIBRARY: LibraryEntry[] = [
  {
    id: "check-engine-flashing",
    glyph: "engine",
    title: L("Check Engine — Flashing", "مصباح المحرك يومض"),
    subtitle: "Check Engine Light (Flashing)",
    severity: "critical",
    summary: L("A flashing check engine light means the engine is misfiring right now and pushing unburned fuel into the exhaust. That can melt the catalytic converter within minutes, adding a very expensive repair on top of whatever caused it.", "وميض مصباح المحرك يعني وجود خلل في الإشعال في هذه اللحظة، فيصل الوقود إلى العادم دون أن يحترق. وقد يؤدي ذلك إلى إتلاف المحوّل الحفّاز خلال دقائق، فترتفع كلفة الإصلاح كثيراً."),
    action: L("Ease off the accelerator, drive gently to the nearest safe spot, switch off, and call for help — don't keep driving on it.", "خفّف الضغط على دوّاسة الوقود، وتوجّه بهدوء إلى أقرب مكان آمن، ثم أطفئ المحرك واتصل بالميكانيكي — ولا تتابع القيادة."),
  },
  {
    id: "check-engine-steady",
    glyph: "engine",
    title: L("Check Engine — Steady", "مصباح المحرك ثابت"),
    subtitle: "Check Engine Light (Steady)",
    severity: "warning",
    summary: L("A steady amber light means the car has stored a fault code — anything from a loose fuel cap to a failing oxygen sensor. The car usually drives normally, but fuel economy and emissions suffer until it's read and fixed.", "المصباح الثابت يعني أن السيارة سجّلت عطلاً في الحاسوب — من غطاء خزان الوقود غير المُحكم إلى حسّاس أكسجين تالف. وغالباً تسير السيارة بصورة طبيعية، لكن استهلاك الوقود والانبعاثات يسوءان حتى يُصلَح العطل."),
    action: L("Check the fuel cap is clicked tight, then have the codes read within the next few days.", "تأكد من إحكام غطاء خزان الوقود، ثم اقرأ رموز الأعطال لدى الميكانيكي خلال أيام قليلة."),
  },
  {
    id: "oil-pressure",
    glyph: "oil-can",
    title: L("Oil Pressure", "ضغط زيت المحرك"),
    subtitle: "Engine Oil Pressure",
    severity: "critical",
    summary: L("The oil pump is no longer holding pressure, so metal parts inside the engine are turning with little or no lubrication. An engine can destroy itself in under a minute in this state.", "لم يعد ضغط الزيت كافياً، وأجزاء المحرك المعدنية تدور دون تزييت. وقد يتلف المحرك بالكامل في أقل من دقيقة في هذه الحالة."),
    action: L("Pull over safely and switch the engine off immediately — do not restart it to \"just get home\".", "توقّف جانباً فوراً وأطفئ المحرك — ولا تعِد تشغيله للوصول إلى المنزل."),
  },
  {
    id: "coolant-temp-high",
    glyph: "thermometer",
    title: L("Engine Temperature — High", "حرارة المحرك مرتفعة"),
    subtitle: "Engine Coolant Temperature (Red)",
    severity: "critical",
    summary: L("The engine is running hotter than its design limit, usually from lost coolant, a stuck thermostat or a dead cooling fan. Carrying on warps the cylinder head and blows the head gasket.", "تجاوزت حرارة المحرك الحد المسموح، غالباً بسبب نقص سائل التبريد أو عطل في الثرموستات أو المروحة. ومتابعة القيادة قد تؤدي إلى التواء رأس المحرك وتلف الحشية."),
    action: L("Pull over, switch off, and let it cool for at least 30 minutes — never open a hot radiator cap.", "توقّف وأطفئ المحرك واتركه يبرد نصف ساعة على الأقل — ولا تفتح غطاء الرادياتير وهو ساخن."),
  },
  {
    id: "brake-warning-red",
    glyph: "brake",
    title: L("Brake System", "نظام الفرامل"),
    subtitle: "Brake System Warning",
    severity: "critical",
    summary: L("Either the parking brake is still applied, the brake fluid is low, or the hydraulic system has a fault. Low fluid almost always means a leak or badly worn pads, and pedal travel can get long with no warning.", "إمّا أن فرامل الانتظار مرفوعة، أو أن زيت الفرامل ناقص، أو أن هناك عطلاً في النظام الهيدروليكي. ونقص الزيت يعني غالباً تسرّباً أو تآكل تيل الفرامل، وقد تصبح الدوّاسة طويلة فجأة."),
    action: L("Release the handbrake first; if the light stays on, stop as soon as it's safe and have the car towed, not driven.", "أنزل فرامل الانتظار أولاً؛ فإن بقي المصباح مضاءً، فتوقّف بأمان واطلب شاحنة سحب بدلاً من قيادتها."),
  },
  {
    id: "master-warning-red",
    glyph: "warning-triangle",
    title: L("Master Warning", "تحذير عام (مثلث أحمر)"),
    subtitle: "Master Warning (Red Triangle)",
    severity: "critical",
    summary: L("The red triangle is a catch-all: another system has raised a serious fault and the details are written on the driver's display. Red always means the car wants you to stop now, not to book an appointment.", "المثلث الأحمر تحذير عام: نظام آخر سجّل عطلاً خطيراً، وتفاصيله معروضة على شاشة العدّادات. واللون الأحمر يعني دائماً التوقف الآن، لا تأجيل الأمر إلى الغد."),
    action: L("Read the message on the dash, then pull over safely and act on exactly what it says.", "اقرأ الرسالة المعروضة على الشاشة، ثم توقّف بأمان وتصرّف وفق ما ورد فيها."),
  },
  {
    id: "transmission-overheat",
    glyph: "thermometer",
    title: L("Transmission Overheating", "ارتفاع حرارة ناقل الحركة"),
    subtitle: "Transmission Temperature / Fault",
    severity: "critical",
    summary: L("Gearbox fluid is above its safe temperature, usually after towing, a long climb or stop-start traffic in the heat. Overheated fluid burns and eats the clutch packs inside the transmission.", "تجاوزت حرارة زيت ناقل الحركة الحد الآمن، غالباً بعد سحب مقطورة أو صعود طويل أو ازدحام مروري في جو حار. واحتراق الزيت يُتلف القوابض داخل ناقل الحركة."),
    action: L("Stop somewhere safe, leave the engine idling in Park for a few minutes to cool it, then avoid loads until it's checked.", "توقّف في مكان آمن، وأبقِ المحرك يعمل على الوضع P دقائق حتى يبرد، وتجنّب الأحمال حتى الفحص."),
  },
  {
    id: "ev-hv-fault",
    glyph: "ev-fault",
    title: L("High-Voltage System Fault", "عطل في نظام الجهد العالي"),
    subtitle: "High-Voltage System Fault (EV/Hybrid)",
    severity: "critical",
    summary: L("The car has found a fault in the high-voltage battery or drive system and may cut power without warning. High-voltage components are never a roadside DIY job.", "اكتشفت السيارة عطلاً في بطارية الجهد العالي أو في نظام الدفع، وقد تنقطع القدرة فجأة. وأجزاء الجهد العالي لا تُصلَح على جانب الطريق إطلاقاً."),
    action: L("Pull over away from traffic, shut the car down, and call EV assistance — don't open the bonnet or touch orange cables.", "توقّف بعيداً عن حركة السير، وأطفئ السيارة، واتصل بمساعدة الوكالة للسيارات الكهربائية — ولا تفتح غطاء المحرك ولا تلمس الكابلات البرتقالية."),
  },
  {
    id: "catalytic-overheat",
    glyph: "catalytic",
    title: L("Catalyst Overheat", "ارتفاع حرارة المحوّل الحفّاز"),
    subtitle: "Catalytic Converter Overheat",
    severity: "critical",
    summary: L("The exhaust catalyst is running far above normal temperature, usually because unburned fuel from a misfire is reaching it. It can glow hot enough to set dry grass under the car alight.", "ارتفعت حرارة المحوّل الحفّاز فوق المعدل الطبيعي بكثير، غالباً لوصول وقود غير محترق إليه بسبب خلل في الإشعال. وقد تبلغ حرارته حداً يُشعل العشب الجاف تحت السيارة."),
    action: L("Stop on tarmac rather than grass, switch off, and have it recovered instead of driven.", "توقّف على الأسفلت لا على العشب، وأطفئ السيارة، واطلب شاحنة سحب بدلاً من قيادتها."),
  },
  {
    id: "abs",
    glyph: "abs",
    title: L("Anti-lock Brakes", "نظام منع انغلاق الفرامل"),
    subtitle: "Anti-lock Braking System (ABS)",
    severity: "warning",
    summary: L("Normal braking still works, but the anti-lock system is offline, so the wheels can lock and skid in an emergency stop. Stopping distances on wet roads get noticeably longer.", "الفرامل الاعتيادية تعمل، لكن نظام ABS معطّل، أي أن الإطارات قد تنغلق وتنزلق عند الفرملة المفاجئة. وتطول مسافة التوقف على الطرق المبتلة."),
    action: L("Drive gently, leave extra following distance, and book a brake diagnostic this week.", "قُد بهدوء، واترك مسافة أكبر عن السيارة التي أمامك، واحجز فحصاً للفرامل هذا الأسبوع."),
  },
  {
    id: "charging-system",
    glyph: "battery",
    title: L("Charging System", "نظام الشحن"),
    subtitle: "Battery / Charging System",
    severity: "warning",
    summary: L("The alternator has stopped charging and the car is running on the battery alone — typically 20 to 40 minutes before everything shuts down. It rarely means the battery itself is the faulty part.", "توقّف المولّد عن الشحن، وتعمل السيارة على البطارية وحدها — عادة من 20 إلى 40 دقيقة ثم تتوقف. ونادراً ما تكون البطارية نفسها هي التالفة."),
    action: L("Switch off the AC, screen and heated seats and drive straight to a garage without stopping the engine.", "أطفئ المكيّف والشاشة وكل ما هو غير ضروري، وتوجّه مباشرة إلى مركز الصيانة دون إطفاء المحرك."),
  },
  {
    id: "airbag-srs",
    glyph: "airbag",
    title: L("Airbag System", "نظام الوسائد الهوائية"),
    subtitle: "Airbag / SRS",
    severity: "warning",
    summary: L("The restraint system has a fault, which usually means the airbags and belt pretensioners will not fire in a crash. A few faults can also cause an airbag to deploy when it shouldn't.", "هناك عطل في نظام الأمان، ويعني ذلك غالباً أن الوسائد الهوائية وشدّادات الأحزمة لن تعمل عند وقوع حادث. وفي حالات قليلة يؤدي العطل نفسه إلى انفتاح الوسادة دون سبب."),
    action: L("Keep driving carefully but book it in, and don't let anyone poke at the wiring under the seats.", "تابع القيادة بحذر واحجز موعداً في مركز الصيانة، ولا تدع أحداً يعبث بالأسلاك تحت المقاعد."),
  },
  {
    id: "tpms",
    glyph: "tyre",
    title: L("Tyre Pressure", "ضغط الإطارات"),
    subtitle: "Tyre Pressure Monitoring (TPMS)",
    severity: "warning",
    summary: L("At least one tyre is roughly 25% below its correct pressure, or the monitoring system itself has failed. Under-inflated tyres overheat, wear at the shoulders and can fail at speed.", "ضغط إطار واحد على الأقل أقل من المطلوب بنحو 25٪، أو أن النظام نفسه معطّل. والإطار ناقص الهواء يسخن ويتآكل من أطرافه وقد ينفجر عند السرعة."),
    action: L("Check all four pressures cold against the sticker in the driver's door frame and inflate to spec.", "قِس ضغط الإطارات الأربعة وهي باردة وفق الملصق الموجود على إطار باب السائق، واضبطها على القيمة المدوّنة."),
  },
  {
    id: "brake-pad-wear",
    glyph: "pad-wear",
    title: L("Brake Pads Worn", "تآكل تيل الفرامل"),
    subtitle: "Brake Pad Wear",
    severity: "warning",
    summary: L("A sensor in the pad has reached the wear line, leaving only a few millimetres of friction material. Ignore it and the backing plate scores the disc, turning a cheap job into an expensive one.", "بلغ الحسّاس الموجود في تيل الفرامل حدّ التآكل، ولم يتبقَّ سوى ملّيمترات. وإهمال ذلك يجعل المعدن يحتكّ بالقرص فترتفع كلفة الإصلاح كثيراً."),
    action: L("Book a pad replacement in the next week or two — sooner if you hear metal grinding.", "غيّر تيل الفرامل خلال أسبوع أو أسبوعين، وعجّل بذلك إن سمعت صوت احتكاك معدني."),
  },
  {
    id: "power-steering-fault",
    glyph: "steering",
    title: L("Power Steering Fault", "عطل في نظام تعزيز المقود"),
    subtitle: "Electric Power Steering (EPS)",
    severity: "warning",
    summary: L("Steering assistance has been reduced or lost, so the wheel goes very heavy, especially when parking or at low speed. The steering still works mechanically — it just takes far more effort.", "ضعف تعزيز المقود أو توقف، فيصبح المقود ثقيلاً جداً، خصوصاً عند الركن والسرعات المنخفضة. ولا يزال المقود يعمل ميكانيكياً لكنه يتطلب جهداً أكبر."),
    action: L("Slow down, keep both hands on the wheel, and drive straight to a garage — avoid tight car parks.", "خفّف السرعة، وأبقِ كلتا يديك على المقود، وتوجّه مباشرة إلى مركز الصيانة — وتجنّب المواقف الضيقة."),
  },
  {
    id: "esc-fault",
    glyph: "skid-car",
    title: L("Stability Control Fault", "عطل في نظام الثبات"),
    subtitle: "Stability Control Fault (ESC/ESP/VSC)",
    severity: "warning",
    summary: L("Electronic stability control has shut itself down because of a fault, so the car will no longer catch a skid for you. On wet, sandy or icy roads that safety net is gone.", "أوقف نظام الثبات نفسه بسبب عطل، أي أن السيارة لن تصحّح الانزلاق عنك. وعلى الطرق المبتلة أو الرملية أو المتجمدة، لم تعد شبكة الأمان هذه موجودة."),
    action: L("Reduce speed, avoid sudden steering, and have it scanned soon — it's often just a wheel speed sensor.", "خفّف السرعة وتجنّب المناورات المفاجئة، وافحص السيارة قريباً — والسبب غالباً حسّاس سرعة أحد الإطارات."),
  },
  {
    id: "esc-off",
    glyph: "esc-off",
    title: L("Stability Control Off", "نظام الثبات متوقف"),
    subtitle: "Stability Control Off",
    severity: "warning",
    summary: L("Stability and traction control are switched off, either by the button or automatically in a sport or off-road mode. Wheelspin and slides are no longer corrected for you.", "نظام الثبات والجر متوقف، إمّا بالزر وإمّا تلقائياً في الوضع الرياضي أو وضع الطرق الوعرة. أي أن فقدان الجر والانزلاق لن يُعالجا تلقائياً."),
    action: L("Press the ESC button once to switch it back on unless you're deliberately freeing a stuck car.", "اضغط زر ESC مرة واحدة ليعود إلى العمل، إلا إن كنت تقصد إخراج السيارة من رمل أو طين."),
  },
  {
    id: "dpf",
    glyph: "dpf",
    title: L("Diesel Particulate Filter", "فلتر جزيئات الديزل"),
    subtitle: "Diesel Particulate Filter (DPF)",
    severity: "warning",
    summary: L("The soot filter in the exhaust is full because the car has done too many short, cold trips to burn it clear. Left alone it blocks solid and needs forced cleaning or replacement.", "امتلأ فلتر السخام في العادم لأن السيارة تسير مسافات قصيرة وباردة لا تكفي لحرقه. وإهماله يؤدي إلى انسداده كلياً فيحتاج إلى تنظيف إجباري أو تغيير."),
    action: L("Drive 15–20 minutes at a steady main-road speed in a lower gear to let it regenerate.", "قُد من 15 إلى 20 دقيقة بسرعة ثابتة على طريق سريع وبغيار أدنى قليلاً حتى يحترق السخام."),
  },
  {
    id: "adblue",
    glyph: "droplet",
    title: L("AdBlue Low", "انخفاض سائل AdBlue"),
    subtitle: "AdBlue / DEF Level",
    severity: "warning",
    summary: L("The exhaust fluid that cleans diesel emissions is running low, and the display usually counts down the range you have left. When it hits zero, emissions law requires the car to refuse to restart.", "أوشك سائل AdBlue الذي ينقّي عوادم الديزل على النفاد، وتعرض الشاشة عادة المسافة المتبقية. وعند نفاده تمنع السيارة نفسها من التشغيل وفق أنظمة الانبعاثات."),
    action: L("Top up with AdBlue from any fuel station or parts shop before the countdown runs out.", "املأ سائل AdBlue من أي محطة أو متجر قطع غيار قبل انتهاء العدّاد."),
  },
  {
    id: "water-in-fuel",
    glyph: "water-in-fuel",
    title: L("Water in Fuel", "ماء في وقود الديزل"),
    subtitle: "Water in Fuel (Diesel)",
    severity: "warning",
    summary: L("Water has collected in the diesel filter's separator, usually from condensation or poor-quality fuel. If it reaches the injection pump it wrecks it — one of the most expensive repairs on a diesel.", "تجمّع الماء في فلتر الديزل، غالباً بفعل التكثّف أو وقود غير نظيف. ووصول الماء إلى مضخة البخّاخات يُتلفها، وهو من أغلى الإصلاحات في محركات الديزل."),
    action: L("Stop soon and drain the filter's water trap, or have a garage do it the same day.", "توقّف قريباً وصرّف الماء من الفلتر، أو اطلب من مركز الصيانة القيام بذلك في اليوم نفسه."),
  },
  {
    id: "oil-level-low",
    glyph: "oil-can",
    title: L("Oil Level Low", "مستوى الزيت منخفض"),
    subtitle: "Engine Oil Level Low",
    severity: "warning",
    summary: L("The sensor in the sump reads below minimum — this is about how much oil is in there, not oil pressure, so it's a warning rather than an emergency. Running low still raises wear and oil temperature.", "يقرأ الحسّاس في حوض الزيت أقل من الحد الأدنى — والحديث هنا عن كمية الزيت لا عن ضغطه، فليست حالة طارئة. لكن النقص يزيد التآكل وحرارة الزيت."),
    action: L("Check the dipstick cold on level ground and top up with the grade in the owner's manual.", "افحص مقياس الزيت والسيارة باردة وعلى أرض مستوية، وأضف النوع نفسه المدوَّن في دليل المالك."),
  },
  {
    id: "coolant-level-low",
    glyph: "coolant",
    title: L("Coolant Low", "انخفاض سائل التبريد"),
    subtitle: "Coolant Level Low",
    severity: "warning",
    summary: L("The expansion tank has dropped below minimum, which usually points to a slow leak from a hose, the radiator or the cap. Coolant isn't consumed — if it's low, it went somewhere.", "انخفض خزان التبريد دون الحد الأدنى، وغالباً هناك تسرّب بسيط من خرطوم أو من الرادياتير أو من الغطاء نفسه. وسائل التبريد لا يُستهلك — فنقصه يعني خروجه من مكان ما."),
    action: L("Top up with the correct coolant while the engine is cold, then have the leak traced.", "أضف سائل التبريد المناسب والمحرك بارد، ثم ابحث عن مصدر التسرّب في مركز الصيانة."),
  },
  {
    id: "bulb-failure",
    glyph: "bulb",
    title: L("Bulb Out", "مصباح خارجي محترق"),
    subtitle: "Exterior Light Failure",
    severity: "warning",
    summary: L("One of the exterior bulbs — brake, indicator, tail or headlight — has failed or is drawing the wrong current. A dead brake light is a common cause of both rear-end collisions and fines.", "أحد المصابيح الخارجية — الفرامل أو الإشارة أو الخلفي أو الأمامي — محترق أو أن استهلاكه للتيار غير صحيح. ومصباح الفرامل المطفأ من أكثر أسباب الاصطدام من الخلف والمخالفات."),
    action: L("Have someone stand behind the car while you test brakes and indicators, then replace the dead bulb.", "اطلب من أحدهم الوقوف خلف السيارة وجرّب الفرامل والإشارات، ثم بدّل المصباح المحترق."),
  },
  {
    id: "epb-fault",
    glyph: "epb",
    title: L("Parking Brake Fault", "عطل في فرامل الانتظار الكهربائية"),
    subtitle: "Electronic Parking Brake Fault",
    severity: "warning",
    summary: L("The electric parking brake has a fault and may not hold the car, or may not release fully. A partly stuck brake overheats the rear pads and can burn them out in one drive.", "هناك عطل في فرامل الانتظار الكهربائية، وقد لا تمسك السيارة أو لا تتحرر بالكامل. والفرملة التي لا تتحرر تُسخّن تيل الفرامل الخلفي وتحرقه في رحلة واحدة."),
    action: L("Park in gear or in P on level ground, chock a wheel on a slope, and get it fixed before it strands you.", "توقّف وضع الغيار أو الوضع P على أرض مستوية، وضع حجراً تحت الإطار إن كنت على منحدر، وأصلحها قبل أن تتعطل بك."),
  },
  {
    id: "immobiliser",
    glyph: "key",
    title: L("Immobiliser", "نظام منع التشغيل (الإيموبيلايزر)"),
    subtitle: "Immobiliser / Security",
    severity: "warning",
    summary: L("The security system isn't recognising the key's transponder, so the engine is blocked from starting or will cut out. A slowly flashing car-and-key symbol with the car parked is normal; lit while driving is not.", "لا يتعرّف نظام منع التشغيل على شريحة المفتاح، فيمنع التشغيل أو يطفئ المحرك. ووميض رمز السيارة والمفتاح والسيارة مطفأة أمر طبيعي، أما ظهوره في أثناء القيادة فليس كذلك."),
    action: L("Try the spare key — if that starts the car, the first key or its battery is the problem.", "جرّب المفتاح الاحتياطي؛ فإن عملت السيارة، فالمشكلة في المفتاح الأول أو في بطاريته."),
  },
  {
    id: "key-not-detected",
    glyph: "key",
    title: L("Key Not Detected", "المفتاح غير موجود"),
    subtitle: "Key Not Detected",
    severity: "warning",
    summary: L("The car can't find the smart key inside the cabin — usually a flat fob battery, or the key sitting in a bag against metal. If you switch the engine off now, it may not restart.", "لا تجد السيارة المفتاح الذكي في داخلها، وغالباً بطارية المفتاح فارغة أو أن المفتاح في حقيبة ملاصق لمعدن. وإن أطفأت المحرك الآن فقد لا يعمل من جديد."),
    action: L("Don't switch off until you're somewhere you can get help; to start, hold the fob against the marked spot by the start button.", "لا تطفئ المحرك حتى تصل إلى مكان تجد فيه مساعدة، وللتشغيل ضع المفتاح في الموضع المخصص بجوار زر التشغيل."),
  },
  {
    id: "aeb-fault",
    glyph: "radar-car",
    title: L("Collision Assist Fault", "عطل في نظام منع التصادم"),
    subtitle: "Forward Collision / AEB Fault",
    severity: "warning",
    summary: L("The forward-facing radar or camera is blocked or faulty, so automatic emergency braking and collision alerts are switched off. Very often it's just dirt, ice or a stone chip in front of the sensor.", "الرادار أو الكاميرا الأمامية مغطّاة أو بها عطل، فنظام الفرملة التلقائية والتنبيه معطّل. وكثيراً ما يكون السبب مجرد اتساخ أو ثلج أو شرخ بسيط في الزجاج أمام الحسّاس."),
    action: L("Clean the windscreen in front of the mirror and around the grille badge, restart, and book a scan if it stays on.", "نظّف الزجاج أمام المرآة وحول شعار الشبك الأمامي وأعد التشغيل، فإن بقي المصباح مضاءً فافحصها في مركز الصيانة."),
  },
  {
    id: "air-suspension-fault",
    glyph: "suspension",
    title: L("Air Suspension Fault", "عطل في التعليق الهوائي"),
    subtitle: "Air Suspension Fault",
    severity: "warning",
    summary: L("The air suspension can't hold its set ride height, usually from a leaking air spring or a tired compressor. The car may sag overnight or drop onto its bump stops while driving.", "لم يعد نظام التعليق الهوائي يحافظ على ارتفاع السيارة، وغالباً بسبب تسرّب في مساعد هوائي أو ضعف في الضاغط. وقد تجد السيارة منخفضة صباحاً أو تهبط في أثناء القيادة."),
    action: L("Avoid speed bumps and rough roads, keep the speed down, and get it inspected before it drops completely.", "تجنّب المطبّات والطرق الوعرة، وخفّف السرعة، وافحصها قبل أن تهبط كلياً."),
  },
  {
    id: "ev-low-charge",
    glyph: "ev-battery",
    title: L("Battery Charge Low", "شحن البطارية منخفض"),
    subtitle: "Low State of Charge (EV)",
    severity: "warning",
    summary: L("The traction battery is near the bottom of its usable range, and remaining range drops faster than the number suggests on motorways or in cold weather. Running it to zero usually means a flatbed, not a jump start.", "أوشكت بطارية السيارة على النفاد، والمدى المتبقي ينخفض أسرع من الرقم المعروض على الشاشة، خصوصاً على الطريق السريع أو في البرد. وإن نفدت كلياً فستحتاج إلى شاحنة سحب لا إلى كابل شحن."),
    action: L("Set the nearest working charger as your destination now and settle into a slower, steadier speed.", "اجعل أقرب شاحن عامل وجهتك على الخريطة الآن، وخفّف سرعتك وحافظ على ثباتها."),
  },
  {
    id: "reduced-power-turtle",
    glyph: "turtle",
    title: L("Reduced Power", "قدرة محدودة (رمز السلحفاة)"),
    subtitle: "Reduced Power (Turtle)",
    severity: "warning",
    summary: L("The car has limited its own power to protect the battery or motor — from very low charge, high temperature, or a logged fault. Acceleration becomes weak, which is genuinely risky when joining fast roads.", "حدّت السيارة قدرتها لحماية البطارية أو المحرك — بسبب شحن منخفض جداً أو حرارة مرتفعة أو عطل مسجّل. ويصبح التسارع ضعيفاً، وهو أمر خطر عند الدخول إلى طريق سريع."),
    action: L("Move to the slow lane, don't attempt overtakes, and head for the nearest charger or garage.", "انتقل إلى المسار البطيء، ولا تحاول تجاوز أحد، وتوجّه إلى أقرب شاحن أو مركز صيانة."),
  },
  {
    id: "regen-brake-fault",
    glyph: "regen",
    title: L("Regen Braking Fault", "عطل في الفرملة الاسترجاعية"),
    subtitle: "Regenerative Braking Fault",
    severity: "warning",
    summary: L("Energy recovery under braking has been reduced or disabled — often because the battery is full or very cold, sometimes because a fault was logged. The pedal feels different and the usual one-pedal slowdown disappears.", "ضعف استرجاع الطاقة عند الفرملة أو توقف، غالباً لأن البطارية ممتلئة أو شديدة البرودة، وأحياناً بسبب عطل مسجّل. ويتغير إحساس دوّاسة الفرامل، ويُفقد التباطؤ المعتاد عند رفع القدم."),
    action: L("Brake earlier and expect the car to coast further; if it doesn't clear as the battery warms or discharges, get it scanned.", "افرمل مبكراً وتوقّع أن تقطع السيارة مسافة أطول قبل التوقف، فإن لم ينطفئ المصباح بعد أن تدفأ البطارية أو ينقص شحنها فافحصها."),
  },
  {
    id: "hybrid-system-warning",
    glyph: "hybrid",
    title: L("Hybrid System", "تحذير النظام الهجين"),
    subtitle: "Hybrid System Warning",
    severity: "warning",
    summary: L("The hybrid controller has logged a fault in the electric drive, battery cooling or the engine-to-motor handover. The car usually still moves, but power and economy drop and it can go into limp mode.", "سجّل حاسوب النظام الهجين عطلاً في الدفع الكهربائي أو تبريد البطارية أو التبديل بين محرك الاحتراق والمحرك الكهربائي. وغالباً تسير السيارة، لكن القدرة واستهلاك الوقود يتأثران وقد تدخل في وضع الطوارئ."),
    action: L("Keep speeds moderate and book a hybrid-trained workshop within a day or two.", "خفّف السرعة وحافظ على اعتدالها، واحجز موعداً في مركز صيانة متخصص بالسيارات الهجينة خلال يوم أو يومين."),
  },
  {
    id: "ev-12v-battery",
    glyph: "battery",
    title: L("12V Battery", "بطارية 12 فولت"),
    subtitle: "12V Battery (EV/Hybrid)",
    severity: "warning",
    summary: L("The small 12-volt battery that wakes the car and runs its computers is weak, even with the main traction battery full. A flat 12V is the single most common reason an EV won't switch on at all.", "ضعفت بطارية الـ 12 فولت الصغيرة التي تشغّل حواسيب السيارة، حتى لو كانت البطارية الكبيرة ممتلئة. وهذه البطارية هي أكثر أسباب توقف السيارة الكهربائية عن العمل تماماً."),
    action: L("Keep the car plugged in or driven daily until you can have the 12V battery tested and replaced.", "أبقِ السيارة موصولة بالشاحن أو قُدها يومياً حتى تفحص بطارية الـ 12 فولت وتبدّلها."),
  },
  {
    id: "master-caution-amber",
    glyph: "warning-triangle",
    title: L("Master Caution", "تنبيه عام أصفر"),
    subtitle: "Master Caution (Amber)",
    severity: "warning",
    summary: L("The amber general warning points you to a message on the driver's display; the symbol on its own tells you nothing. Amber means attention needed soon, not an emergency stop.", "يوجّهك التنبيه الأصفر العام إلى رسالة على شاشة العدّادات، والرمز وحده لا يدل على شيء. واللون الأصفر يعني الانتباه قريباً، لا حالة طارئة."),
    action: L("Read the dash message and deal with whichever system it names.", "اقرأ الرسالة المعروضة على الشاشة وعالج النظام الذي ذكرته."),
  },
  {
    id: "glow-plug",
    glyph: "glow-plug",
    title: L("Glow Plug Preheat", "تسخين شمعات الإشعال (ديزل)"),
    subtitle: "Glow Plug / Preheat (Diesel)",
    severity: "info",
    summary: L("The coil symbol shows the diesel's glow plugs are warming the cylinders before starting, and it should go out after a second or two. If it stays lit or flashes while driving, it has become an engine fault warning instead.", "يعني رمز الملف أن شمعات التسخين تُدفئ المحرك قبل التشغيل، ويجب أن ينطفئ بعد ثانية أو ثانيتين. أما بقاؤه مضاءً أو وميضه في أثناء القيادة فيصبح تحذيراً من عطل في المحرك."),
    action: L("Wait for the light to go out before cranking the engine.", "انتظر حتى ينطفئ المصباح ثم شغّل المحرك."),
  },
  {
    id: "ev-ready",
    glyph: "ev-ready",
    title: L("Ready", "جاهزة للسير"),
    subtitle: "Ready to Drive (EV/Hybrid)",
    severity: "info",
    summary: L("The car is powered up and will move the moment you select a gear, even though there's no engine noise. This is the EV and hybrid equivalent of an engine idling.", "السيارة جاهزة وتتحرك بمجرد وضع الغيار، حتى دون صوت محرك. وهذا ما يقابل صوت المحرك العامل في السيارات الاعتيادية."),
    action: L("Keep your foot on the brake until you've selected D or R — it can creep the moment you lift off.", "أبقِ قدمك على الفرامل حتى تختار D أو R — فهي تتحرك من تلقاء نفسها بمجرد رفع قدمك."),
  },
  {
    id: "charging-cable-connected",
    glyph: "plug",
    title: L("Plugged In", "الشاحن موصول"),
    subtitle: "Charging Cable Connected",
    severity: "info",
    summary: L("The charge cable is locked into the car and on most models drive is blocked while it's attached. A change of colour or pulse is what tells you charging has actually started.", "كابل الشحن مثبّت بالسيارة، وفي معظم الطُرز لا تتحرك السيارة وهو موصول. وتغيّر اللون أو النبض هو ما يدل على أن الشحن بدأ فعلاً."),
    action: L("Confirm the light shows charging, not just connected, before you walk away.", "تأكد من أن المصباح يشير إلى الشحن لا إلى التوصيل فقط قبل أن تنصرف."),
  },
  {
    id: "esc-active-flashing",
    glyph: "skid-car",
    title: L("Stability Control Working", "نظام الثبات يعمل"),
    subtitle: "Stability Control Active (Flashing)",
    severity: "info",
    summary: L("A briefly flashing stability symbol means the system is actively cutting power or braking one wheel to keep you on line. Nothing is broken — the car is telling you a tyre lost grip.", "وميض رمز الثبات لثوانٍ يعني أن النظام يعمل، فيقلّل القوة أو يفرمل إطاراً ليبقيك في مسارك. ولا يوجد عطل — بل تخبرك السيارة أن إطاراً فقد تماسكه."),
    action: L("Ease off the throttle and slow down — the road has less grip than you think.", "ارفع قدمك عن دوّاسة الوقود وخفّف السرعة — فالطريق أشد انزلاقاً مما تتوقع."),
  },
  {
    id: "service-due",
    glyph: "spanner",
    title: L("Service Due", "موعد الصيانة"),
    subtitle: "Service Due (Spanner)",
    severity: "info",
    summary: L("The car has reached a mileage or time interval for scheduled maintenance. It's a calendar reminder, not a fault reading.", "بلغت السيارة المسافة أو المدة المحددة للصيانة الدورية. وهذا تذكير بالموعد لا قراءة عطل."),
    action: L("Book the service and ask them to reset the indicator as part of it.", "احجز الصيانة واطلب تصفير العدّاد معها."),
  },
  {
    id: "low-fuel",
    glyph: "fuel-pump",
    title: L("Low Fuel", "الوقود قارب على الانتهاء"),
    subtitle: "Low Fuel",
    severity: "info",
    summary: L("There's usually 50–80 km of range left, and that shrinks fast in traffic or at motorway speed. Running a modern car dry can overheat the fuel pump that sits inside the tank.", "يتبقى عادة من 50 إلى 80 كم، وينخفض هذا الرقم بسرعة في الازدحام أو عند السرعات العالية. وتفريغ الخزان كلياً يُسخّن مضخة الوقود الموجودة داخله."),
    action: L("Fill up at the next station rather than the cheaper one two exits away.", "تزوّد بالوقود من أول محطة، لا من الأرخص التي تبعد مخرجين."),
  },
  {
    id: "washer-fluid-low",
    glyph: "washer",
    title: L("Washer Fluid", "انخفاض سائل المساحات"),
    subtitle: "Washer Fluid Low",
    severity: "info",
    summary: L("The windscreen washer reservoir is nearly empty. Not urgent, until the first time you're behind a dusty lorry with low sun in your eyes.", "أوشك خزان سائل المساحات على النفاد. وليس الأمر عاجلاً، حتى تجد نفسك خلف شاحنة مغبّرة والشمس في عينيك."),
    action: L("Top it up with proper screenwash rather than plain water, which freezes and grows algae.", "املأه بسائل مساحات مخصص بدلاً من الماء الاعتيادي، فالماء يتجمد ويُفسد الخزان."),
  },
  {
    id: "door-ajar",
    glyph: "door-ajar",
    title: L("Door Open", "باب غير مغلق"),
    subtitle: "Door / Bonnet / Boot Open",
    severity: "warning",
    summary: L("A door, bonnet or boot isn't latched properly. At speed an unlatched bonnet can fly up and block the windscreen completely.", "أحد الأبواب أو غطاء المحرك أو الصندوق غير مغلق بإحكام. وعند السرعة قد يرتفع غطاء المحرك غير المُحكم فيحجب الزجاج الأمامي بالكامل."),
    action: L("Stop somewhere safe and close it properly — don't drive on hoping it settles.", "توقّف في مكان آمن وأغلقه بإحكام — ولا تتابع على أمل أن يُغلق من تلقاء نفسه."),
  },
  {
    id: "high-beam",
    glyph: "high-beam",
    title: L("High Beams On", "الأضواء العالية مضاءة"),
    subtitle: "Main Beam / High Beam",
    severity: "info",
    summary: L("The blue symbol means main beam is on, whether you switched it on or the automatic system did. Left on in traffic it badly dazzles oncoming drivers.", "يدل هذا الرمز على أن الأضواء العالية مضاءة، سواء شغّلتها أنت أم النظام التلقائي. وبقاؤها مضاءة في الازدحام يُبهر السائقين المقابلين."),
    action: L("Dip them as soon as you see oncoming lights or catch a car ahead.", "أنزلها بمجرد أن ترى سيارة قادمة أو تلحق بسيارة أمامك."),
  },
  {
    id: "rear-fog-light",
    glyph: "rear-fog",
    title: L("Rear Fog Light", "ضوء الضباب الخلفي"),
    subtitle: "Rear Fog Light",
    severity: "info",
    summary: L("The rear fog lamp is on — far brighter than a normal tail light, and meant only for genuinely poor visibility. In clear conditions it dazzles the driver behind and masks your brake lights.", "ضوء الضباب الخلفي مضاء، وهو أقوى بكثير من الضوء الخلفي الاعتيادي ومخصص للضباب الكثيف وحده. وفي الجو الصافي يُبهر من خلفك ويحجب أضواء الفرامل."),
    action: L("Switch it off as soon as visibility improves.", "أطفئه بمجرد أن تعود الرؤية إلى طبيعتها."),
  },
  {
    id: "cruise-control-set",
    glyph: "cruise",
    title: L("Cruise Control On", "مثبت السرعة مفعّل"),
    subtitle: "Cruise Control Set",
    severity: "info",
    summary: L("The car is holding a set speed and will keep pulling to it downhill unless you brake. Basic cruise control doesn't see the car in front — only adaptive systems do.", "تحافظ السيارة على سرعة محددة وتستمر في دفعها حتى في المنحدر ما لم تفرمل. والمثبت الاعتيادي لا يرى السيارة التي أمامك، أما النظام التكيّفي فيراها."),
    action: L("Cancel it in rain, heavy traffic or on twisty roads and drive on the pedal.", "ألغِه في المطر والازدحام والطرق المتعرجة وقُد بالدوّاسة."),
  },
  {
    id: "ice-warning",
    glyph: "snowflake",
    title: L("Ice Warning", "تحذير من الجليد"),
    subtitle: "Low Temperature / Ice Warning",
    severity: "info",
    summary: L("Outside temperature has fallen to around 4°C or below, where bridges and shaded corners can already be icy. The car measures air, not road surface, so the tarmac may be worse than the number says.", "انخفضت حرارة الجو إلى 4 درجات أو أقل، وعند هذه الحرارة قد تكون الجسور والمنعطفات المظللة متجمدة. والسيارة تقيس حرارة الهواء لا الأسفلت، فقد يكون الطريق أسوأ من الرقم المعروض."),
    action: L("Slow down, brake and steer gently, and leave extra distance on bridges and flyovers.", "خفّف السرعة، وافرمل وانعطف بهدوء، واترك مسافة أكبر على الجسور."),
  },
  {
    id: "seatbelt-reminder",
    glyph: "seatbelt",
    title: L("Seat Belt", "تذكير حزام الأمان"),
    subtitle: "Seat Belt Reminder",
    severity: "info",
    summary: L("A belt is unfastened, or a heavy bag on a seat has triggered the occupant sensor. In a crash an unbelted passenger becomes a danger to everyone else in the car too.", "أحد الأحزمة غير مربوط، أو أن حقيبة ثقيلة على المقعد شغّلت الحسّاس. وعند وقوع حادث يصبح الراكب دون حزام خطراً على بقية الركاب أيضاً."),
    action: L("Buckle up, or move the bag to the footwell or the boot.", "اربط الحزام، أو ضع الحقيبة تحت المقعد أو في الصندوق."),
  },
  {
    id: "start-stop",
    glyph: "start-stop",
    title: L("Auto Stop/Start", "نظام الإطفاء والتشغيل التلقائي"),
    subtitle: "Stop/Start System",
    severity: "info",
    summary: L("The engine has shut down at a standstill to save fuel and restarts when you lift off the brake. An 'A' with a line through it means the system has disabled itself, usually because the 12V battery is low or the cabin needs cooling.", "توقّف المحرك أثناء وقوفك لتوفير الوقود، ويعمل بمجرد رفع قدمك عن الفرامل. وإن كان على الرمز خط، فذلك يعني أن النظام أوقف نفسه، غالباً بسبب بطارية ضعيفة أو حاجة المكيّف إلى التبريد."),
    action: L("Nothing to do — press the off button if you'd rather the engine kept running in traffic.", "لا يلزمك فعل شيء — اضغط زر الإيقاف إن أردت أن يبقى المحرك عاملاً في الازدحام."),
  },
];
