import { L } from "../i18n";
import type { LibraryEntry } from "./types";

/**
 * The 48 warning lights drivers actually see, across petrol, diesel, hybrid
 * and EV cars worldwide. Browsable without spending a scan, and it works
 * offline — a scanner with one screen feels like a demo.
 */
export const DASHLIGHT_LIBRARY: LibraryEntry[] = [
  {
    id: "check-engine-flashing",
    glyph: "engine",
    title: L("Check Engine — Flashing", "لمبة المحرك ترمش"),
    subtitle: "Check Engine Light (Flashing)",
    severity: "critical",
    summary: L("A flashing check engine light means the engine is misfiring right now and pushing unburned fuel into the exhaust. That can melt the catalytic converter within minutes, adding a very expensive repair on top of whatever caused it.", "لما لمبة المحرك ترمش، معناها في مشكلة إشعال صارت الآن والبنزين عم يوصل للشكمان بدون ما يحترق. هالشي ممكن يحرق الكتالايست خلال دقائق ويزيد تكلفة التصليح كثير."),
    action: L("Ease off the accelerator, drive gently to the nearest safe spot, switch off, and call for help — don't keep driving on it.", "خفف على دعسة البنزين، روح بهدوء لأقرب مكان آمن، طفّي السيارة واتصل بالميكانيكي — لا تكمل سواقة."),
  },
  {
    id: "check-engine-steady",
    glyph: "engine",
    title: L("Check Engine — Steady", "لمبة المحرك ثابتة"),
    subtitle: "Check Engine Light (Steady)",
    severity: "warning",
    summary: L("A steady amber light means the car has stored a fault code — anything from a loose fuel cap to a failing oxygen sensor. The car usually drives normally, but fuel economy and emissions suffer until it's read and fixed.", "اللمبة الثابتة معناها السيارة سجّلت عطل بالكمبيوتر — من غطا خزان البنزين المرخي لحد حسّاس أوكسجين خربان. غالباً السيارة تمشي عادي، بس الصرفية والعوادم تسوء لين ما تتصلح."),
    action: L("Check the fuel cap is clicked tight, then have the codes read within the next few days.", "تأكد إن غطا خزان البنزين مسكّر لآخره، وبعدين اقرأ الأعطال عند الميكانيكي خلال كم يوم."),
  },
  {
    id: "oil-pressure",
    glyph: "oil-can",
    title: L("Oil Pressure", "ضغط زيت المحرك"),
    subtitle: "Engine Oil Pressure",
    severity: "critical",
    summary: L("The oil pump is no longer holding pressure, so metal parts inside the engine are turning with little or no lubrication. An engine can destroy itself in under a minute in this state.", "ما عاد في ضغط زيت كافي، وأجزاء المحرك المعدنية عم تدور بدون تزييت. المحرك ممكن يتلف كلياً بأقل من دقيقة بهالحالة."),
    action: L("Pull over safely and switch the engine off immediately — do not restart it to \"just get home\".", "اركن على جنب فوراً وطفّي المحرك — ولا تشغّله مرة ثانية عشان توصل البيت."),
  },
  {
    id: "coolant-temp-high",
    glyph: "thermometer",
    title: L("Engine Temperature — High", "حرارة المحرك مرتفعة"),
    subtitle: "Engine Coolant Temperature (Red)",
    severity: "critical",
    summary: L("The engine is running hotter than its design limit, usually from lost coolant, a stuck thermostat or a dead cooling fan. Carrying on warps the cylinder head and blows the head gasket.", "حرارة المحرك تعدّت الحد المسموح، غالباً بسبب نقص ماء التبريد أو ثرموستات أو مروحة خربانة. إذا كملت سواقة ممكن يتقوّس رأس المحرك ويضرب الجوان."),
    action: L("Pull over, switch off, and let it cool for at least 30 minutes — never open a hot radiator cap.", "اركن، طفّي، واتركها تبرد نص ساعة على الأقل — ولا تفتح غطا الرادييتر وهو سخن."),
  },
  {
    id: "brake-warning-red",
    glyph: "brake",
    title: L("Brake System", "نظام الفرامل"),
    subtitle: "Brake System Warning",
    severity: "critical",
    summary: L("Either the parking brake is still applied, the brake fluid is low, or the hydraulic system has a fault. Low fluid almost always means a leak or badly worn pads, and pedal travel can get long with no warning.", "يا إما فرامل اليد مرفوعة، يا زيت الفرامل ناقص، يا في عطل بالنظام الهيدروليكي. نقص الزيت غالباً معناه تسريب أو فحمات مستهلكة، والدعسة ممكن تصير طويلة فجأة."),
    action: L("Release the handbrake first; if the light stays on, stop as soon as it's safe and have the car towed, not driven.", "أول شي نزّل فرامل اليد؛ وإذا ضلت اللمبة شغالة، اركن بأمان واسحب السيارة بونش بدل ما تسوقها."),
  },
  {
    id: "master-warning-red",
    glyph: "warning-triangle",
    title: L("Master Warning", "تحذير عام (مثلث أحمر)"),
    subtitle: "Master Warning (Red Triangle)",
    severity: "critical",
    summary: L("The red triangle is a catch-all: another system has raised a serious fault and the details are written on the driver's display. Red always means the car wants you to stop now, not to book an appointment.", "المثلث الأحمر تحذير عام: في نظام ثاني طلّع عطل خطير والتفاصيل مكتوبة على شاشة العدادات. الأحمر دائماً معناه وقّف الآن، مو خلّيها لبكرا."),
    action: L("Read the message on the dash, then pull over safely and act on exactly what it says.", "اقرأ الرسالة على الشاشة، وبعدين اركن بأمان وتصرّف حسب اللي مكتوب فيها."),
  },
  {
    id: "transmission-overheat",
    glyph: "thermometer",
    title: L("Transmission Overheating", "حرارة ناقل الحركة (الجير)"),
    subtitle: "Transmission Temperature / Fault",
    severity: "critical",
    summary: L("Gearbox fluid is above its safe temperature, usually after towing, a long climb or stop-start traffic in the heat. Overheated fluid burns and eats the clutch packs inside the transmission.", "حرارة زيت الجير تعدّت الحد الآمن، غالباً بعد سحب مقطورة أو طلعة طويلة أو زحمة بالحر. الزيت لما يحترق ياكل القوابض اللي جوّا الجير."),
    action: L("Stop somewhere safe, leave the engine idling in Park for a few minutes to cool it, then avoid loads until it's checked.", "اركن بمكان آمن، خلّي المحرك شغال على وضع P كم دقيقة حتى يبرد، وتجنب الأحمال لين ما تفحصها."),
  },
  {
    id: "ev-hv-fault",
    glyph: "ev-fault",
    title: L("High-Voltage System Fault", "عطل بنظام الجهد العالي"),
    subtitle: "High-Voltage System Fault (EV/Hybrid)",
    severity: "critical",
    summary: L("The car has found a fault in the high-voltage battery or drive system and may cut power without warning. High-voltage components are never a roadside DIY job.", "السيارة اكتشفت عطل ببطارية الجهد العالي أو نظام الدفع، وممكن تقطع القدرة فجأة. أجزاء الجهد العالي ما تتصلح أبداً على جنب الطريق."),
    action: L("Pull over away from traffic, shut the car down, and call EV assistance — don't open the bonnet or touch orange cables.", "اركن بعيد عن حركة السير، طفّي السيارة، واتصل بمساعدة الوكالة للسيارات الكهربائية — ولا تفتح الكبوت ولا تلمس الكابلات البرتقالية."),
  },
  {
    id: "catalytic-overheat",
    glyph: "catalytic",
    title: L("Catalyst Overheat", "سخونة الكتالايست"),
    subtitle: "Catalytic Converter Overheat",
    severity: "critical",
    summary: L("The exhaust catalyst is running far above normal temperature, usually because unburned fuel from a misfire is reaching it. It can glow hot enough to set dry grass under the car alight.", "الكتالايست حرارته صارت أعلى من الطبيعي بكثير، غالباً لأن بنزين غير محترق وصله من عطل بالإشعال. ممكن يسخن لدرجة يشعل عشب ناشف تحت السيارة."),
    action: L("Stop on tarmac rather than grass, switch off, and have it recovered instead of driven.", "اركن على الأسفلت مو على العشب، طفّي السيارة، وخلّيهم يسحبوها بونش بدل ما تسوقها."),
  },
  {
    id: "abs",
    glyph: "abs",
    title: L("Anti-lock Brakes", "نظام منع انغلاق الفرامل"),
    subtitle: "Anti-lock Braking System (ABS)",
    severity: "warning",
    summary: L("Normal braking still works, but the anti-lock system is offline, so the wheels can lock and skid in an emergency stop. Stopping distances on wet roads get noticeably longer.", "الفرامل العادية شغالة، بس نظام ABS معطّل، يعني الإطارات ممكن تقفل وتزحلق بالفرملة المفاجئة. ومسافة الوقوف تطول على الطرق المبلولة."),
    action: L("Drive gently, leave extra following distance, and book a brake diagnostic this week.", "سوق بهدوء، خلّي مسافة أكبر عن اللي قدامك، واحجز فحص فرامل هالأسبوع."),
  },
  {
    id: "charging-system",
    glyph: "battery",
    title: L("Charging System", "نظام الشحن"),
    subtitle: "Battery / Charging System",
    severity: "warning",
    summary: L("The alternator has stopped charging and the car is running on the battery alone — typically 20 to 40 minutes before everything shuts down. It rarely means the battery itself is the faulty part.", "الدينمو وقف عن الشحن والسيارة عم تشتغل على البطارية بس — عادة من ٢٠ لـ ٤٠ دقيقة وبعدها تطفى. ونادراً تكون البطارية نفسها هي الخربانة."),
    action: L("Switch off the AC, screen and heated seats and drive straight to a garage without stopping the engine.", "طفّي المكيف والشاشة وأي شي زيادة، وروح مباشرة للورشة بدون ما تطفي المحرك."),
  },
  {
    id: "airbag-srs",
    glyph: "airbag",
    title: L("Airbag System", "نظام الوسائد الهوائية"),
    subtitle: "Airbag / SRS",
    severity: "warning",
    summary: L("The restraint system has a fault, which usually means the airbags and belt pretensioners will not fire in a crash. A few faults can also cause an airbag to deploy when it shouldn't.", "في عطل بنظام الأمان، وغالباً معناه إن الوسائد الهوائية وشدّادات الأحزمة ما رح تشتغل بالحادث. وبحالات قليلة العطل نفسه يخلي الوسادة تنفجر بدون سبب."),
    action: L("Keep driving carefully but book it in, and don't let anyone poke at the wiring under the seats.", "كمّل سواقة بحذر بس احجز موعد بالورشة، ولا تخلي أحد يعبث بالأسلاك تحت الكراسي."),
  },
  {
    id: "tpms",
    glyph: "tyre",
    title: L("Tyre Pressure", "ضغط الإطارات"),
    subtitle: "Tyre Pressure Monitoring (TPMS)",
    severity: "warning",
    summary: L("At least one tyre is roughly 25% below its correct pressure, or the monitoring system itself has failed. Under-inflated tyres overheat, wear at the shoulders and can fail at speed.", "في إطار على الأقل ضغطه أقل بحوالي ٢٥٪ من اللازم، أو النظام نفسه خربان. الإطار الناقص هوا يسخن ويتآكل من الأطراف وممكن ينفجر بالسرعة."),
    action: L("Check all four pressures cold against the sticker in the driver's door frame and inflate to spec.", "قِس ضغط الأربع إطارات وهي باردة حسب الملصق على إطار باب السائق وعبّيهم للرقم المكتوب."),
  },
  {
    id: "brake-pad-wear",
    glyph: "pad-wear",
    title: L("Brake Pads Worn", "فحمات الفرامل مستهلكة"),
    subtitle: "Brake Pad Wear",
    severity: "warning",
    summary: L("A sensor in the pad has reached the wear line, leaving only a few millimetres of friction material. Ignore it and the backing plate scores the disc, turning a cheap job into an expensive one.", "الحسّاس اللي بالفحمة وصل لحد التآكل وما ضل إلا كم مليمتر. وإذا أهملتها، الحديد يحك الديسك ويصير التصليح أغلى بكثير."),
    action: L("Book a pad replacement in the next week or two — sooner if you hear metal grinding.", "غيّر الفحمات خلال أسبوع أو أسبوعين، وأسرع إذا سمعت صوت حك حديد."),
  },
  {
    id: "power-steering-fault",
    glyph: "steering",
    title: L("Power Steering Fault", "عطل بمقود الباور"),
    subtitle: "Electric Power Steering (EPS)",
    severity: "warning",
    summary: L("Steering assistance has been reduced or lost, so the wheel goes very heavy, especially when parking or at low speed. The steering still works mechanically — it just takes far more effort.", "مساعدة المقود ضعفت أو راحت، والدركسون يصير ثقيل كثير خصوصاً بالركن والسرعات البطيئة. المقود لسا شغال ميكانيكياً بس يحتاج مجهود أكبر."),
    action: L("Slow down, keep both hands on the wheel, and drive straight to a garage — avoid tight car parks.", "خفف السرعة، خلّي يديك الثنتين على الدركسون، وروح مباشرة للورشة — وتجنب المواقف الضيقة."),
  },
  {
    id: "esc-fault",
    glyph: "skid-car",
    title: L("Stability Control Fault", "عطل بنظام الثبات"),
    subtitle: "Stability Control Fault (ESC/ESP/VSC)",
    severity: "warning",
    summary: L("Electronic stability control has shut itself down because of a fault, so the car will no longer catch a skid for you. On wet, sandy or icy roads that safety net is gone.", "نظام الثبات طفّى نفسه بسبب عطل، يعني السيارة ما رح تصحّح الانزلاق عنك. وعلى الطرق المبلولة أو الرملية أو المثلجة، شبكة الأمان هاي راحت."),
    action: L("Reduce speed, avoid sudden steering, and have it scanned soon — it's often just a wheel speed sensor.", "خفف السرعة وتجنب المناورات المفاجئة، وافحصها قريباً — غالباً حسّاس سرعة إطار."),
  },
  {
    id: "esc-off",
    glyph: "esc-off",
    title: L("Stability Control Off", "نظام الثبات مطفي"),
    subtitle: "Stability Control Off",
    severity: "warning",
    summary: L("Stability and traction control are switched off, either by the button or automatically in a sport or off-road mode. Wheelspin and slides are no longer corrected for you.", "نظام الثبات والسحب مطفي، يا من الزر يا تلقائياً بوضع رياضي أو وضع طرق وعرة. يعني الفرط والانزلاق ما رح ينمسك تلقائياً."),
    action: L("Press the ESC button once to switch it back on unless you're deliberately freeing a stuck car.", "اضغط زر ESC مرة وحدة يرجع يشتغل، إلا إذا كنت قاصد تطلّع السيارة من رمل أو طين."),
  },
  {
    id: "dpf",
    glyph: "dpf",
    title: L("Diesel Particulate Filter", "فلتر جزيئات الديزل"),
    subtitle: "Diesel Particulate Filter (DPF)",
    severity: "warning",
    summary: L("The soot filter in the exhaust is full because the car has done too many short, cold trips to burn it clear. Left alone it blocks solid and needs forced cleaning or replacement.", "فلتر السخام اللي بالشكمان امتلأ لأن السيارة تمشي مشاوير قصيرة وباردة وما تقدر تحرقه. وإذا تركته ينسد كلياً ويحتاج تنظيف إجباري أو تغيير."),
    action: L("Drive 15–20 minutes at a steady main-road speed in a lower gear to let it regenerate.", "سوق ١٥–٢٠ دقيقة بسرعة ثابتة على طريق سريع وبغيار أوطى شوي حتى يحرق السخام."),
  },
  {
    id: "adblue",
    glyph: "droplet",
    title: L("AdBlue Low", "سائل الأدبلو ناقص"),
    subtitle: "AdBlue / DEF Level",
    severity: "warning",
    summary: L("The exhaust fluid that cleans diesel emissions is running low, and the display usually counts down the range you have left. When it hits zero, emissions law requires the car to refuse to restart.", "سائل الأدبلو اللي ينظف عوادم الديزل قارب يخلص، والشاشة عادة تعد المسافة الباقية. ولما يخلص، السيارة تمنع نفسها من التشغيل حسب قوانين العوادم."),
    action: L("Top up with AdBlue from any fuel station or parts shop before the countdown runs out.", "عبّي أدبلو من أي محطة أو محل قطع غيار قبل ما ينتهي العدّاد."),
  },
  {
    id: "water-in-fuel",
    glyph: "water-in-fuel",
    title: L("Water in Fuel", "ماء بخزان الديزل"),
    subtitle: "Water in Fuel (Diesel)",
    severity: "warning",
    summary: L("Water has collected in the diesel filter's separator, usually from condensation or poor-quality fuel. If it reaches the injection pump it wrecks it — one of the most expensive repairs on a diesel.", "تجمّع ماء بفلتر الديزل، غالباً من التكثيف أو وقود مو نظيف. وإذا وصل الماء لطرمبة البخّاخات يتلفها، وهذا من أغلى التصليحات بالديزل."),
    action: L("Stop soon and drain the filter's water trap, or have a garage do it the same day.", "وقّف قريباً وصفّي الماء من الفلتر، أو خلّي الورشة تسويها بنفس اليوم."),
  },
  {
    id: "oil-level-low",
    glyph: "oil-can",
    title: L("Oil Level Low", "مستوى الزيت منخفض"),
    subtitle: "Engine Oil Level Low",
    severity: "warning",
    summary: L("The sensor in the sump reads below minimum — this is about how much oil is in there, not oil pressure, so it's a warning rather than an emergency. Running low still raises wear and oil temperature.", "الحسّاس اللي بالكارتير قارئ أقل من الحد الأدنى — الكلام هنا عن كمية الزيت مو عن الضغط، فمو حالة طوارئ. بس النقص يزيد التآكل وحرارة الزيت."),
    action: L("Check the dipstick cold on level ground and top up with the grade in the owner's manual.", "افحص عصا الزيت والسيارة باردة وعلى أرض مستوية، وعبّي بنفس نوع الزيت المكتوب بالكتيّب."),
  },
  {
    id: "coolant-level-low",
    glyph: "coolant",
    title: L("Coolant Low", "ماء التبريد ناقص"),
    subtitle: "Coolant Level Low",
    severity: "warning",
    summary: L("The expansion tank has dropped below minimum, which usually points to a slow leak from a hose, the radiator or the cap. Coolant isn't consumed — if it's low, it went somewhere.", "خزان التبريد نزل تحت الحد الأدنى، وغالباً في تسريب بسيط من خرطوم أو الرادييتر أو الغطا نفسه. سائل التبريد ما ينشرب — إذا ناقص يعني طلع من مكان."),
    action: L("Top up with the correct coolant while the engine is cold, then have the leak traced.", "عبّي سائل التبريد المناسب والمحرك بارد، وبعدين دوّر على مصدر التسريب بالورشة."),
  },
  {
    id: "bulb-failure",
    glyph: "bulb",
    title: L("Bulb Out", "لمبة خارجية محروقة"),
    subtitle: "Exterior Light Failure",
    severity: "warning",
    summary: L("One of the exterior bulbs — brake, indicator, tail or headlight — has failed or is drawing the wrong current. A dead brake light is a common cause of both rear-end collisions and fines.", "وحدة من اللمبات الخارجية — فرامل، غماز، خلفية أو أمامية — محروقة أو سحبها مو صح. ولمبة الفرامل المطفية من أكثر أسباب الاصطدام من الخلف والمخالفات."),
    action: L("Have someone stand behind the car while you test brakes and indicators, then replace the dead bulb.", "خلّي أحد يوقف ورا السيارة وجرّب الفرامل والغمازات، وبدّل اللمبة المحروقة."),
  },
  {
    id: "epb-fault",
    glyph: "epb",
    title: L("Parking Brake Fault", "عطل بفرامل اليد الكهربائية"),
    subtitle: "Electronic Parking Brake Fault",
    severity: "warning",
    summary: L("The electric parking brake has a fault and may not hold the car, or may not release fully. A partly stuck brake overheats the rear pads and can burn them out in one drive.", "في عطل بفرامل اليد الكهربائية، وممكن ما تمسك السيارة أو ما تفك كامل. والفرملة اللي ما تفك تسخّن الفحمات الخلفية وتحرقها بمشوار واحد."),
    action: L("Park in gear or in P on level ground, chock a wheel on a slope, and get it fixed before it strands you.", "اركن وحط الغيار أو وضع P على أرض مستوية، وحط حجر تحت الإطار إذا كنت على منحدر، وصلّحها قبل ما تعلّقك."),
  },
  {
    id: "immobiliser",
    glyph: "key",
    title: L("Immobiliser", "نظام الحماية (الإيموبلايزر)"),
    subtitle: "Immobiliser / Security",
    severity: "warning",
    summary: L("The security system isn't recognising the key's transponder, so the engine is blocked from starting or will cut out. A slowly flashing car-and-key symbol with the car parked is normal; lit while driving is not.", "نظام الحماية ما عم يتعرّف على شريحة المفتاح، فيمنع التشغيل أو يطفي المحرك. رمز السيارة والمفتاح وهو يرمش والسيارة مطفية شي طبيعي، بس إذا اشتغل وأنت سايق فمو طبيعي."),
    action: L("Try the spare key — if that starts the car, the first key or its battery is the problem.", "جرّب المفتاح الاحتياطي؛ إذا اشتغلت السيارة، يعني المشكلة بالمفتاح الأول أو ببطاريته."),
  },
  {
    id: "key-not-detected",
    glyph: "key",
    title: L("Key Not Detected", "المفتاح غير موجود"),
    subtitle: "Key Not Detected",
    severity: "warning",
    summary: L("The car can't find the smart key inside the cabin — usually a flat fob battery, or the key sitting in a bag against metal. If you switch the engine off now, it may not restart.", "السيارة ما لاقية المفتاح الذكي جوّا، وغالباً بطارية الريموت فاضية أو المفتاح بشنطة ملاصق لمعدن. وإذا طفّيت المحرك الآن، يمكن ما يشتغل من جديد."),
    action: L("Don't switch off until you're somewhere you can get help; to start, hold the fob against the marked spot by the start button.", "لا تطفي المحرك لين ما توصل مكان تقدر تلاقي فيه مساعدة، وللتشغيل حط الريموت على المكان المحدد جنب زر التشغيل."),
  },
  {
    id: "aeb-fault",
    glyph: "radar-car",
    title: L("Collision Assist Fault", "عطل بنظام منع التصادم"),
    subtitle: "Forward Collision / AEB Fault",
    severity: "warning",
    summary: L("The forward-facing radar or camera is blocked or faulty, so automatic emergency braking and collision alerts are switched off. Very often it's just dirt, ice or a stone chip in front of the sensor.", "الرادار أو الكاميرا الأمامية مغطّاة أو فيها عطل، فنظام الفرملة التلقائية والتنبيه معطّل. وكثير مرات السبب بس وسخ أو ثلج أو كسر بسيط بالزجاج قدام الحسّاس."),
    action: L("Clean the windscreen in front of the mirror and around the grille badge, restart, and book a scan if it stays on.", "نظّف الزجاج قدام المراية وحول شعار الشبك الأمامي وأعد التشغيل، وإذا ضلت اللمبة افحصها بالورشة."),
  },
  {
    id: "air-suspension-fault",
    glyph: "suspension",
    title: L("Air Suspension Fault", "عطل بالتعليق الهوائي"),
    subtitle: "Air Suspension Fault",
    severity: "warning",
    summary: L("The air suspension can't hold its set ride height, usually from a leaking air spring or a tired compressor. The car may sag overnight or drop onto its bump stops while driving.", "نظام التعليق الهوائي ما عاد يمسك ارتفاع السيارة، غالباً تسريب بمساعد هوائي أو كمبرسر تعبان. وممكن تلاقي السيارة نازلة الصبح أو تهبط وأنت سايق."),
    action: L("Avoid speed bumps and rough roads, keep the speed down, and get it inspected before it drops completely.", "تجنب المطبات والطرق الوعرة، خفف السرعة، وافحصها قبل ما تهبط كلياً."),
  },
  {
    id: "ev-low-charge",
    glyph: "ev-battery",
    title: L("Battery Charge Low", "شحن البطارية منخفض"),
    subtitle: "Low State of Charge (EV)",
    severity: "warning",
    summary: L("The traction battery is near the bottom of its usable range, and remaining range drops faster than the number suggests on motorways or in cold weather. Running it to zero usually means a flatbed, not a jump start.", "بطارية السيارة قاربت تخلص، والمدى الباقي ينزل أسرع من الرقم اللي على الشاشة، خصوصاً على الطريق السريع أو بالبرد. وإذا خلصت كلياً تحتاج سطحة، مو كيبل شحن."),
    action: L("Set the nearest working charger as your destination now and settle into a slower, steadier speed.", "حط أقرب شاحن شغّال كوجهة على الخريطة الآن، وخفف سرعتك وخلّيها ثابتة."),
  },
  {
    id: "reduced-power-turtle",
    glyph: "turtle",
    title: L("Reduced Power", "قدرة محدودة (لمبة السلحفاة)"),
    subtitle: "Reduced Power (Turtle)",
    severity: "warning",
    summary: L("The car has limited its own power to protect the battery or motor — from very low charge, high temperature, or a logged fault. Acceleration becomes weak, which is genuinely risky when joining fast roads.", "السيارة حدّت قدرتها لحماية البطارية أو الموتور — بسبب شحن قليل جداً أو حرارة عالية أو عطل مسجّل. والتسارع يصير ضعيف، وهذا خطر عند الدخول على طريق سريع."),
    action: L("Move to the slow lane, don't attempt overtakes, and head for the nearest charger or garage.", "انتقل للمسرب البطيء، لا تحاول تتجاوز أحد، وروح لأقرب شاحن أو ورشة."),
  },
  {
    id: "regen-brake-fault",
    glyph: "regen",
    title: L("Regen Braking Fault", "عطل بالفرملة المسترجعة"),
    subtitle: "Regenerative Braking Fault",
    severity: "warning",
    summary: L("Energy recovery under braking has been reduced or disabled — often because the battery is full or very cold, sometimes because a fault was logged. The pedal feels different and the usual one-pedal slowdown disappears.", "استرجاع الطاقة عند الفرملة ضعف أو توقف، غالباً لأن البطارية ممتلئة أو باردة كثير، وأحياناً بسبب عطل مسجّل. ودعسة الفرامل يتغير إحساسها وتفقد التباطؤ المعتاد لما ترفع رجلك."),
    action: L("Brake earlier and expect the car to coast further; if it doesn't clear as the battery warms or discharges, get it scanned.", "افرمل بدري وتوقّع السيارة تمشي بالعزم مسافة أطول قبل ما تقف، وإذا ما راحت اللمبة بعد ما تدفى البطارية أو تنقص شحنتها افحصها."),
  },
  {
    id: "hybrid-system-warning",
    glyph: "hybrid",
    title: L("Hybrid System", "تحذير النظام الهجين"),
    subtitle: "Hybrid System Warning",
    severity: "warning",
    summary: L("The hybrid controller has logged a fault in the electric drive, battery cooling or the engine-to-motor handover. The car usually still moves, but power and economy drop and it can go into limp mode.", "كمبيوتر النظام الهجين سجّل عطل بالدفع الكهربائي أو تبريد البطارية أو التبديل بين المحرك والموتور. وغالباً السيارة تمشي، بس القدرة والصرفية يتأثروا وممكن تدخل بوضع الطوارئ."),
    action: L("Keep speeds moderate and book a hybrid-trained workshop within a day or two.", "خفف السرعة وخلّيها معتدلة، واحجز ورشة متخصصة بالهايبرد خلال يوم أو يومين."),
  },
  {
    id: "ev-12v-battery",
    glyph: "battery",
    title: L("12V Battery", "بطارية ١٢ فولت"),
    subtitle: "12V Battery (EV/Hybrid)",
    severity: "warning",
    summary: L("The small 12-volt battery that wakes the car and runs its computers is weak, even with the main traction battery full. A flat 12V is the single most common reason an EV won't switch on at all.", "بطارية الـ ١٢ فولت الصغيرة اللي تشغّل كمبيوترات السيارة صارت ضعيفة، حتى لو البطارية الكبيرة مليانة. وأكثر سبب إن السيارة الكهربائية ما تفتح أبداً هو هالبطارية."),
    action: L("Keep the car plugged in or driven daily until you can have the 12V battery tested and replaced.", "خلّي السيارة موصولة بالشاحن أو سوقها يومياً لين ما تفحص بطارية الـ ١٢ فولت وتبدّلها."),
  },
  {
    id: "master-caution-amber",
    glyph: "warning-triangle",
    title: L("Master Caution", "تنبيه عام أصفر"),
    subtitle: "Master Caution (Amber)",
    severity: "warning",
    summary: L("The amber general warning points you to a message on the driver's display; the symbol on its own tells you nothing. Amber means attention needed soon, not an emergency stop.", "التنبيه الأصفر العام يوجّهك لرسالة على شاشة العدادات، والرمز لحاله ما يقول شي. والأصفر معناه انتبه قريباً، مو حالة طوارئ."),
    action: L("Read the dash message and deal with whichever system it names.", "اقرأ الرسالة على الشاشة وعالج النظام اللي ذكرته."),
  },
  {
    id: "glow-plug",
    glyph: "glow-plug",
    title: L("Glow Plug Preheat", "تسخين البوجيهات (ديزل)"),
    subtitle: "Glow Plug / Preheat (Diesel)",
    severity: "info",
    summary: L("The coil symbol shows the diesel's glow plugs are warming the cylinders before starting, and it should go out after a second or two. If it stays lit or flashes while driving, it has become an engine fault warning instead.", "رمز الملف معناه بوجيهات التسخين عم تدفّي المحرك قبل التشغيل، ولازم تطفى بعد ثانية أو ثنتين. أما إذا ضلت شغالة أو رمشت وأنت سايق، فصارت تحذير عطل بالمحرك."),
    action: L("Wait for the light to go out before cranking the engine.", "استنى لين تطفى اللمبة وبعدها شغّل المحرك."),
  },
  {
    id: "ev-ready",
    glyph: "ev-ready",
    title: L("Ready", "جاهزة للسير"),
    subtitle: "Ready to Drive (EV/Hybrid)",
    severity: "info",
    summary: L("The car is powered up and will move the moment you select a gear, even though there's no engine noise. This is the EV and hybrid equivalent of an engine idling.", "السيارة جاهزة وتتحرك أول ما تحط الغيار، حتى لو ما في صوت محرك. وهذا مقابل صوت المحرك الشغال بالسيارات العادية."),
    action: L("Keep your foot on the brake until you've selected D or R — it can creep the moment you lift off.", "خلّي رجلك على الفرامل لين ما تختار D أو R — لأنها تتحرك لحالها أول ما ترفع رجلك."),
  },
  {
    id: "charging-cable-connected",
    glyph: "plug",
    title: L("Plugged In", "الشاحن موصول"),
    subtitle: "Charging Cable Connected",
    severity: "info",
    summary: L("The charge cable is locked into the car and on most models drive is blocked while it's attached. A change of colour or pulse is what tells you charging has actually started.", "كابل الشحن مثبّت بالسيارة، وبمعظم الموديلات السيارة ما تتحرك وهو موصول. وتغيّر اللون أو النبض هو اللي يقول لك إن الشحن فعلاً بدأ."),
    action: L("Confirm the light shows charging, not just connected, before you walk away.", "تأكد إن اللمبة تقول عم تشحن مو بس موصولة قبل ما تمشي."),
  },
  {
    id: "esc-active-flashing",
    glyph: "skid-car",
    title: L("Stability Control Working", "نظام الثبات يشتغل"),
    subtitle: "Stability Control Active (Flashing)",
    severity: "info",
    summary: L("A briefly flashing stability symbol means the system is actively cutting power or braking one wheel to keep you on line. Nothing is broken — the car is telling you a tyre lost grip.", "لما رمز الثبات يرمش لثواني، معناها النظام عم يشتغل ويقلل القوة أو يفرمل إطار حتى يبقيك على مسارك. ما في عطل — بس السيارة تقول لك إن إطار فقد التماسك."),
    action: L("Ease off the throttle and slow down — the road has less grip than you think.", "ارفع رجلك عن البنزين وخفف السرعة — الطريق أزلق مما تتوقع."),
  },
  {
    id: "service-due",
    glyph: "spanner",
    title: L("Service Due", "موعد الصيانة"),
    subtitle: "Service Due (Spanner)",
    severity: "info",
    summary: L("The car has reached a mileage or time interval for scheduled maintenance. It's a calendar reminder, not a fault reading.", "السيارة وصلت للممشى أو المدة المحددة للصيانة الدورية. وهذا تذكير بالموعد، مو قراءة عطل."),
    action: L("Book the service and ask them to reset the indicator as part of it.", "احجز الصيانة واطلب منهم يصفّرون العدّاد معها."),
  },
  {
    id: "low-fuel",
    glyph: "fuel-pump",
    title: L("Low Fuel", "الوقود قارب على الانتهاء"),
    subtitle: "Low Fuel",
    severity: "info",
    summary: L("There's usually 50–80 km of range left, and that shrinks fast in traffic or at motorway speed. Running a modern car dry can overheat the fuel pump that sits inside the tank.", "عادة يضل من ٥٠ لـ ٨٠ كم، وهالرقم ينزل بسرعة بالزحمة أو بالسرعات العالية. وتفضية الخزان كلياً تسخّن طرمبة البنزين اللي جوّاه."),
    action: L("Fill up at the next station rather than the cheaper one two exits away.", "عبّي من أول محطة، مو من الأرخص اللي على بعد مخرجين."),
  },
  {
    id: "washer-fluid-low",
    glyph: "washer",
    title: L("Washer Fluid", "ماء المساحات ناقص"),
    subtitle: "Washer Fluid Low",
    severity: "info",
    summary: L("The windscreen washer reservoir is nearly empty. Not urgent, until the first time you're behind a dusty lorry with low sun in your eyes.", "خزان ماء المساحات قارب يفضى. مو مستعجل، لين أول مرة تكون ورا شاحنة مغبّرة والشمس بعينك."),
    action: L("Top it up with proper screenwash rather than plain water, which freezes and grows algae.", "عبّيه بسائل مساحات مخصص بدل الماء العادي، لأنه يتجمّد ويعفّن الخزان."),
  },
  {
    id: "door-ajar",
    glyph: "door-ajar",
    title: L("Door Open", "في باب غير مغلق"),
    subtitle: "Door / Bonnet / Boot Open",
    severity: "warning",
    summary: L("A door, bonnet or boot isn't latched properly. At speed an unlatched bonnet can fly up and block the windscreen completely.", "في باب أو كبوت أو صندوق مو مقفول صح. وبالسرعة، الكبوت اللي مو مسكّر ممكن يطير ويغطي الزجاج الأمامي كله."),
    action: L("Stop somewhere safe and close it properly — don't drive on hoping it settles.", "اركن بمكان آمن وسكّره صح — لا تكمل وتقول رح ينسكّر لحاله."),
  },
  {
    id: "high-beam",
    glyph: "high-beam",
    title: L("High Beams On", "الأضواء العالية شغالة"),
    subtitle: "Main Beam / High Beam",
    severity: "info",
    summary: L("The blue symbol means main beam is on, whether you switched it on or the automatic system did. Left on in traffic it badly dazzles oncoming drivers.", "الرمز الأزرق معناه الأضواء العالية شغالة، سواء أنت شغّلتها أو النظام التلقائي. وإذا ضلت شغالة بالزحمة تعمي السواق المقابلين."),
    action: L("Dip them as soon as you see oncoming lights or catch a car ahead.", "نزّلها أول ما تشوف سيارة جاية أو تلحق سيارة قدامك."),
  },
  {
    id: "rear-fog-light",
    glyph: "rear-fog",
    title: L("Rear Fog Light", "ضوء الضباب الخلفي"),
    subtitle: "Rear Fog Light",
    severity: "info",
    summary: L("The rear fog lamp is on — far brighter than a normal tail light, and meant only for genuinely poor visibility. In clear conditions it dazzles the driver behind and masks your brake lights.", "ضوء الضباب الخلفي شغال، وهو أقوى بكثير من الضوء الخلفي العادي ومخصص للضباب الكثيف بس. وبالجو الصافي يعمي اللي وراك ويخفي أضواء الفرامل."),
    action: L("Switch it off as soon as visibility improves.", "طفّيه أول ما ترجع الرؤية طبيعية."),
  },
  {
    id: "cruise-control-set",
    glyph: "cruise",
    title: L("Cruise Control On", "مثبت السرعة شغال"),
    subtitle: "Cruise Control Set",
    severity: "info",
    summary: L("The car is holding a set speed and will keep pulling to it downhill unless you brake. Basic cruise control doesn't see the car in front — only adaptive systems do.", "السيارة ماسكة سرعة محددة ورح تضل تدفع عليها حتى بالنزلة إلا إذا فرملت. والمثبت العادي ما يشوف السيارة اللي قدامك، بس النظام التكيّفي يشوفها."),
    action: L("Cancel it in rain, heavy traffic or on twisty roads and drive on the pedal.", "ألغيه بالمطر والزحمة والطرق المتعرجة وسوق على الدعسة."),
  },
  {
    id: "ice-warning",
    glyph: "snowflake",
    title: L("Ice Warning", "تحذير من الجليد"),
    subtitle: "Low Temperature / Ice Warning",
    severity: "info",
    summary: L("Outside temperature has fallen to around 4°C or below, where bridges and shaded corners can already be icy. The car measures air, not road surface, so the tarmac may be worse than the number says.", "حرارة الجو نزلت لحدود ٤ درجات أو أقل، وبهالحرارة الجسور والمنعطفات المظللة ممكن تكون متجمدة. والسيارة تقيس حرارة الهوا مو الأسفلت، فالطريق ممكن يكون أسوأ من الرقم."),
    action: L("Slow down, brake and steer gently, and leave extra distance on bridges and flyovers.", "خفف السرعة، افرمل ولف بهدوء، وخلّي مسافة أكبر على الجسور."),
  },
  {
    id: "seatbelt-reminder",
    glyph: "seatbelt",
    title: L("Seat Belt", "تذكير حزام الأمان"),
    subtitle: "Seat Belt Reminder",
    severity: "info",
    summary: L("A belt is unfastened, or a heavy bag on a seat has triggered the occupant sensor. In a crash an unbelted passenger becomes a danger to everyone else in the car too.", "في حزام مو مربوط، أو في شنطة ثقيلة على الكرسي شغّلت الحسّاس. وبالحادث، الراكب بدون حزام يصير خطر على باقي الركاب كمان."),
    action: L("Buckle up, or move the bag to the footwell or the boot.", "اربط الحزام، أو حط الشنطة تحت الكرسي أو بالصندوق."),
  },
  {
    id: "start-stop",
    glyph: "start-stop",
    title: L("Auto Stop/Start", "نظام الإطفاء والتشغيل التلقائي"),
    subtitle: "Stop/Start System",
    severity: "info",
    summary: L("The engine has shut down at a standstill to save fuel and restarts when you lift off the brake. An 'A' with a line through it means the system has disabled itself, usually because the 12V battery is low or the cabin needs cooling.", "المحرك طفى وأنت واقف عشان يوفر وقود، ويشتغل أول ما ترفع رجلك عن الفرامل. وإذا الرمز عليه خط، معناه النظام عطّل نفسه، غالباً بطارية ضعيفة أو المكيف محتاج يبرّد."),
    action: L("Nothing to do — press the off button if you'd rather the engine kept running in traffic.", "ما في شي تعمله — اضغط زر الإيقاف إذا تحب المحرك يضل شغال بالزحمة."),
  },
];
