import { L } from "../i18n";
import type { LibraryEntry } from "./types";

/**
 * The 32 warning lights a driver actually sees. Browsable without spending a
 * scan, works offline, and gives the app something to be when the camera is
 * closed — a scanner with one screen feels like a demo.
 *
 * Ordered roughly by how urgent they are, so the dangerous ones are first.
 */
export const DASHLIGHT_LIBRARY: LibraryEntry[] = [
  {
    id: "oil-pressure",
    title: L("Oil pressure", "ضغط الزيت"),
    subtitle: "Oil Pressure",
    severity: "critical",
    summary: L("Engine oil pressure has dropped below safe. The engine can be destroyed within minutes.", "ضغط زيت المحرك نزل عن الحد الآمن. المحرك ممكن يتلف خلال دقائق."),
    action: L("Pull over immediately and switch the engine off. Do not keep driving.", "اوقف على جنب فوراً وطفّي المحرك. لا تكمل سواقة أبداً."),
  },
  {
    id: "coolant-temp",
    title: L("Engine temperature", "حرارة المحرك"),
    subtitle: "Coolant Temperature",
    severity: "critical",
    summary: L("The engine is overheating. Driving on can warp the cylinder head.", "المحرك سخن فوق الحد. الاستمرار بالسواقة ممكن يشوي رأس المحرك."),
    action: L("Pull over, turn off the A/C and open the windows. Let it cool before opening the radiator.", "اوقف، طفّي المكيف، وافتح الشبابيك. استنى المحرك يبرد قبل ما تفتح الراديتر."),
  },
  {
    id: "brake",
    title: L("Brakes", "الفرامل"),
    subtitle: "Brake System",
    severity: "critical",
    summary: L("A brake system fault, low brake fluid, or the parking brake is still engaged.", "خلل بنظام الفرامل، أو زيت الفرامل ناقص، أو الفرامل اليدوية مرفوعة."),
    action: L("Check the handbrake is fully released. If it stays on, stop — the brakes could fail.", "تأكد إن اليدوي منزّل. إذا اللمبة ضلت، اوقف — الفرامل ممكن تفشل."),
  },
  {
    id: "charging",
    title: L("Charging / battery", "الشحن / البطارية"),
    subtitle: "Battery / Charging",
    severity: "critical",
    summary: L("The alternator isn't charging. You're running on battery alone and the car may cut out.", "الدينمو مش عم يشحن. السيارة عم تمشي على البطارية وحدها وممكن تطفى."),
    action: L("Switch off the A/C and any unnecessary lights and drive straight to a garage.", "طفّي المكيف والأضواء غير الضرورية وروح على أقرب ورشة مباشرة."),
  },
  {
    id: "airbag",
    title: L("Airbag", "الوسادة الهوائية"),
    subtitle: "Airbag / SRS",
    severity: "critical",
    summary: L("A fault in the airbag system. They may not deploy in a crash.", "خلل بنظام الوسائد الهوائية. ممكن ما تنفتح عند الحادث."),
    action: L("The car drives, but that protection is disabled. Get it fixed soon.", "السيارة بتمشي، بس الحماية معطّلة. صلّحها بأقرب وقت."),
  },
  {
    id: "power-steering",
    title: L("Power steering", "الدركسيون المعزّز"),
    subtitle: "Power Steering",
    severity: "critical",
    summary: L("Loss of steering assistance. The wheel becomes very heavy without warning.", "فقدان تعزيز التوجيه. الدركسيون بيصير ثقيل جداً فجأة."),
    action: L("Grip the wheel firmly, slow down, and stop somewhere safe.", "امسك الدركسيون بقوة، خفّف السرعة، واوقف بمكان آمن."),
  },
  {
    id: "check-engine",
    title: L("Check engine", "فحص المحرك"),
    subtitle: "Check Engine",
    severity: "warning",
    summary: L("An engine or emissions fault. Causes range from a loose fuel cap to a failed sensor.", "خلل بالمحرك أو نظام العادم. الأسباب كتيرة — من غطا البنزين المفكوك لحساس معطّل."),
    action: L("Tighten the fuel cap first. If it stays on, get the codes read with an OBD scanner.", "شدّ غطا خزان البنزين وشوف. إذا ضلت، افحص بجهاز OBD."),
  },
  {
    id: "check-engine-flashing",
    title: L("Check engine — flashing", "فحص المحرك (وامضة)"),
    subtitle: "Check Engine — Flashing",
    severity: "critical",
    summary: L("A flashing light means a misfire is destroying your catalytic converter right now.", "اللمبة الوامضة تعني احتراق ناقص عم يدمّر الحساس الحفاز الآن."),
    action: L("Slow down and stop. Flashing is far more serious than steady.", "خفّف السرعة واوقف. الوامضة أخطر بكتير من الثابتة."),
  },
  {
    id: "transmission",
    title: L("Transmission temperature", "حرارة الجير"),
    subtitle: "Transmission Temperature",
    severity: "critical",
    summary: L("The transmission is overheating. Driving on shortens its life considerably.", "ناقل الحركة سخن. السواقة بهالحالة بتقصّر عمر الجير كتير."),
    action: L("Pull over and idle in neutral to let the transmission cool.", "اوقف وخلّي المحرك دائر بالوضع المحايد لتبريد الجير."),
  },
  {
    id: "abs",
    title: L("ABS", "نظام ABS"),
    subtitle: "Anti-lock Braking",
    severity: "warning",
    summary: L("Anti-lock braking is disabled. Normal brakes still work, but without ABS.", "نظام منع انغلاق الفرامل معطّل. الفرامل العادية بتشتغل بس بدون ABS."),
    action: L("Drive carefully and leave more distance, especially in the wet. Get it fixed soon.", "سوق بحذر وباعد المسافة، خصوصاً على طريق مبلول. صلّحها قريباً."),
  },
  {
    id: "tpms",
    title: L("Tire pressure", "ضغط الإطارات"),
    subtitle: "Tire Pressure (TPMS)",
    severity: "warning",
    summary: L("One or more tyres is under-inflated. It raises fuel use and blowout risk.", "ضغط إطار أو أكثر واطي. بيزيد استهلاك البنزين وخطر الانفجار."),
    action: L("Check all four and the spare, and inflate to the pressure on the driver's door label.", "افحص الإطارات الأربعة والاحتياطي واملاهم للضغط المكتوب على باب السائق."),
  },
  {
    id: "traction",
    title: L("Traction control", "التحكم بالجر"),
    subtitle: "Traction Control",
    severity: "info",
    summary: L("Flashing means it's actively working because a wheel is slipping. Steady means it's disabled.", "لو بتومض: النظام شغال هلق لأن الإطارات عم تزحلق. لو ثابتة: النظام معطّل."),
    action: L("Flashing is normal — ease off. Steady needs checking.", "الوامضة طبيعية — خفّف السرعة. الثابتة بتحتاج فحص."),
  },
  {
    id: "esp",
    title: L("Stability control", "الثبات الإلكتروني"),
    subtitle: "ESP / Stability Control",
    severity: "warning",
    summary: L("Stability control is off or faulty. You lose that help if the car starts to slide.", "نظام الثبات مطفي أو فيه خلل. السيارة بتفقد المساعدة عند الانزلاق."),
    action: L("Check you haven't pressed the ESP OFF button. If not, get it looked at.", "شوف إذا ضغطت زر ESP OFF بالغلط. إذا لأ، افحصها."),
  },
  {
    id: "glow-plug",
    title: L("Glow plugs (diesel)", "شمعات التسخين (ديزل)"),
    subtitle: "Glow Plug — Diesel",
    severity: "info",
    summary: L("Normal on a cold start — it goes out as things warm up. If it keeps flashing, there's a fault.", "طبيعية عند التشغيل البارد — بتنطفي لما تسخن. لو ضلت وامضة، في خلل."),
    action: L("Wait for it to go out before cranking. If it keeps flashing, have the plugs checked.", "استنى تنطفي قبل ما تدير المحرك. لو ضلت وامضة، افحص الشمعات."),
  },
  {
    id: "dpf",
    title: L("DPF filter (diesel)", "فلتر الجزيئات (ديزل)"),
    subtitle: "DPF Filter",
    severity: "warning",
    summary: L("The diesel particulate filter is clogged, usually from too many short trips.", "فلتر عادم الديزل متسكّر — عادةً بسبب كثرة السواقة القصيرة."),
    action: L("Drive 20 minutes at steady speed on a motorway to let it regenerate.", "سوق على سرعة ثابتة ٢٠ دقيقة على طريق سريع لتنظيف الفلتر."),
  },
  {
    id: "adblue",
    title: L("AdBlue / DEF", "سائل AdBlue"),
    subtitle: "AdBlue / DEF",
    severity: "warning",
    summary: L("Exhaust fluid is low or empty. The car may refuse to start once it runs dry.", "سائل معالجة العادم خلص أو قارب يخلص. السيارة ممكن ترفض تشتغل إذا فضي."),
    action: L("Top up AdBlue before it empties completely.", "عبّي AdBlue قبل ما يخلص تماماً."),
  },
  {
    id: "epb",
    title: L("Electronic parking brake", "الفرامل اليدوية الإلكترونية"),
    subtitle: "Electronic Parking Brake",
    severity: "warning",
    summary: L("A fault in the electronic parking brake, or it's still engaged.", "خلل بالفرامل اليدوية الإلكترونية أو إنها مرفوعة."),
    action: L("Try releasing and re-applying it. If it persists, fix it before parking on a slope.", "جرّب تنزّلها وترفعها. إذا ضلت، صلّحها قبل ما توقف بمنحدر."),
  },
  {
    id: "water-in-fuel",
    title: L("Water in fuel", "ماء بالوقود"),
    subtitle: "Water in Fuel",
    severity: "warning",
    summary: L("Water has collected in the diesel filter. It can destroy the fuel pump.", "تجمّع ماء بفلتر الديزل. ممكن يتلف مضخة الوقود."),
    action: L("Drain the fuel filter or get to a garage soon.", "صرّف فلتر الوقود أو روح على الورشة قريباً."),
  },
  {
    id: "catalytic",
    title: L("Catalytic converter", "الحساس الحفاز"),
    subtitle: "Catalytic Converter",
    severity: "warning",
    summary: L("The catalytic converter is overheating or no longer working properly.", "الحساس الحفاز سخن أو ما عاد يشتغل صح."),
    action: L("Ease off the engine and get it checked — the part is expensive to replace.", "خفّف الحمل على المحرك وافحص — القطعة غالية إذا تلفت."),
  },
  {
    id: "service",
    title: L("Service due", "موعد الصيانة"),
    subtitle: "Service Due",
    severity: "info",
    summary: L("You've reached the scheduled service interval.", "وصلت مسافة أو مدة الصيانة الدورية."),
    action: L("Book an oil change and service.", "احجز موعد تغيير زيت وصيانة."),
  },
  {
    id: "oil-level",
    title: L("Oil level", "مستوى الزيت"),
    subtitle: "Oil Level",
    severity: "warning",
    summary: L("Oil level is low — different from the red oil pressure warning.", "منسوب الزيت واطي — غير عن لمبة ضغط الزيت الحمرا."),
    action: L("Check the dipstick and top up with the correct grade.", "افحص بالمقياس وضيف زيت من النوع المناسب."),
  },
  {
    id: "fuel-low",
    title: L("Low fuel", "الوقود شارف يخلص"),
    subtitle: "Low Fuel",
    severity: "info",
    summary: L("Usually 50–80 km of range left, depending on the car.", "باقي عادةً ٥٠–٨٠ كم حسب السيارة."),
    action: L("Fill up soon — running near empty wears the fuel pump.", "عبّي قريباً — السواقة على خزان فاضي بتضر مضخة البنزين."),
  },
  {
    id: "washer",
    title: L("Washer fluid", "ماء المساحات"),
    subtitle: "Washer Fluid",
    severity: "info",
    summary: L("The windscreen washer reservoir is empty.", "خزان ماء غسيل الزجاج فاضي."),
    action: L("Top it up.", "عبّي الخزان."),
  },
  {
    id: "door-ajar",
    title: L("Door ajar", "باب مفتوح"),
    subtitle: "Door Ajar",
    severity: "warning",
    summary: L("A door, boot or bonnet isn't properly latched.", "باب أو صندوق أو غطا محرك مش مسكّر صح."),
    action: L("Stop and close it — dangerous at speed.", "اوقف وسكّر الباب — خطير على السرعات العالية."),
  },
  {
    id: "seatbelt",
    title: L("Seat belt", "حزام الأمان"),
    subtitle: "Seat Belt",
    severity: "warning",
    summary: L("The driver's or a passenger's belt isn't fastened.", "حزام السائق أو أحد الركاب مش مربوط."),
    action: L("Fasten the belt.", "اربط الحزام."),
  },
  {
    id: "immobilizer",
    title: L("Immobiliser", "نظام الحماية"),
    subtitle: "Immobilizer / Security",
    severity: "warning",
    summary: L("The car can't recognise the key. The key battery may be flat.", "السيارة ما تعرّفت على المفتاح. ممكن بطارية المفتاح فاضية."),
    action: L("Hold the key against the start button, or replace its battery.", "قرّب المفتاح من زر التشغيل أو بدّل بطاريته."),
  },
  {
    id: "key-battery",
    title: L("Key fob battery", "بطارية المفتاح"),
    subtitle: "Key Fob Battery",
    severity: "info",
    summary: L("The key fob battery is nearly flat.", "بطارية الريموت شارفت تخلص."),
    action: L("Replace it before you get stranded.", "بدّل البطارية قبل ما تعلق برّا."),
  },
  {
    id: "high-beam",
    title: L("High beam", "الأضواء العالية"),
    subtitle: "High Beam",
    severity: "info",
    summary: L("Main beam is on — usually shown in blue.", "الأضواء العالية شغالة (أزرق عادةً)."),
    action: L("Dip them for oncoming traffic — they dazzle other drivers.", "طفّيها عند مقابلة سيارات — بتعمي السائق المقابل."),
  },
  {
    id: "fog",
    title: L("Fog lights", "أضواء الضباب"),
    subtitle: "Fog Lights",
    severity: "info",
    summary: L("Front or rear fog lights are on.", "أضواء الضباب الأمامية أو الخلفية شغالة."),
    action: L("Switch them off in clear weather — rear fogs dazzle the car behind.", "طفّيها بالجو الصافي — الخلفية بتزعج اللي وراك."),
  },
  {
    id: "cruise",
    title: L("Cruise control", "مثبّت السرعة"),
    subtitle: "Cruise Control",
    severity: "info",
    summary: L("Cruise control is engaged.", "مثبّت السرعة مفعّل."),
    action: L("Status only. Braking cancels it.", "معلومة فقط. الفرملة بتلغيه."),
  },
  {
    id: "lane-departure",
    title: L("Lane departure", "تحذير مغادرة المسار"),
    subtitle: "Lane Departure",
    severity: "info",
    summary: L("The system noticed you drifting out of your lane without indicating.", "النظام لاحظ إنك خرجت عن مسارك بدون إشارة."),
    action: L("Status only — but take a break if it repeats; you may be tired.", "معلومة فقط — بس خد بريك إذا تكررت، ممكن تكون تعبان."),
  },
  {
    id: "master-warning",
    title: L("Master warning", "التحذير العام"),
    subtitle: "Master Warning",
    severity: "warning",
    summary: L("A general warning — the detail appears on the instrument display.", "تحذير عام — التفاصيل بتطلع على شاشة العدادات."),
    action: L("Read the message on the display to find the real cause.", "اقرأ الرسالة على الشاشة لتعرف السبب الحقيقي."),
  },
];
