import { L } from "../i18n";
import type { ProgramPack, ProgramItem, Session } from "./types";

/* A 4-week obedience course built on positive reinforcement.
 *
 * Sessions are short on purpose — a dog's useful attention span is minutes,
 * not an hour, and the single most common reason home training fails is
 * sessions that run long and end in frustration. Every drill therefore caps
 * at a few minutes and ends while the dog is still winning.
 *
 * The `mistakes` list on each drill is what separates this from a video: it
 * names the handler error that silently teaches the dog the wrong thing.
 */

const d = (
  id: string,
  name: { en: string; ar: string },
  seconds: number,
  restSeconds: number,
  cues: { en: string; ar: string }[],
  mistakes: { en: string; ar: string }[],
): ProgramItem => ({ id, name, seconds, restSeconds, cues, mistakes });

const FOUNDATION = [
  d("name", L("Name recognition", "الاستجابة للاسم"), 120, 30,
    [L("Say his name once, in a bright tone", "قول اسمه مرة وحدة بصوت مرح"),
     L("The moment he looks at you, mark it and treat immediately", "أول ما يلتفت لك — قول 'ممتاز' وأعطيه مكافأة فوراً"),
     L("Repeat 10 times from varying distances", "كرّر ١٠ مرات بمسافات مختلفة"),
     L("End while he's still keen", "خلص التمرين وهو لسه متحمس")],
    [L("Repeating his name over and over — it teaches him to tune it out", "تكرار الاسم مرات ورا بعض — بيعلّمه يتجاهله"),
     L("Using his name to scold — it turns his name into a bad signal", "استخدام اسمه بالتوبيخ — بيصير الاسم إشارة سلبية"),
     L("A late treat — it has to land within two seconds", "المكافأة المتأخرة — لازم خلال ثانيتين من الفعل")]),
  d("marker", L("Marker word", "كلمة التمييز"), 90, 30,
    [L("Pick one fixed word — \"yes\" — or a clicker", "اختار كلمة وحدة ثابتة: 'ممتاز' أو صوت الكلِكر"),
     L("Say it and treat instantly, 15 times", "قولها وأعطي مكافأة فوراً، ١٥ مرة"),
     L("The goal is for the word alone to light him up", "الهدف: الكلمة لحالها تصير تفرّحه"),
     L("This underpins every drill that follows", "هاي أساس كل التمارين اللي بعدها")],
    [L("Changing the word each time", "تغيير الكلمة كل مرة"), L("Saying the marker without a treat early on — it loses its meaning", "قول الكلمة بدون مكافأة بالبداية — بتفقد معناها")]),
  d("eye-contact", L("Focus / watch me", "التواصل البصري"), 120, 30,
    [L("Hold a treat near your eye", "امسك مكافأة قريب من عينك"),
     L("The moment he gives you a glance, mark and reward", "أول ما يعطيك نظرة — ميّز وكافئ"),
     L("Build the hold gradually — one second, two, five", "زوّد المدة تدريجياً: ثانية، ثانيتين، خمسة"),
     L("Then try it with nothing in your hand", "بعدين جرّب بدون مكافأة باليد")],
    [L("Forcing his head round with your hand", "إجبار رأسه بالإيد"), L("Long, direct staring — some dogs read it as a threat", "التحديق بعينه بشكل مباشر وطويل — بعض الكلاب بتحسه تهديد")]),
];

const CORE_COMMANDS = [
  d("sit", L("Sit", "الجلوس"), 150, 40,
    [L("Hold a treat above his nose and move it up and back", "امسك المكافأة فوق أنفه ومرّرها لفوق ولورا"),
     L("His head lifts and his rear lowers on its own", "رأسه بيرتفع ومؤخرته بتنزل طبيعياً"),
     L("The moment he sits, mark and reward", "أول ما يقعد — ميّز وكافئ"),
     L("Add the word \"sit\" once he has the movement, not before", "ضيف كلمة 'اجلس' بعد ما يتقن الحركة، مش قبل")],
    [L("Pushing his rear down — it creates resistance and strains the hips", "الضغط على مؤخرته باليد — بيخلق مقاومة وبيأذي الورك"),
     L("Naming the cue before he knows the behaviour — the word ends up meaningless", "قول الأمر قبل ما يتعلم الحركة — بيصير الأمر بلا معنى"),
     L("Holding the treat too high — he jumps instead of sitting", "رفع المكافأة عالي كتير — بيقفز بدل ما يقعد")]),
  d("down", L("Down", "الانبطاح"), 150, 40,
    [L("From a sit, lower the treat to the floor between his paws", "من وضع الجلوس، نزّل المكافأة للأرض بين يديه"),
     L("Draw it slowly forward", "سحّبها للأمام ببطء"),
     L("The moment he lies down, mark and reward", "أول ما ينبطح — ميّز وكافئ"),
     L("Add the word \"down\" once he's fluent", "ضيف كلمة 'انبطح' بعد الإتقان")],
    [L("Moving the lure too fast — he stands and follows your hand", "السحب السريع — بيوقف ويتبع اليد"),
     L("Working on a slippery or cold floor — he'll refuse to lie down", "التمرين على أرضية زحلقة أو باردة — بيرفض ينبطح")]),
  d("stay", L("Stay", "الثبات"), 180, 45,
    [L("From a sit, show an open palm and say \"stay\"", "من وضع الجلوس، افتح كفك أمامه وقول 'ثابت'"),
     L("Wait one second only, then mark and reward", "استنى ثانية وحدة بس، بعدين ميّز وكافئ"),
     L("Add a second per success — one, two, five", "زوّد ثانية كل نجاح — ثانية، ثانيتين، خمسة"),
     L("You go back to him — never call him out of a stay", "ارجع أنت له — لا تناديه ليكسر الثبات")],
    [L("Adding duration too fast — the most common reason stay falls apart", "الزيادة السريعة بالمدة — أشهر سبب للفشل"),
     L("Recalling him out of a stay — it wrecks both cues at once", "مناداته من مكان الثبات — بيدمّر أمر النداء والثبات مع بعض"),
     L("Training when he's wound up or straight after play", "التمرين وهو متحمس أو بعد لعب")]),
  d("come", L("Recall", "النداء"), 180, 45,
    [L("Step two paces away and drop to one knee", "ابعد عنه خطوتين واجلس على ركبتك"),
     L("Call his name plus \"come\" in a genuinely happy voice", "نادي اسمه + 'تعال' بصوت مفرح جداً"),
     L("Start cheering the instant he moves toward you", "أول ما يتحرك باتجاهك ابدأ تشجّعه"),
     L("When he arrives: a jackpot and a party — bigger than any other drill", "لما يوصل: مكافأة كبيرة واحتفال — أكبر من أي تمرين تاني")],
    [L("Calling him for something he hates (bath, nail trim) — he learns to ignore the recall", "مناداته لشي بيكرهه (حمام، قص أظافر) — بيتعلم يتجاهل النداء"),
     L("Scolding him for arriving late — he learns that coming back is punished", "توبيخه لما يجي متأخر — بيتعلم إن الجيّة عقاب"),
     L("Using the recall when you can't follow through", "استخدام النداء وأنت ما بتقدر تفرضه")]),
  d("leave-it", L("Leave it", "اتركه"), 150, 40,
    [L("Put a treat in your palm and close your hand", "حط مكافأة بكفك واقفل يدك"),
     L("Let him sniff and work at it — don't move your hand", "خلّيه يشم ويحاول — لا تحرك يدك"),
     L("The instant his nose backs off, mark and reward from your other hand", "أول ما يبعد أنفه ولو لحظة — ميّز وكافئ من اليد التانية"),
     L("Always reward from the other hand, never the one he was working on", "المكافأة دايماً من اليد التانية، مش اللي بيحاول عليها")],
    [L("Rewarding from the same hand — he learns that pestering works", "المكافأة من نفس اليد — بيتعلم إن الإلحاح بينفع"),
     L("Saying \"no\" sharply instead of marking the right choice", "قول 'لا' بغضب بدل تمييز السلوك الصح")]),
];

const REAL_WORLD = [
  d("loose-leash", L("Loose leash walking", "المشي بدون شد"), 240, 60,
    [L("Start indoors or in the garden, not on the street", "ابدأ بالبيت أو الحديقة، مش بالشارع"),
     L("Walk two steps — if the leash is slack, mark and reward", "امشِ خطوتين — إذا الرباط مرتخي، ميّز وكافئ"),
     L("The moment he pulls, stop dead and don't move", "أول ما يشد: اوقف تماماً ولا تتحرك"),
     L("Wait for the leash to go slack, then carry on", "استنى لحد ما يرتخي الرباط، بعدين كمّل")],
    [L("Pulling back — it triggers his opposition reflex and he pulls harder", "السحب المقابل — بيفعّل غريزة الشد عند الكلب"),
     L("Walking on while he pulls — it teaches him pulling works", "المشي المستمر رغم الشد — بيعلّمه إن الشد بينفع"),
     L("Starting somewhere full of distractions", "البدء بمكان مليان مشتتات")]),
  d("greeting", L("Calm greeting", "السلام بدون نطّ"), 180, 45,
    [L("The moment he jumps, turn away and ignore him completely", "أول ما ينط عليك — استدر وتجاهله تماماً"),
     L("The instant all four paws touch down, give him attention and reward", "أول ما تلامس أربع أرجله الأرض — انتبهله وكافئ"),
     L("Repeat with everyone in the household the same way", "كرّر مع أفراد البيت بنفس الطريقة"),
     L("Consistency across everyone is what makes it stick", "الاتساق بين كل الناس هو المفتاح")],
    [L("Pushing him off or shouting — any attention, even negative, rewards the jump", "دفعه أو الصراخ — أي انتباه (حتى السلبي) بيكافئ النط"),
     L("One person allowing it undoes everyone else's work", "شخص واحد بالبيت يسمح بالنط — بيلغي شغل الجميع")]),
  d("crate", L("Crate / safe place", "القفص أو المكان الآمن"), 240, 60,
    [L("Toss a treat inside and leave the door open", "ارمِ مكافأة جوا القفص وخلّي الباب مفتوح"),
     L("Never close the door in the first sessions", "لا تسكّر الباب أول مرات أبداً"),
     L("When he goes in on his own, mark and reward", "لما يدخل بإرادته — ميّز وكافئ"),
     L("Build up slowly, closing the door for seconds at first", "زوّد المدة تدريجياً وسكّر الباب لثواني بس")],
    [L("Using the crate as punishment — it becomes a place he dreads", "استخدام القفص كعقاب — بيصير مكان مكروه"),
     L("Closing the door too soon", "تسكير الباب بسرعة"), L("Letting him cry for a long stretch early on", "تركه يبكي لفترة طويلة أول مرة")]),
  d("alone", L("Alone time", "البقاء لحاله"), 180, 45,
    [L("Leave the room for 5 seconds and return calmly", "اطلع من الغرفة ٥ ثواني وارجع بهدوء"),
     L("No dramatic goodbye and no big reunion", "لا تعمل وداع درامي ولا ترحيب صاخب"),
     L("Build gradually — 5 seconds, 30, a minute", "زوّد المدة تدريجياً: ٥ ثواني، ٣٠، دقيقة"),
     L("Give him a food toy before you go", "أعطيه لعبة فيها أكل قبل ما تطلع")],
    [L("A drawn-out goodbye — it raises his anxiety", "الوداع الطويل — بيرفع قلقه"),
     L("Returning while he's crying — he learns crying brings you back", "الرجوع لما يكون عم يبكي — بيتعلم إن البكاء بيرجّعك")]),
  d("barking", L("Reduce barking", "تقليل النباح"), 180, 45,
    [L("Identify the trigger first — doorbell, people, dogs outside", "حدّد المحفّز أول: جرس، ناس، كلاب برّا"),
     L("The instant he goes quiet, mark and reward immediately", "أول ما يسكت للحظة — ميّز وكافئ فوراً"),
     L("Teach a replacement — going to his mat instead of barking", "علّمه سلوك بديل: يروح لمكانه بدل ما ينبح"),
     L("Reduce his exposure to the trigger at first", "قلّل تعرّضه للمحفّز بالبداية")],
    [L("Shouting at him — to him you're barking along", "الصراخ عليه — بيحسه بينبح معه"),
     L("Rewarding right after a bark instead of after silence", "المكافأة بعد النباح مباشرة بدل بعد الصمت")]),
  d("impulse", L("Impulse control", "ضبط الاندفاع"), 150, 40,
    [L("Set the food bowl down and have him wait", "حط صحن الأكل وخلّيه ينتظر"),
     L("If he moves, lift the bowl calmly", "لو تحرك، ارفع الصحن بهدوء"),
     L("When he sits and waits, put it down and release him", "لما يقعد وينتظر — نزّل الصحن واسمحله"),
     L("Extend the wait gradually", "زوّد وقت الانتظار تدريجياً")],
    [L("Shouting or pushing", "الصراخ أو الدفع"), L("Giving in when he pesters — he learns pestering works", "التنازل لما يلح — بيتعلم إن الإلحاح بينجح")]),
];

const s = (
  id: string,
  title: { en: string; ar: string },
  subtitle: { en: string; ar: string },
  minutes: number,
  level: Session["level"],
  focus: { en: string; ar: string },
  items: ProgramItem[],
): Session => ({ id, title, subtitle, minutes, level, focus, items });

export const DOGTRAIN_SESSIONS: Session[] = [
  s("d1", L("Foundations: name and marker", "الأساس: الاسم والتمييز"), L("Before any cue — he has to hear you and know the success signal", "قبل أي أمر — لازم يسمعك ويفهم إشارة النجاح"), 6, "beginner", L("Foundations", "الأساسيات"),
    [FOUNDATION[1], FOUNDATION[0]]),
  s("d2", L("Focus", "التركيز"), L("He offers you attention without being asked", "يعطيك انتباهه بدون ما تطلب"), 6, "beginner", L("Foundations", "الأساسيات"),
    [FOUNDATION[0], FOUNDATION[2]]),
  s("d3", L("Sit", "الجلوس"), L("The first real cue", "أول أمر حقيقي"), 7, "beginner", L("Cues", "الأوامر"),
    [FOUNDATION[1], CORE_COMMANDS[0]]),
  s("d4", L("Down", "الانبطاح"), L("A little harder — patience matters", "أصعب شوي — الصبر مهم"), 7, "beginner", L("Cues", "الأوامر"),
    [CORE_COMMANDS[0], CORE_COMMANDS[1]]),
  s("d5", L("Stay", "الثبات"), L("The most important cue for safety", "أهم أمر للسلامة"), 8, "intermediate", L("Cues", "الأوامر"),
    [CORE_COMMANDS[0], CORE_COMMANDS[2]]),
  s("d6", L("Recall", "النداء"), L("The cue that can save his life", "الأمر اللي ممكن ينقذ حياته"), 8, "intermediate", L("Cues", "الأوامر"),
    [FOUNDATION[0], CORE_COMMANDS[3]]),
  s("d7", L("Leave it", "اتركه"), L("Stops him eating something dangerous off the ground", "بيمنعه ياكل شي خطر من الأرض"), 7, "intermediate", L("Cues", "الأوامر"),
    [CORE_COMMANDS[4], CORE_COMMANDS[2]]),
  s("d8", L("Loose leash walking", "المشي بدون شد"), L("The single most common complaint from dog owners", "أكثر شكوى عند أصحاب الكلاب"), 9, "intermediate", L("Everyday life", "الحياة اليومية"),
    [FOUNDATION[2], REAL_WORLD[0]]),
  s("d9", L("Calm greeting", "السلام بدون نطّ"), L("When guests arrive", "لما يجي ضيوف"), 8, "intermediate", L("Everyday life", "الحياة اليومية"),
    [REAL_WORLD[1], CORE_COMMANDS[0]]),
  s("d10", L("Impulse control", "ضبط الاندفاع"), L("Patience at the bowl and the door", "الصبر عند الأكل والباب"), 7, "intermediate", L("Everyday life", "الحياة اليومية"),
    [REAL_WORLD[5], CORE_COMMANDS[2]]),
  s("d11", L("Alone time", "البقاء لحاله"), L("Easing separation anxiety, step by step", "علاج قلق الانفصال تدريجياً"), 8, "advanced", L("Behaviour", "السلوك"),
    [REAL_WORLD[2], REAL_WORLD[3]]),
  s("d12", L("Reduce barking", "تقليل النباح"), L("With a replacement behaviour, not shouting", "بالسلوك البديل مش بالصراخ"), 8, "advanced", L("Behaviour", "السلوك"),
    [REAL_WORLD[4], CORE_COMMANDS[2]]),
];

export const dogtrain: ProgramPack = {
  kind: "program",
  id: "dogtrain",
  appName: L("Dog Training", "تدريب الكلاب"),
  tagline: L("Train your dog yourself — short daily sessions, no shouting, no punishment", "درّب كلبك بنفسك — جلسات قصيرة كل يوم، بدون صراخ ولا عقاب"),
  accent: "#5A8DEE",
  nouns: { session: L("session", "جلسة"), item: L("drill", "تمرين"), plan: L("programme", "البرنامج") },
  disclaimer:
    L("This is a general positive-reinforcement programme, not a substitute for a qualified trainer or a vet. Aggression, severe fear, or any sudden change in behaviour needs professional assessment — pain or illness can be the cause.", "هذا برنامج تدريب عام مبني على التعزيز الإيجابي، وليس بديلاً عن مدرب مختص أو طبيب بيطري. السلوك العدواني أو الخوف الشديد أو أي تغيّر مفاجئ بالسلوك بيحتاج تقييم مختص — وممكن يكون سببه ألم أو مرض."),
  onboarding: [
    { key: "age", question: L("How old is your dog?", "قديش عمر كلبك؟"),
      options: [L("Under 4 months", "أقل من ٤ شهور"), L("4 months to a year", "٤ شهور – سنة"), L("1 to 7 years", "سنة – ٧ سنين"), L("Over 7 years", "أكبر من ٧ سنين")] },
    { key: "problem", question: L("What bothers you most?", "شو أكثر شي بيزعجك؟"),
      options: [L("He pulls on the leash", "بيشد بالرباط"), L("He jumps on people", "بينط على الناس"), L("He won't come when called", "ما بيجي لما أناديه"), L("He barks a lot", "بينبح كتير"), L("He doesn't listen generally", "ما بيسمع الكلام عموماً")] },
    { key: "experience", question: L("How much training experience do you have?", "قديش خبرتك بتدريب الكلاب؟"),
      options: [L("This is my first dog", "أول كلب إلي"), L("I've trained a dog before", "دربت كلب قبل"), L("I'm fairly experienced", "عندي خبرة كويسة")] },
    { key: "time", question: L("How long can you give a day?", "قديش بتقدر تعطي باليوم؟"),
      options: [L("5 minutes", "٥ دقايق"), L("10 minutes", "١٠ دقايق"), L("15 minutes or more", "١٥ دقيقة أو أكثر")] },
  ],
  paywall: {
    headline: L("A trained dog in four weeks — ten minutes a day", "كلب مدرَّب بأربع أسابيع — عشر دقايق باليوم"),
    bullets: [
      L("12 sessions, from foundations to the hard behaviours", "١٢ جلسة مرتبة من الأساسيات للسلوك الصعب"),
      L("Every drill step by step, plus the mistakes that derail training", "كل تمرين بخطواته + الأخطاء اللي بتفشّل التدريب"),
      L("Positive reinforcement only — no shouting, no punishment", "تعزيز إيجابي فقط — بدون صراخ ولا عقاب"),
      L("A day streak — consistency is the whole game in training", "عدّاد أيام متواصلة — الاستمرارية هي كل شي بالتدريب"),
    ],
  },
  pricing: {
    entitlement: "pro",
    defaultProductId: "annual",
    products: [
      { id: "weekly", label: L("Weekly", "أسبوعي"), fallbackPrice: "$6.99", period: L("week", "أسبوع"), trialDays: 7 },
      { id: "annual", label: L("Yearly", "سنوي"), fallbackPrice: "$39.99", period: L("year", "سنة"), note: L("Under $0.77 a week", "أقل من $0.77 بالأسبوع"), badge: L("Best value", "الأوفر") },
    ],
  },
  plan: { weeks: 4, daysPerWeek: 3, promise: L("Four weeks, three sessions a week, 6 to 9 minutes", "أربع أسابيع، ثلاث جلسات بالأسبوع، من ٦ لـ ٩ دقايق") },
  sessions: DOGTRAIN_SESSIONS,
  tips: [
    L("Short beats long. Finish while he's still keen, not once he's bored.", "الجلسة القصيرة أفضل من الطويلة. خلّص وهو لسه متحمس، مش لما يمل."),
    L("Train before meals, not after — a hungry dog learns faster.", "درّبه قبل الأكل مش بعده — الجوعان بيتعلم أسرع."),
    L("The reward has to land within two seconds or he won't connect it to the behaviour.", "المكافأة لازم توصل خلال ثانيتين من السلوك، وإلا ما بيربط بينهم."),
    L("Everyone in the house has to use the same words and the same rules.", "كل الناس بالبيت لازم يستخدموا نفس الكلمات ونفس القواعد."),
    L("An off day is normal. Drop back a step and don't take it personally.", "لو تراجع بيوم، هاد طبيعي. رجّع خطوة ولا تزعل."),
    L("Mental work tires a dog more than running. Ten minutes of training equals half an hour's walk.", "التعب الذهني بيتعب الكلب أكثر من الجري. جلسة تدريب ١٠ دقايق = نص ساعة مشي."),
    L("Don't train while you're frustrated. He reads your mood instantly and shuts down.", "لا تدرّبه وأنت عصبان. بيحس بمزاجك فوراً وبيقفل."),
  ],
};
