import { L } from "../i18n";
import type { LibraryEntry } from "./types";

/**
 * 38 hallmarks used worldwide: fineness marks and their karat equivalents,
 * plus the plated and filled markings (GP, GF, HGE, RGP, vermeil) that are
 * the expensive mistake this app exists to prevent.
 */
export const GOLDSCAN_LIBRARY: LibraryEntry[] = [
  {
    id: "fine-999",
    title: L("Pure Gold", "ذهب صافي"),
    subtitle: "999",
    severity: "info",
    summary: L("99.9% gold — as pure as gold gets in commerce, sometimes stamped 999.9 or 24K. It is soft enough to mark with a fingernail, so you see it on bars, coins and thick Gulf and Asian chains, almost never on rings set with stones.", "ذهب صافي 99.9%، وهذا أعلى عيار موجود بالسوق، وأحياناً تلقاه مكتوب 999.9 أو 24K. طري لدرجة إن الظفر يأثر فيه، عشان كذا تلقاه بالسبايك والعملات والسلاسل الخليجية والهندية الثقيلة، ونادر يستخدمونه بخاتم فيه فصوص."),
    action: L("Price it straight off the day's gold rate by weight — there is no alloy to discount for. On a bar, match the serial number and refiner name against the refiner's own verification page, and weigh it: real 999 gold is very dense, so a bar that feels light for its size is not gold.", "احسب سعره من وزنه على سعر الذهب اليوم مباشرة، ما في خلطة تنقّص قيمته. وإذا سبيكة، طابق الرقم التسلسلي واسم المصفاة مع موقع الشركة نفسها، ووزنها كمان: الذهب 999 ثقيل جداً، وأي سبيكة تحسها خفيفة على حجمها مو ذهب."),
  },
  {
    id: "fine-995",
    title: L("Fine Gold (Bullion)", "ذهب فاين (سبايك)"),
    subtitle: "995",
    severity: "info",
    summary: L("99.5% gold, the minimum purity accepted for a recognised investment bar. In practice it behaves like 999 — the missing half percent is refining tolerance, not a cheaper alloy.", "ذهب 99.5%، وهذا أقل عيار مقبول بسبايك الاستثمار المعتمدة. عملياً هو نفس 999، والنص بالمية الناقصة فرق تصفية مو خلطة أرخص."),
    action: L("Value it at 0.995 of the spot price per gram. Keep the assay card and serial number with the bar — a bar sold without them fetches less on resale even when the metal is perfectly good.", "قيّمه على 0.995 من سعر الغرام اليوم. واحتفظ بشهادة الفحص والرقم التسلسلي مع السبيكة، لأن السبيكة بدونهم تنباع بأقل حتى لو المعدن سليم."),
  },
  {
    id: "fine-916",
    title: L("22 Karat Gold", "ذهب عيار 22"),
    subtitle: "916",
    severity: "info",
    summary: L("91.6% gold — the wedding and investment standard across the Gulf, India and Southeast Asia. Deep yellow, still soft, and it holds value close to bullion because there is so little alloy in it.", "ذهب 91.6%، وهذا عيار الزواج والاستثمار بالخليج والهند وشرق آسيا. لونه أصفر غامق، طري شوي، وقيمته قريبة من سعر الذهب الخام لأن الخلطة فيه قليلة."),
    action: L("Check the maths is (today's gold rate × 0.916 × grams) plus a separately stated making charge, and have the piece weighed in front of you. Keep the invoice — it is what gets you a fair buy-back price later.", "تأكد إن الحساب = سعر الذهب اليوم × 0.916 × عدد الغرامات + المصنعية مكتوبة لحالها، وخل الوزن يصير قدامك على الميزان. واحتفظ بالفاتورة لأنها اللي تضمن لك سعر عادل لما تبي تبيعه."),
  },
  {
    id: "fine-875",
    title: L("21 Karat Gold", "ذهب عيار 21"),
    subtitle: "875",
    severity: "info",
    summary: L("87.5% gold — the everyday Gulf standard, a little harder and less orange than 22K. The same number was also used on old Russian and Soviet silver, so a white-grey piece stamped 875 is silver, not gold.", "ذهب 87.5%، وهذا العيار الأكثر استخداماً بالخليج، أقوى شوي ولونه أفتح من عيار 22. ونفس الرقم كانوا يستخدمونه بروسيا على الفضة القديمة، فإذا القطعة لونها أبيض رمادي ومكتوب عليها 875 فهي فضة مو ذهب."),
    action: L("Buy it by weight exactly as you would 22K, and expect a lower making charge on machine-made chains than on handmade work. If the metal looks white or grey, treat 875 as a silver mark and price it as silver.", "اشتره بالوزن نفس طريقة عيار 22، وتوقع مصنعية أقل بالسلاسل المصنّعة بالمكينة مقارنة بالشغل اليدوي. وإذا لون المعدن أبيض، احسبها فضة وسعّرها فضة."),
  },
  {
    id: "fine-750",
    title: L("18 Karat Gold", "ذهب عيار 18"),
    subtitle: "750",
    severity: "info",
    summary: L("75% gold and 25% alloy — the standard for European and designer jewellery, and the lowest fineness most luxury houses will use. Hard enough to hold diamonds securely, which is why engagement rings live here.", "ذهب 75% و25% معادن ثانية، وهذا عيار المجوهرات الأوروبية والماركات، وأقل عيار تستخدمه أغلب الماركات الفخمة. قوي بما يكفي يمسك الألماس، عشان كذا خواتم الخطوبة غالباً منه."),
    action: L("Look for a maker's mark or assay mark beside the 750 — branded 18K rarely carries a bare number alone. Rose and white 18K are the same 75% gold; white gold is rhodium-plated and needs re-plating every year or two.", "دوّر على دمغة الشركة أو دمغة مكتب الفحص جنب الرقم 750، لأن الذهب الماركة نادر يجي برقم لحاله. والذهب الأبيض والوردي نفس النسبة، بس الأبيض مطلي روديوم ويحتاج إعادة طلاء كل سنة أو سنتين."),
  },
  {
    id: "fine-585",
    title: L("14 Karat Gold", "ذهب عيار 14"),
    subtitle: "585",
    severity: "info",
    summary: L("58.5% gold — the everyday standard in the US and much of Europe. Noticeably harder and paler than 18K and better for daily-wear rings and chains, but a little under 60% of its weight is actual gold.", "ذهب 58.5%، وهذا العيار الدارج بأمريكا وأوروبا. أقوى ولونه أفتح من عيار 18، ومناسب للبس اليومي، بس أقل من 60% من وزنه ذهب فعلي."),
    action: L("Price it at 0.585 of spot per gram, not at the headline gold price. If you may resell it, expect the buy-back to be calculated on that same fraction — so do not overpay for design on a thin 14K chain.", "سعّره على 0.585 من سعر الغرام مو على سعر الذهب الكامل. وإذا ناوي تبيعه بعدين، توقع إن الشرا منك يكون على نفس النسبة، فلا تدفع زيادة على تصميم سلسلة رفيعة عيار 14."),
  },
  {
    id: "fine-375",
    title: L("9 Karat Gold", "ذهب عيار 9"),
    subtitle: "375",
    severity: "info",
    summary: L("37.5% gold — the UK's entry-level standard, legal to sell as gold there but not in the US, where 10K is the floor. More base metal than gold, so it can dull slightly and is worth far less by weight than it looks.", "ذهب 37.5%، وهذا أدنى عيار مسموح ببريطانيا، وممنوع يتباع كذهب بأمريكا لأن الحد عندهم عيار 10. المعادن الثانية فيه أكثر من الذهب، فممكن يبهت لونه، وقيمته بالوزن أقل بكثير من شكله."),
    action: L("Expect roughly 40% of the gold value of a 22K piece of the same weight, and negotiate on that basis. It is a sensible buy for durable everyday jewellery and a poor one as a store of value.", "توقع تقريباً حوالي 40٪ من قيمة قطعة عيار 22 بنفس الوزن، واحسبه على هالأساس. حلو كذهب للبس اليومي، بس ما ينفع كاستثمار."),
  },
  {
    id: "karat-24k",
    title: L("24 Karat Stamp", "دمغة عيار 24"),
    subtitle: "24K",
    severity: "warning",
    summary: L("Claims pure gold, the same as 999. Real 24K is so soft it bends by hand and cannot hold a stone or a springy clasp — so a hard, rigid, cheaply priced '24K' ring or bracelet is the single most commonly faked stamp in jewellery.", "معناها ذهب صافي، نفس 999. الذهب الصافي طري لدرجة إنه ينثني باليد وما يمسك فص ولا مشبك ناشف، عشان كذا أي خاتم أو إسورة مكتوب عليها 24K وهي قاسية ورخيصة غالباً مضروبة — وهذي أكثر دمغة تتقلّد."),
    action: L("Have it tested before you pay, and read the stamp under a loupe for letters after the number — 24KGP or 24K HGE is plating. Genuine 24K sells by weight at close to spot; anything priced well below that is not 24K.", "افحصها قبل ما تدفع، وشوف الدمغة بعدسة مكبرة إذا فيها حروف بعد الرقم: 24KGP أو 24K HGE يعني مطلي. الذهب عيار 24 الأصلي ينباع بالوزن بسعر قريب من سعر السوق، وأي سعر أرخص بكثير يعني إنه مو 24."),
  },
  {
    id: "karat-22k",
    title: L("22 Karat Stamp", "دمغة عيار 22"),
    subtitle: "22K",
    severity: "info",
    summary: L("The written form of 916. It appears as 22K, 22KT or 22CT depending on the country, and all three mean the same 91.6% gold.", "هذي نفس 916 بس مكتوبة بالحروف، وتجي 22K أو 22KT أو 22CT حسب البلد، وكلها تعني 91.6% ذهب."),
    action: L("Make sure nothing follows the K — 22K GP and 22K GF are plated and filled, not solid. Once the stamp is clean, weigh it and price it exactly as 916.", "تأكد ما في حروف بعد الـ K، لأن 22K GP و22K GF مطلي وملبّس مو ذهب كامل. وبعدين وزنها وسعّرها زي 916."),
  },
  {
    id: "karat-21k",
    title: L("21 Karat Stamp", "دمغة عيار 21"),
    subtitle: "21K",
    severity: "info",
    summary: L("Equal to 875. Almost exclusively a Middle Eastern and North African standard — rarely seen in Europe or the US, where buy-back counters sometimes misprice it as 18K.", "تساوي 875، ومستخدمة بالشرق الأوسط وشمال أفريقيا بس، ونادر تشوفها بأوروبا وأمريكا — ومحلات الشرا هناك أحياناً تحسبها غلط على أساس عيار 18."),
    action: L("If you are selling outside the Gulf, ask the buyer to confirm they are paying at 0.875 and not 0.75. Point them to the 875 stamp if '21K' means nothing to them.", "إذا بتبيع برّه الخليج، اطلب منهم يأكدون إنهم يحسبون 0.875 مو 0.75. وإذا ما يعرفون معنى 21K، ورّيهم دمغة 875."),
  },
  {
    id: "karat-18k",
    title: L("18 Karat Stamp", "دمغة عيار 18"),
    subtitle: "18K",
    severity: "info",
    summary: L("Equal to 750. Also written 18KT, 18CT or 18KP — the 'KP' means karat plumb, a guarantee the piece is exactly 18K and not a hair under.", "تساوي 750، وتنكتب كمان 18KT أو 18CT أو 18KP، و«KP» تعني إن القطعة عيار 18 بالضبط مو ناقصة ولا شوي."),
    action: L("Check carefully for a letter after the number: 18KP is solid, 18KGP is plated brass. Under a loupe, the plated stamps are usually the ones crammed together or set slightly crooked.", "دقق زين إذا في حرف بعد الرقم: 18KP ذهب كامل، بس 18KGP نحاس مطلي. وبالعدسة المكبرة، دمغات المطلي غالباً مزحومة أو مايلة شوي."),
  },
  {
    id: "karat-14k",
    title: L("14 Karat Stamp", "دمغة عيار 14"),
    subtitle: "14K",
    severity: "info",
    summary: L("Equal to 585 and the most common gold stamp in the US. Hard-wearing, and the usual choice for chains, wedding bands and everyday rings.", "تساوي 585، وهي أكثر دمغة ذهب بأمريكا. قوية وتتحمل، وغالباً تستخدم بالسلاسل ومحابس الزواج والخواتم اليومية."),
    action: L("Read the whole stamp: '14K GF' and '1/20 14K' are gold-filled and worth a small fraction of solid 14K, and those extra characters are easy to miss without magnification.", "اقرا الدمغة كاملة: «14K GF» و«1/20 14K» يعني ملبّس ذهب وقيمته جزء بسيط من الذهب الكامل، والحروف الزيادة صعب تشوفها بدون عدسة."),
  },
  {
    id: "karat-10k",
    title: L("10 Karat Stamp", "دمغة عيار 10"),
    subtitle: "10K",
    severity: "info",
    summary: L("41.7% gold, sometimes stamped 417 — the legal minimum that can be called gold in the US. Mostly alloy, so it is hard, pale, and can react with skin that is sensitive to nickel or copper.", "41.7% ذهب (أحياناً مكتوبة 417)، وهذا أقل شي مسموح يتسمى ذهب بأمريكا. أغلبه معادن ثانية، فيطلع قاسي ولونه فاتح وممكن يهيّج البشرة الحساسة للنيكل أو النحاس."),
    action: L("Judge it as jewellery rather than as gold value — only about 40% of the weight is gold. If it marks your skin green or dark, that is the copper in the alloy, not proof of a fake.", "قيّمه كتصميم مو كقيمة ذهب، لأن حوالي 40% بس من وزنه ذهب. وإذا خلّى جلدك أخضر أو غامق، هذا من النحاس بالخلطة مو دليل إنه مضروب."),
  },
  {
    id: "karat-9k",
    title: L("9 Karat Stamp", "دمغة عيار 9"),
    subtitle: "9K",
    severity: "info",
    summary: L("Equal to 375 and common in the UK, Australia and South Africa. It is genuinely solid gold, but under 40% of it is gold, so resale value is low compared with the ticket price.", "تساوي 375، ومنتشرة ببريطانيا وأستراليا وجنوب أفريقيا. هو ذهب كامل فعلاً، بس أقل من 40% منه ذهب، فقيمته لما تبيعه تطلع قليلة مقارنة بسعر الشرا."),
    action: L("On a British piece it should sit alongside a full hallmark with 375 and an assay office mark; a lone '9K' with no hallmark is worth checking. Price it at about 40% of a 22K piece of the same weight.", "ببريطانيا لازم تكون جنبها دمغة رسمية فيها 375 وختم مكتب الفحص؛ وإذا القطعة بريطانية ومكتوب عليها 9K بس بدون دمغة، تستاهل فحص. واحسب قيمتها حوالي 40٪ من قطعة عيار 22 بنفس الوزن."),
  },
  {
    id: "plated-gp",
    title: L("Gold Plated", "مطلي ذهب"),
    subtitle: "GP",
    severity: "critical",
    summary: L("A microscopically thin layer of gold electroplated over brass, copper or steel — often under half a micron, a fraction of the thickness of a hair. The stamp usually reads 18KGP or 14KGP, and that karat number describes only the skin, not the piece.", "طبقة ذهب رفيعة جداً مطلية بالكهرباء فوق نحاس أو ستيل، غالباً أقل من نص مايكرون — يعني جزء بسيط من سمك الشعرة. والدمغة تجي 18KGP أو 14KGP، والرقم يوصف الطبقة الخارجية بس مو القطعة."),
    action: L("Never pay gold prices — a GP piece is worth its design, not its metal. Expect the plating to wear through at edges and clasps within months to a couple of years, and do not buy it as an investment or for resale.", "لا تدفع سعر ذهب أبداً؛ قيمة القطعة بتصميمها مو بمعدنها. وتوقع الطلا يروح من الأطراف والمشبك خلال شهور لسنتين، ولا تشتريها كاستثمار ولا عشان تبيعها بعدين."),
  },
  {
    id: "plated-gep",
    title: L("Gold Electroplate", "مطلي بالكهرباء"),
    subtitle: "GEP",
    severity: "critical",
    summary: L("Gold Electroplate — the same thing as GP written more formally, typically stamped 18K GEP. The gold present is measured in millionths of a metre and is worth cents.", "طلاء ذهب بالكهرباء — نفس GP بس مكتوبة بشكل رسمي أكثر، وغالباً تجي 18K GEP. وكمية الذهب فيها تقاس بأجزاء من المليون من المتر وقيمتها فلوس بسيطة."),
    action: L("Treat it exactly as you would GP: fashion jewellery with no metal value. Keep it away from perfume, chlorine and sweat if you want the finish to last, and never let a seller price it against the gold rate.", "تعامل معها زي GP بالضبط: إكسسوار، ما لها قيمة معدن. وابعدها عن العطر والكلور والعرق إذا تبي الطلا يعيش أطول، ولا تخلي البايع يسعّرها على سعر الذهب."),
  },
  {
    id: "plated-hge",
    title: L("Heavy Gold Electroplate", "طلاء ذهب ثقيل"),
    subtitle: "HGE",
    severity: "critical",
    summary: L("'Heavy' sounds reassuring but US FTC rules require a 2.5 micron minimum, ten times plain plating — HGE is still electroplating, just a slightly thicker layer, usually over a brass core. Very common on 1980s and 90s chains and on marketplace listings that read '18K HGE'.", "كلمة «ثقيل» تطمّن بس قوانين FTC الأمريكية بتفرض 2٫5 ميكرون كحد أدنى، عشر أضعاف الطلي العادي — HGE برضه طلاء بالكهرباء، بس طبقته أسمك شوي وغالباً فوق نحاس أصفر. منتشرة بسلاسل الثمانينات والتسعينات وبإعلانات النت المكتوب فيها «18K HGE»."),
    action: L("Price it as costume jewellery. If a seller quotes it as '18K', point at the HGE letters and walk away — when the plating wears through you will see yellow-brown brass at the high points.", "سعّرها إكسسوار. وإذا البايع قال لك «عيار 18»، أشّر له على حروف HGE وامشِ؛ لأن الطلا لما يروح بيبين النحاس الأصفر من الأطراف."),
  },
  {
    id: "filled-gf",
    title: L("Gold Filled", "ذهب ملبّس"),
    subtitle: "GF",
    severity: "critical",
    summary: L("A thick layer of real gold mechanically bonded to a brass core — far better than plating, typically 50 to 100 times thicker, and it can last decades. But it is still mostly brass: by law the gold must be at least 1/20 of the total weight, about 5%.", "طبقة ذهب حقيقية وسميكة ملصوقة ميكانيكياً على قلب نحاس — أحسن بكثير من المطلي، تقريباً 50 إلى 100 ضعف بالسماكة، وممكن تعيش سنين طويلة. بس بالنهاية أغلبها نحاس: القانون يطلب إن الذهب على الأقل 1/20 من الوزن، يعني حوالي 5%."),
    action: L("Buy it to wear, never for value — refiners pay almost nothing for gold-filled scrap. It is a good choice when you want the look of gold with real durability and none of the price.", "اشترها عشان تلبسها مو عشان قيمتها — محلات شرا الذهب تعطي عليها شي بسيط جداً أو ترفضها. وهي خيار كويس إذا تبي شكل الذهب ويتحمّل الاستخدام اليومي بدون سعر الذهب الكامل."),
  },
  {
    id: "filled-fraction",
    title: L("Gold-Filled Fraction", "كسر الذهب الملبّس"),
    subtitle: "1/20 12K GF",
    severity: "critical",
    summary: L("The fraction is the whole point: 1/20 means one twentieth of the item's weight is the gold layer, and 12K says that layer is itself only half pure. Net gold content is roughly 2.5% of the piece.", "الكسر هو بيت القصيد: 1/20 يعني واحد من عشرين من وزن القطعة هو طبقة الذهب، و12K يعني هالطبقة نفسها نصها ذهب بس. والنتيجة حوالي 2.5% من القطعة ذهب."),
    action: L("Do the arithmetic before believing any 'gold' claim — multiply the fraction by the karat. Insure and sell it as costume jewellery, and expect scrap buyers to decline it outright.", "اضرب الكسر بالعيار قبل ما تصدق أي كلام عن «ذهب». وسجّلها وبيعها كإكسسوار، وتوقع محلات شرا الذهب ما تستلمها أصلاً."),
  },
  {
    id: "plated-rgp",
    title: L("Rolled Gold Plate", "ذهب مدرفل"),
    subtitle: "RGP",
    severity: "critical",
    summary: L("Rolled Gold Plate — a gold sheet rolled onto base metal, thinner than gold-filled and often stamped as a fraction such as 1/40 12K RGP. Common on vintage watch cases and eyeglass frames.", "ذهب مدرفل على معدن رخيص، أرفع من الملبّس (GF)، وغالباً ينكتب ككسر مثل 1/40 12K RGP. تلاقيها كثير بعلب الساعات القديمة وإطارات النظارات."),
    action: L("Value it as a vintage object, not as gold — the metal is worth almost nothing. On a watch case, check the back and the lugs for worn patches showing grey or yellow base metal underneath.", "قيّمها كقطعة قديمة مو كذهب — المعدن ما له قيمة تذكر. وإذا ساعة، شوف الظهر والأطراف إذا فيها أماكن راح عنها الطلا وبان المعدن اللي تحت."),
  },
  {
    id: "vermeil",
    title: L("Gold Over Silver", "ذهب على فضة"),
    subtitle: "VERMEIL",
    severity: "critical",
    summary: L("Gold plating over a sterling silver base — sometimes stamped VERMEIL, very often just 925 on a gold-coloured piece. The real value is the silver underneath; in the US the gold layer must be at least 2.5 microns and 10K or better.", "طلاء ذهب فوق قاعدة فضة إسترليني — أحياناً مكتوب VERMEIL، وغالباً مكتوب 925 بس والقطعة لونها ذهبي. والقيمة الحقيقية بالفضة اللي تحت، وبأمريكا لازم طبقة الذهب 2.5 مايكرون على الأقل وعيار 10 فأعلى."),
    action: L("Any gold-coloured piece stamped 925 is plated — price it as silver plus a little. Do not polish it hard or use silver dip; both strip the gold layer and leave you with white silver.", "أي قطعة لونها ذهبي ومختوم عليها 925 فهي مطلية — سعّرها فضة وزيادة بسيطة. ولا تفركها بقوة ولا تحطها بسائل تلميع الفضة، لأن الاثنين يشيلون طبقة الذهب وتطلع لك فضة بيضا."),
  },
  {
    id: "gold-tone",
    title: L("Costume Gold Colour", "لون ذهبي فقط"),
    subtitle: "GOLD TONE",
    severity: "critical",
    summary: L("'Gold tone', 'gold finish', 'gold colour' and 'GT' all mean base metal that is merely the colour of gold — there may be no gold in it at all. The same applies to 'silver tone'.", "«Gold tone» و«gold finish» و«gold colour» و«GT» كلها تعني معدن رخيص بلون الذهب بس، وممكن ما فيه ذرة ذهب أصلاً. ونفس الشي ينطبق على «silver tone»."),
    action: L("Treat it as an accessory with zero metal value. If a listing uses these words in the description while showing '18K' in the title, believe the description, not the title.", "تعامل معها إكسسوار بدون أي قيمة معدن. وإذا الإعلان كاتب هالكلمات بالوصف وكاتب «18K» بالعنوان، صدّق الوصف مو العنوان."),
  },
  {
    id: "silver-925",
    title: L("Sterling Silver", "فضة إسترليني"),
    subtitle: "925",
    severity: "info",
    summary: L("92.5% silver with 7.5% copper — the world standard for silver jewellery. The copper is what makes it strong enough to wear, and also what makes it tarnish.", "92.5% فضة و7.5% نحاس، وهذا معيار الفضة بالعالم كله. والنحاس هو اللي يعطيها قوة تتلبس، وهو نفسه اللي يخليها تسوّد مع الوقت."),
    action: L("It is a normal, expected mark — buy with confidence and price by weight. Tarnish proves nothing on its own — plated pieces tarnish and clean up the same way; a piece that stays bright forever and feels light is probably plated.", "دمغة طبيعية ومتوقعة، فاشترها مطمئن وسعّرها بالوزن. والسواد ما بيثبت شي لحاله — المطلي بيسوّد وبينظّف بنفس الطريقة؛ أما القطعة اللي تظل لامعة للأبد وخفيفة بالوزن فغالباً مطلية."),
  },
  {
    id: "silver-sterling",
    title: L("Sterling Word Mark", "كلمة إسترليني"),
    subtitle: "STERLING",
    severity: "info",
    summary: L("The word form of 925, mostly on American and British pieces and sometimes shortened to STER or STG. It carries exactly the same 92.5% guarantee.", "نفس معنى 925 بس مكتوبة بالحروف، غالباً على القطع الأمريكية والبريطانية، وأحياناً تختصر STER أو STG، ونفس الضمان 92.5%."),
    action: L("Read the full stamp: 'STERLING SILVER PLATED' means plated base metal, and the word 'plated' is the one that counts. Check the spelling too — a misspelt sterling mark is a classic fake tell.", "اقرا الدمغة كاملة: «STERLING SILVER PLATED» تعني معدن رخيص مطلي، والكلمة المهمة هي «PLATED». ودقق بالإملاء كمان، لأن الأخطاء الإملائية بالدمغة من أوضح علامات التقليد."),
  },
  {
    id: "silver-800-835",
    title: L("Continental Silver", "فضة أوروبية"),
    subtitle: "800 / 835",
    severity: "info",
    summary: L("Lower-purity silver standards used in Germany, Italy, France and Eastern Europe — 80% and 83.5% silver. Common on older cutlery, trays and jewellery, and entirely legitimate.", "معايير فضة أقل نقاوة مستخدمة بألمانيا وإيطاليا وفرنسا وشرق أوروبا — 80% و83.5% فضة. تلاقيها كثير بأدوات المائدة والصواني والمجوهرات القديمة، وهي فضة نظامية 100%."),
    action: L("It is real silver, just less of it: price at 0.800 or 0.835 by weight rather than at 925 rates. An 800 stamp on a modern piece being sold as 'sterling' is a mismatch worth questioning.", "فضة أصلية بس بنسبة أقل: سعّرها على 0.800 أو 0.835 بالوزن مو بسعر 925. وإذا قطعة حديثة مكتوب عليها 800 والبايع يقول «إسترليني»، هذا تناقض يستاهل سؤال."),
  },
  {
    id: "silver-plate-epns",
    title: L("Silver Plated", "مطلي فضة"),
    subtitle: "EPNS",
    severity: "critical",
    summary: L("Electro-Plated Nickel Silver — a thin silver layer over a nickel-copper alloy that contains no silver at all. Marks like A1, EP, EPBM, 'silver on copper' and 'nickel silver' mean the same thing.", "«فضة نيكل مطلية بالكهرباء» — طبقة فضة رفيعة فوق خلطة نيكل ونحاس ما فيها ولا ذرة فضة. ونفس المعنى لدمغات A1 وEP وEPBM و«silver on copper» و«nickel silver»."),
    action: L("Never buy it as silver — scrap value is essentially nil. Do not over-polish plated trays and cutlery either; once you rub through to the coppery base metal it cannot be restored without re-plating.", "لا تشتريها كفضة أبداً، لأن قيمتها عند محلات الشرا تقريباً صفر. ولا تبالغ بتلميع الصواني والملاعق المطلية، لأنك إذا وصلت للنحاس اللي تحت ما ترجع إلا بإعادة طلاء."),
  },
  {
    id: "plat-word",
    title: L("Platinum", "بلاتين"),
    subtitle: "PLAT",
    severity: "info",
    summary: L("Platinum, at 950 fineness unless a lower number is stamped with it. Far denser than gold, so a platinum ring feels noticeably heavier than an identical white gold one, and it is naturally white — no rhodium plating needed.", "بلاتين، وعياره 950 إلا إذا كان مكتوب جنبه رقم أقل. كثافته أعلى بكثير من الذهب، فخاتم البلاتين تحسه أثقل من نفس الخاتم بالذهب الأبيض، ولونه أبيض طبيعي وما يحتاج طلاء روديوم."),
    action: L("Weigh it against a same-size white gold piece; the heft is the fastest honest check. If the stamp reads 'PLATINUM PLATED' or 'PLATINUM FINISH', that is a coating on base metal and nowhere near platinum in value.", "قارن وزنه بقطعة ذهب أبيض بنفس الحجم؛ الثقل أسرع فحص صادق. وإذا الدمغة مكتوب فيها «PLATINUM PLATED» أو «PLATINUM FINISH» فهذا طلاء على معدن رخيص وقيمته لا تقارن بالبلاتين."),
  },
  {
    id: "plat-pt950",
    title: L("950 Platinum", "بلاتين 950"),
    subtitle: "PT950 / 950",
    severity: "info",
    summary: L("95% platinum, the usual jewellery grade — also written 950 PLAT, PT.950, or just 950. PT900 and 900 PLAT (90%) are common on older American and Japanese pieces.", "95% بلاتين، وهو العيار المعتاد بالمجوهرات — وينكتب كمان 950 PLAT أو PT.950 أو 950 لحاله. وPT900 و900 PLAT (90%) منتشرة بالقطع الأمريكية واليابانية القديمة."),
    action: L("A bare '950' can be platinum or, rarely, high-grade silver — look for the PT or PLAT letters, and check the weight, since platinum is about twice as heavy as silver. If the piece feels light, have the jeweller test it.", "رقم 950 لحاله ممكن يكون بلاتين أو، بشكل نادر، فضة عالية النقاوة؛ فدوّر على حروف PT أو PLAT، وشوف الوزن — البلاتين تقريباً ضعف وزن الفضة. وإذا حسيت القطعة خفيفة، خل الصايغ يفحصها."),
  },
  {
    id: "uk-lion-passant",
    title: L("British Sterling Mark", "دمغة الأسد البريطانية"),
    subtitle: "Lion Passant",
    severity: "info",
    summary: L("A walking lion in profile, the British mark for 92.5% sterling silver, used for centuries. Scotland uses a thistle or a rampant lion instead, and a crown beside a karat number marked British gold until 1975.", "أسد ماشي من الجنب، وهذي الدمغة البريطانية للفضة الإسترليني 92.5%، ومستخدمة من قرون. وباسكتلندا يقابلها زهرة الشوك (thistle) أو أسد واقف، والتاج جنب رقم العيار كان يدمغ الذهب البريطاني لين 1975."),
    action: L("Expect it as part of a row of small stamps, not standing alone. Look for the town mark, date letter and maker's initials beside it — a lion with no companions on a modern piece deserves a second look.", "توقعها ضمن صف دمغات صغيرة، مو لحالها. ودوّر جنبها على دمغة المدينة وحرف السنة وحروف الصانع — أسد لحاله على قطعة حديثة يستاهل وقفة."),
  },
  {
    id: "uk-town-marks",
    title: L("UK Assay Office Marks", "دمغات مكاتب الفحص البريطانية"),
    subtitle: "Leopard's Head / Anchor / Rose / Castle",
    severity: "info",
    summary: L("The town mark says which assay office tested the piece: a leopard's head for London, an anchor for Birmingham, a rose for Sheffield, a three-towered castle for Edinburgh. Its presence means an independent laboratory verified the metal, not just the maker.", "دمغة المدينة تقول لك أي مكتب فحص فحص القطعة: راس نمر للندن، مرساة لبرمنغهام، وردة لشيفيلد، وقلعة بثلاثة أبراج لأدنبرة. ووجودها يعني إن مختبر مستقل فحص المعدن، مو بس الصانع اللي دمغ."),
    action: L("Use it to date and place a piece, and to trust the fineness figure stamped beside it. If something is described as 'fully hallmarked British' but carries only a number, it was never assayed in the UK.", "استخدمها عشان تعرف تاريخ القطعة ومصدرها، وتثق بالرقم اللي جنبها. وإذا أحد قال لك «مدموغة بريطانية كاملة» وما فيها إلا رقم، فهي ما مرت على مكتب فحص بريطاني."),
  },
  {
    id: "uk-sponsor-date",
    title: L("Maker and Year Marks", "دمغة الصانع والسنة"),
    subtitle: "Sponsor's Mark + Date Letter",
    severity: "info",
    summary: L("Two or three initials in a shaped shield identify the maker or importer, and a single letter in its own shield gives the year of assay. The letter's font and the shield's shape are what pin down the exact year.", "حرفين أو ثلاثة داخل شكل صغير تدل على الصانع أو المستورد، وحرف واحد لحاله داخل شكل ثاني يدل على سنة الفحص. ونوع الخط وشكل الإطار هما اللي يحددون السنة بالضبط."),
    action: L("Photograph the row of marks and match the date letter against the assay office's published chart — London, Birmingham and Sheffield all publish them free. On antiques this often matters more than the metal value.", "صوّر صف الدمغات وطابق حرف السنة مع جداول مكاتب الفحص المنشورة مجاناً للندن وبرمنغهام وشيفيلد. وبالقطع القديمة، هالمعلومة أحياناً أغلى من المعدن نفسه."),
  },
  {
    id: "swiss-assay",
    title: L("Swiss Assay Marks", "الدمغات السويسرية"),
    subtitle: "Helvetia Head / St Bernard",
    severity: "info",
    summary: L("A woman's head (Helvetia) marks Swiss gold and platinum cases, a St Bernard dog's head marks silver, and a squirrel or rampant bear appears on imported work. They sit beside a fineness number such as 750.", "راس امرأة (هلفيتيا) تدمغ الذهب والبلاتين السويسري، وراس كلب سان برنارد يدمغ الفضة، والسنجاب أو الدب يظهر على الشغل المستورد. وتجي دايماً جنب رقم عيار مثل 750."),
    action: L("On a watch, check the case back, the inside of the lugs and the movement — Swiss marks are tiny and often tucked out of sight. A 'Swiss' case with no assay mark and no fineness number is a claim, not a fact.", "بالساعات، شوف ظهر العلبة وداخل الأطراف والحركة نفسها — الدمغات السويسرية صغيرة ومخبّاة. وأي علبة ساعة «سويسرية» بدون دمغة ولا رقم عيار هي ادعاء مو إثبات."),
  },
  {
    id: "italy-maker",
    title: L("Italian Maker Mark", "دمغة إيطاليا"),
    subtitle: "750 + ★ 123 MI",
    severity: "info",
    summary: L("Italian pieces carry the fineness (750, 585, 925) plus a small oval holding a star, the workshop's registration number and a two-letter province code — VI for Vicenza, AR for Arezzo, MI for Milan. It identifies the workshop, not an independent assay.", "القطع الإيطالية تجي عليها نسبة العيار (750 أو 585 أو 925) مع بيضاوي صغير فيه نجمة ورقم تسجيل المصنع ورمز المحافظة بحرفين — VI لفيتشنزا وAR لأريتسو وMI لميلانو. وهذا يعرّف الورشة، مو إنه فحص من جهة رسمية."),
    action: L("Read the number as the maker's licence and the fineness as the maker's own declaration — Italy self-certifies, so an independent test still matters on a large purchase. Chains labelled 'Italy' with no oval mark are usually not Italian-made.", "اعتبر الرقم رخصة الصانع والعيار إقرار منه، لأن إيطاليا نظامها تصديق ذاتي، فالفحص المستقل يبقى مهم بأي شرا كبير. والسلاسل المكتوب عليها «Italy» بدون البيضاوي غالباً مو إيطالية."),
  },
  {
    id: "india-bis",
    title: L("Indian BIS Hallmark", "دمغة BIS الهندية"),
    subtitle: "BIS + 22K916 + HUID",
    severity: "info",
    summary: L("Three parts since 2021: the BIS triangle logo, the purity (22K916, 18K750, 14K585) and a six-character HUID code unique to that one item. Anything carrying only two of the three is an older mark.", "من 2021 صارت من ثلاث أجزاء: مثلث BIS، ونسبة العيار (22K916 أو 18K750 أو 14K585)، ورمز HUID من ست خانات خاص بهالقطعة لحالها. وأي قطعة فيها جزئين بس تعتبر دمغة قديمة."),
    action: L("Type the HUID into the free BIS Care app before you pay — it returns the jeweller's name and the tested purity for that exact piece. If the code returns nothing, do not complete the purchase.", "ادخل رمز HUID بتطبيق BIS Care المجاني قبل ما تدفع — بيطلع لك اسم المحل والعيار المفحوص لنفس القطعة. وإذا الرمز ما طلع نتيجة، لا تكمّل الشرا."),
  },
  {
    id: "gulf-assay",
    title: L("Gulf Assay Marks", "دمغات الخليج"),
    subtitle: "Dubai Central Laboratory / SASO",
    severity: "warning",
    summary: L("Gulf gold is usually stamped with the karat and the shop's own mark rather than a national assay stamp. The UAE has the Dubai Central Laboratory mark and Saudi has SASO-regulated stamps, but a plain '21' or '875' beside a shop logo is far more common.", "ذهب الخليج غالباً مدموغ بالعيار وبختم المحل نفسه، مو بدمغة فحص وطنية. الإمارات عندها دمغة مختبر دبي المركزي، والسعودية عندها دمغات تحت إشراف المواصفات، بس الأغلب تلقاه «21» أو «875» مع شعار المحل."),
    action: L("Buy from a licensed shop, take a printed invoice showing weight, karat and making charge, and watch the piece go on the scale. For a large purchase, have any second gold shop test it before the return window closes.", "اشتر من محل مرخّص، وخذ فاتورة مطبوعة فيها الوزن والعيار والمصنعية، وخل الوزن يصير قدام عينك. وإذا الشرا كبير، ودّه لأي محل ذهب ثاني يفحصه لك قبل ما تنتهي مدة الإرجاع."),
  },
  {
    id: "fake-stamp-spelling",
    title: L("Wrong Spelling or Format", "دمغة غلط بالكتابة"),
    subtitle: "Misspelled or Odd Stamp",
    severity: "critical",
    summary: L("Counterfeiters get the wording wrong: 'STERLING SILVER' misspelt, a word spelled out where a genuine mark uses just '925', karat numbers no jeweller uses such as 20K or 23K on a Western piece, or a stamp with mixed fonts and uneven depth.", "المقلّدين يغلطون بالكتابة: «STERLING SILVER» بإملاء غلط، أو كلمة مكتوبة كاملة بمكان الرقم 925 المعتاد، أو أرقام عيارات ما يستخدمها أحد مثل 20K و23K على قطعة غربية، أو دمغة بخطوط مختلفة وعمق غير متساوي."),
    action: L("Read every character under a 10x loupe before paying, and compare it with a piece from a shop you trust. A stamp that is crooked, smeared, or pressed to a different depth than the rest was almost certainly added later.", "اقرا كل حرف بعدسة تكبير 10x قبل ما تدفع، وقارنها بقطعة من محل تثق فيه. وأي دمغة مايلة أو ملطوشة أو محفورة بعمق مختلف عن باقي الحروف غالباً انضافت لاحقاً."),
  },
  {
    id: "fake-magnet-wear",
    title: L("Magnet and Wear Tells", "المغناطيس وأثر الاستعمال"),
    subtitle: "Magnet, Wear and Colour",
    severity: "critical",
    summary: L("Gold, silver and platinum are not magnetic — if a strong magnet pulls the piece, the core is steel or another base metal. Brassy or coppery colour showing at clasps, edges and the inside of a ring, or green-black marks on your skin, means the plating has worn through.", "الذهب والفضة والبلاتين ما تنجذب للمغناطيس — فإذا مغناطيس قوي شدّ القطعة، يعني قلبها حديد أو معدن رخيص. ولون نحاسي أو أصفر باين عند المشبك والأطراف وداخل الخاتم، أو أثر أخضر وأسود على جلدك، يعني الطلا راح."),
    action: L("Run a strong magnet over the whole piece, clasp included, and inspect the high-wear points under good light. If either check fails, stop and have it properly tested before any money changes hands.", "مرّر مغناطيس قوي على القطعة كاملة وعلى المشبك، وافحص الأماكن اللي تتحك كثير تحت إضاءة زينة. وإذا طلع أي واحد من الاثنين، وقّف وخلها تنفحص قبل ما تدفع فلوس."),
  },
  {
    id: "fake-clasp-only",
    title: L("Unmarked or Clasp-Only", "بدون دمغة أو الدمغة بالمشبك فقط"),
    subtitle: "No Mark / Clasp-Only Mark",
    severity: "warning",
    summary: L("A missing stamp does not prove a fake — old, handmade and many Middle Eastern pieces were never stamped. But a mark on the clasp alone is a known trick: a genuine gold clasp is soldered onto a plated chain so the stamp passes inspection.", "غياب الدمغة ما يعني بالضرورة تقليد — القطع القديمة واليدوية وكثير من الشغل الشرقي ما كانت تندمغ أصلاً. بس الدمغة على المشبك لحاله حيلة معروفة: يلحّمون مشبك ذهب أصلي على سلسلة مطلية عشان تعدي."),
    action: L("Ask the jeweller to test the body of the piece, not the clasp — a non-destructive XRF test takes a minute and most shops do it free. Never treat a stamp alone as proof on a purchase you cannot afford to lose.", "اطلب من الصايغ يفحص جسم القطعة نفسها مو المشبك — فحص XRF ما ياخذ دقيقة وأغلب المحلات تسويه مجاناً. ولا تعتمد على الدمغة لحالها كإثبات بأي شرا ما تقدر تخسره."),
  },
];
