/**
 * The content bank, generated from the guide rather than written beside it.
 *
 * A crisis app cannot be sold the way a habit app is sold. Nobody watches a
 * demo of a dashboard scanner and installs it, because their dashboard is dark
 * — the demand is not standing there waiting to be captured, it arrives on a
 * day nobody can schedule. So the content that works here is not the app. It
 * is the warning itself: "if this light is flashing, do not keep driving" is
 * something a driver watches to the end, saves, and sends to their brother.
 * The app is the answer at the end of it, not the subject.
 *
 * Which means the content bank already exists in this repository. Forty-eight
 * lights, each with a severity, a plain-language explanation and one action,
 * already written, already reviewed, already in two languages. Writing scripts
 * beside them by hand would be transcribing them into a form that can drift —
 * and a video that gives outdated safety advice is worse than no video, because
 * it stays up.
 *
 *   node scripts/content-bank.js            write store/content-bank.md
 *   node scripts/content-bank.js --check    fail if it is out of date
 */
const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const ts = require(path.join(ROOT, "node_modules/typescript"));
const OUT = path.join(ROOT, "store/content-bank.md");

/* ---------------------------------------------- the real library, not a copy */

const src = fs.readFileSync(path.join(ROOT, "src/packs/dashlight-library.ts"), "utf8");
const js = ts.transpileModule(src, {
  compilerOptions: { target: ts.ScriptTarget.ES2020, module: ts.ModuleKind.CommonJS },
}).outputText;
const mod = { exports: {} };
new Function("module", "exports", "require", js)(mod, mod.exports, (id) =>
  id.includes("i18n") ? { L: (en, ar) => ({ en, ar }) } : {},
);
const LIBRARY = mod.exports.DASHLIGHT_LIBRARY;

/* -------------------------------------------------------------------- hooks

   The first two seconds decide whether the rest is watched, and the three
   severities are three different promises. A critical light is a warning; a
   warning light is a deadline; an info light is a small piece of knowledge
   somebody enjoys having. Reading the same hook over all three wastes the two
   that are not emergencies. */

const HOOK = {
  critical: {
    en: "If this light comes on, stop the car.",
    ar: "إذا اشتعلت هذه اللمبة، أوقف السيارة.",
  },
  warning: {
    en: "This light is not an emergency. It is a deadline.",
    ar: "هذه اللمبة ليست حالة طارئة، لكنها موعد نهائي.",
  },
  info: {
    en: "Most drivers can't name this one.",
    ar: "أكثر السائقين لا يعرفون اسم هذه اللمبة.",
  },
};

/** Most dangerous first: the eight critical lights are the ones somebody sends
 *  to someone else, and the order of the bank is the order to shoot in. */
const RANK = { critical: 0, warning: 1, info: 2 };

/* --------------------------------------------------- what must not be shot yet

   Two entries show the wrong picture — `symbol-specs.md` has the briefs. Inside
   the app that is a bug in two of forty-eight rows. In a video it is worse: the
   whole premise is *match the shape in front of you*, and a video teaching a
   driver the wrong shape for a red "stop the engine" light is a mistake that
   keeps working after it is found. */

const WRONG_SYMBOL = new Set(["oil-level-low", "transmission-overheat"]);

/** One sentence, so a six-second body is not a paragraph nobody finishes. */
const firstSentence = (text) => {
  const cut = text.match(/^[^.。؟?!]*[.؟?!]/);
  return (cut ? cut[0] : text).trim();
};

const entries = [...LIBRARY].sort(
  (a, b) => RANK[a.severity] - RANK[b.severity] || a.id.localeCompare(b.id),
);

const lines = [];
const say = (s = "") => lines.push(s);

say("# Content bank — Dash Light");
say();
say("**Generated by `node scripts/content-bank.js`. Do not edit by hand.**");
say("Every line below is the app's own text. Editing it here would put safety");
say("advice in a video that the app itself no longer gives.");
say();
say(
  `${entries.length} lights, most dangerous first — which is also the order to shoot in, ` +
    "because the eight red ones are the videos somebody forwards.",
);
say();
say("Each block is the seven-second form: hook, what it means, one action, then the app.");
say("Shoot the dashboard, not a screen recording. The app appears at the end, once.");
say();
say("**The safety rule holds in a caption as it does on a screen:** never say the car");
say("is safe. The app says what the lamp does or does not require — it is one photo of");
say("one lamp, and it cannot see smoke, hear a bearing, or feel the steering.");
say();
say("Carry the disclaimer in the caption of every video giving an instruction:");
say("> Guidance from a photo, not a technical diagnosis. It does not replace a mechanic.");
say();
say("---");

let severity = null;
for (const entry of entries) {
  if (entry.severity !== severity) {
    severity = entry.severity;
    const count = entries.filter((e) => e.severity === severity).length;
    say();
    say(`## ${severity} — ${count}`);
  }

  say();
  say(`### ${entry.title.en} · ${entry.title.ar}`);
  say(`\`${entry.id}\` — ${entry.subtitle}`);
  if (WRONG_SYMBOL.has(entry.id)) {
    say();
    say(
      "> **Do not shoot this one yet.** The pictogram in the app is the wrong symbol " +
        "(`symbol-specs.md`). A video teaching the wrong shape outlives the fix.",
    );
  }
  say();
  say("| | English | العربية |");
  say("|---|---|---|");
  say(`| **Hook** 0–2s | ${HOOK[entry.severity].en} | ${HOOK[entry.severity].ar} |`);
  say(`| **Body** 2–6s | ${firstSentence(entry.summary.en)} | ${firstSentence(entry.summary.ar)} |`);
  say(`| **Action** 6–9s | ${entry.action.en} | ${entry.action.ar} |`);
}

say();
say("---");
say();
say("## The three that are not in this bank");
say();
say("1. **The scan itself.** A screen recording of a photograph becoming a verdict is");
say("   a product demo, and product demos are watched by people who already want the");
say("   product. The dashboard is the shot.");
say("2. **The model.** Nobody installs an app because of what runs inside it. They");
say("   install it because they do not know whether they can keep driving.");
say("3. **A discount.** Stating one in the app is a review finding, and stating one in");
say("   a video is a promise the storefront may not keep.");

const bank = lines.join("\n") + "\n";

if (process.argv.includes("--check")) {
  const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, "utf8") : "";
  if (current === bank) {
    console.log(`ok   the content bank matches the guide (${entries.length} lights)`);
    process.exit(0);
  }
  console.log("FAIL the content bank is out of date — run: node scripts/content-bank.js");
  console.log("     A shot list that disagrees with the app is safety advice the app withdrew.");
  process.exit(1);
}

fs.writeFileSync(OUT, bank);
console.log(`Wrote ${path.relative(ROOT, OUT)} — ${entries.length} lights.`);
